### ISSUE TITLE
Errore in Get Status Strumento Pagamento H/M Banking

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#100]
Abbiamo effettuato correttamente Enroll della carta come da nuove specifiche, ovvero:

**PUT** https://bpd-dev.azure-api.net/bpd/hb/payment-instruments/card
REQUEST:
{
    "id": "**1234567890123458**",
    "fiscalCode": "AAABBB11X11X111A",
    "expireYear": 2025,
    "exprireMonth": 12,
    "issuerAbiCode": "36003",
    "brand": "Mastercard",
    "holder": "Alberto Gialli",
    "type": "DEB",
    "channel": "36003"
}

NOTA: Trattandosi di SIT il PAN qui non è cifrato.

Tuttavia chiamando l'API per il recupero stato della carta riceviamo errore come da dettagli in seguito:

GET  https://bpd-dev.azure-api.net/bpd/hb/payment-instruments/card/**1234567890123458**

RESPONSE:
{
    "statusCode": 404,
    "message": "Resource not found"
}

**Comment by ChristianRoldo** [comment]
è sbagliato l endpoint .. non deve avere card al fondo la get..
riprova senza

**Comment by DenisaBraho** [comment]
Ciao, confermiamo  che per il recupero status l'endpoint non è quello corretto,
Provvediamo con la chiusura issue. Se riscontrate un errore non atteso anche in questo caso, vi chiediamo di procedere con l'apertura di una nuova issue
saluti
