### ISSUE TITLE
Errore in API "Recesso del Cittadino"

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#101]
Chiamando l'API di "recesso del cittadino" in SIT:

DELETE: https://test.cstar.pagopa.it/bpd/hb/citizens/**AAABBB11X11X111A**

Riceviamo l'errore:
{
    "statusCode": 500,
    "message": "Internal server error",
    "activityId": "e8e18ab9-7f0a-4144-90a3-39697b11584b"
}

Inoltre, ci confermate che:

1. Il recesso rimuove dai vostri sistemi automaticamente gli strumenti di pagamento e IBAN associati dal cittadino?
2. il recesso è efficace anche in caso il cittadino dovesse aver sottoscritto strumenti di pagamento anche con altri issuer (o avesse l'IBAN associato ad un altro issuer)?

**Comment by daniloMessinaSia** [comment]
Buonasera,
i caratteri ** fanno parte della chiamata?

rispondo ai punti:
1. il recesso rimuove gli strumenti, le informazioni relative all'IBAN, la classifica accumulata e le transazioni ricevute (tutto questo pacchetto di informazioni non sarà più visualizzabile qual'ora l'utente decidesse di reiscriversi)
2. se in fase di recesso dovessero essere riscontrati strumenti di pagamento enrollati con altri issuer, verrà restituito un errore 409 che blocca il processo di recesso. l'utente dovrà esereguire la disattivazione dei vari touchpoint degli issuer o il recesso direttamente da app IO

**Comment by DenisaBraho** [comment]
Ciao, @albertosangalliflowe  
ci sono novità in merito alla chiamata di recesso? Inolte, dal endopoint notiamo che la chiamata è stata fatta in UAT e non SIT.
Saluti

**Comment by albertosangalliflowe** [comment]
Buongiorno,
ho appena provato e vi confermo l'errore:

DELETE: https://bpd-dev.azure-api.net/bpd/hb/citizens/AAABBB11X11X111A
RESPONSE: 
{
    "statusCode": 500,
    "message": "Internal server error",
    "activityId": "66dd5010-57cb-4cda-9962-c9dfde279d86"
}

NOTA:
L'utente con il CF indicato attualmente in SIA ha carta e Conto corrente Enrolled.

**Comment by mdesogus** [comment]
Buongiorno,

potreste cortesemente fornirci anche il body della chiamata?

**Comment by albertosangalliflowe** [comment]
Scusate, mancava il "channel" nel body della chiamata.

Ora con il seguente body:
DELETE: https://bpd-dev.azure-api.net/bpd/hb/citizens/AAABBB11X11X111A
REQUEST
{
    "channel": "36003"
}

RESPONSE:
{
    "returnMessages": {
        "ERROR": [
            {
                "message": "Unknown",
                "messageTitle": "Unknown",
                "messageKey": "too many channels",
                "retry": false,
                "errorCode": "UNKNOWN",
                "severity": "ERROR"
            }
        ]
    }
}

Stesso errore descritto in questa issue: https://github.com/pagopa/issuer_integration/issues/78

**Comment by DenisaBraho** [comment]
Ciao,
qualora l'utente abbia enrollato piu carte da canali diversi l'errore è da ritenersi atteso, mentre non è atteso nel caso in cui ha enrollato una/piu carte con lo stesso canale. La casistica in questione è la seconda? Stiamo comunque conducendo le analisi del caso, vi aggiorniamo appena possibile

**Comment by mdesogus** [comment]
Buongiorno,

potreste ripetere il test e fornirci riscontro?

grazie

**Comment by DenisaBraho** [comment]
Ciao, 
il servizio attualmente risulta funzionante e non riscontriamo errori. Procediamo con la chiusura della issue. Qualora si ripresentasse un errore, vi chiediamo di procedere con l'apertura di una nuova issue. 
Grazie
Saluti
