### ISSUE TITLE
Disattivazione Cashback

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#102]
potreste per favore disattivare il servizio per queste utenze? 

TSTCRT37A29M264P
CSSQRT76H60H501P
NVCLDA81D58G702N
CSAVTR80A01H501M
NVCLDA81D58G702N
PTNGRG80A01H501Y
TMSMTN80A01H501N
NVCBNT77E22F205T
PPCLSA70A08H501Z
PPCDDT70B04H501U
CNNBCK80A01H501Q
MCCNTN71E07G942P
MCCMHL71E07G942P
KRGFDD90L03F839Z
MCHMRS90L03F839Z
LCSNDR80C10L845Y
CPPDVD86E05H501C
MRNCNC80A41D236Z
RCHDEA80A41G813S
PRTCNR80A01F839L
DDCDBP66A01L736X
CNDSEI80A01H501W
PLARST80A01H501Z
JMSMRS90L20Z110I
CRBDYN84L63I535J
FLVNDR89B27F839K
DMMMLN76R58C514Q
MSTNNL90T01H501T
RSSNEE99A01H501L

**Comment by lucasomarugasia** [comment]
Chiudo, obsoleta
