### ISSUE TITLE
GET payment-instruments in SIT

### ISSUE THREAD

**Issue by ChristianRoldo** [pagopa/issuer_integration#103]
In sit abbiamo eseguito su endpoint 

/bpd/hb/payment-instruments/card
`
{   "id":"-----BEGIN PGP MESSAGE-----\nVersion: BCPG C# v1.6.1.0\n\nhQEMA+NENQPn0iNJAQf9EkUoFrMuUjkHG7MUMSUC/4rkTvLbWtD3sd3nNxC/NrWU\nEVQ4j/DIBCANQibBE2Z0plmKyQalTz+470ucxnxGlSNSBBcHlHxTaP+NJl8bYCaG\n2yhX0M2zR01K8CRQ08LAQbtBdww0X1ZwsvHaX8zYv4JCBxF15lkargdQE2ZefUSz\n3+0aE1/252aTUyOQ8P0jaXZUNC+zSYoXbsc9cU8WrDCdhVtgz5oz6f6DWfy92Jw3\nAY8fuIIYXu3u9E0o6IUJ+FblYR5lSUTYdJ5+r2w9Cmrv1Wm10jpLW1+SmWpW9ksI\nl+0sOHs0Z654piPc7X/cwazPL8g3oR/Tl0OUTRdty8kuN8EYzxkHBtuw0hAGEMUg\nOgJCyMfa6xBD7QxMOJcc7OvNjT7qcGAKOjFrMoEvjQ==\n=EQOg\n-----END PGP MESSAGE-----\n",
    "fiscalCode": "RLDCRS78B08A859N",
    "expireYear": "2022",
    "exprireMonth": "05",
    "issuerAbiCode": "03268",
    "brand": "VISA",
    "holder": "ROLDO CHRISTIAN",
    "type": "CRD",
    "channel": "03268"
} `
( ho provato con expireMonth e exprireMonth ) 

Otteniamo correttamente l activation date. 
Il pan inserito è 4775710112345678

Se proviamo la GET 

/bpd/hb/payment-instruments/4775710112345678

otteniamo l errore

`{
    "returnMessages": {
        "ERROR": [
            {
                "message": "il campo %s supporta solamente il tipo %s",
                "messageTitle": "Risorsa non trovata",
                "messageKey": "resource.not-found.error",
                "severity": "ERROR"
            }
        ]
    }
}`

**Comment by daniloMessinaSia** [comment]
Buonasera,
come da specifiche, in ambiente di SIT non è possibile chiamare con PAN cifrato con chiave PGP.
è necessario invocare i servizi con il PAN in chiaro.

**Comment by ChristianRoldo** [comment]
Nelle specifiche c e scritto che è possibile chiamare senza chiave.. Non che DEVE essere chiamato non criptato
