### ISSUE TITLE
status carta - 503

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#104]
- AUTH LEVEL [https://idp.poste.it/L2] - USERID [dyn.carbone] - CASHBACK - WSCall - StatusStrumentoPagamentoCashBackCommand - StatusStrumentoPagamentoRequest{​​​pan='5354760546516436'}​​​ org.jod.cashback.dto.bonuspagamentidigitali.statusstrumentopagamento.v1.StatusStrumentoPagamentoRequest@2841025a]                              [DEBUG]   [28/11/2020 10.12.02 311] [pool-4-thread-44] [SCA - SESSIONID [819360D9CF5CA7187CB4594BD254A151.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [dyn.carbone] - CASHBACK - WSCall -  START BonusPagamentiDigitaliService - statusStrumentoPagamento ]          [INFO]    [28/11/2020 10.12.02 312] [pool-4-thread-44] [SCA - SESSIONID [819360D9CF5CA7187CB4594BD254A151.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [dyn.carbone] - CASHBACK - WSCall - BonusPagamentiDigitaliService - statusStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5354760546516436]]                [INFO]    [28/11/2020 10.12.02 312] [pool-4-thread-44] [SCA - SESSIONID [819360D9CF5CA7187CB4594BD254A151.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [dyn.carbone] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 0673f888-ca47-4e76-a6ac-1ae9bd19f3a2]]                                        [INFO]    [28/11/2020 10.12.02 312] [pool-4-thread-44] [SCA - SESSIONID [819360D9CF5CA7187CB4594BD254A151.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [dyn.carbone] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5354760546516436]                                                                                [INFO]    [28/11/2020 10.12.02 693] [pool-4-thread-44] [SCA - SESSIONID [819360D9CF5CA7187CB4594BD254A151.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [dyn.carbone] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP STATUS[503]]                                                              [INFO]    [28/11/2020 10.12.02 694] [pool-4-thread-44] [SCA - SESSIONID [819360D9CF5CA7187CB4594BD254A151.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [dyn.carbone] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP ENTITY[]]

**Comment by lucasomarugasia** [comment]
Ciao Nicola, 
gli errori che riceverete in giornata su status carta sono inputabili alle attività di performance test che stiamo eseguendo in parallelo su CentroStella
