### ISSUE TITLE
Status utente - 503

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#105]
salve riscontriamo errore 503 alla chiamata dello status carta

o.v1.StatusStrumentoPagamentoRequest@4ec06ca0]                            [DEBUG]   [28/11/2020 11.43.51 515] [pool-4-thread-323] [SCA - SESSIONID [A7BFBD15543D0B88AB0BA75273A04452.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [eneaa.rossii] - CASHBACK - WSCall -  START BonusPagamentiDigitaliService - statusStrumentoPagamento ]        [INFO]    [28/11/2020 11.43.51 515] [pool-4-thread-323] [SCA - SESSIONID [A7BFBD15543D0B88AB0BA75273A04452.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [eneaa.rossii] - CASHBACK - WSCall - BonusPagamentiDigitaliService - statusStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030]]              [INFO]    [28/11/2020 11.43.51 515] [pool-4-thread-323] [SCA - SESSIONID [A7BFBD15543D0B88AB0BA75273A04452.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [eneaa.rossii] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 4acabc17-12f5-4e2a-a366-614207650a89]]                                      [INFO]    [28/11/2020 11.43.51 515] [pool-4-thread-323] [SCA - SESSIONID [A7BFBD15543D0B88AB0BA75273A04452.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [eneaa.rossii] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030]                                                                              [INFO]    [28/11/2020 11.43.51 878] [pool-4-thread-323] [SCA - SESSIONID [A7BFBD15543D0B88AB0BA75273A04452.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [eneaa.rossii] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP STATUS[503]]                                                            [INFO]    [28/11/2020 11.43.51 879] [pool-4-thread-323] [SCA - SESSIONID [A7BFBD15543D0B88AB0BA75273A04452.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [eneaa.rossii] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP ENTITY[]]                                                               [ERROR]   [28/11/2020 11.43.51 879] [pool-4-thread-323] [SCA - SESSIONID [A7BFBD15543D0B88AB0BA75273A04452.mobile] -  COMMAND SCA [Async - v1/bancoposta/statoUt

**Comment by DenisaBraho** [comment]
Ciao @NicolaLamberti ,
l'anomalia dovrebbe essere rientrata. Potreste verificare e fornirci un riscontro?
Saluti

**Comment by DenisaBraho** [comment]
ciao nicola, chiudiamola issue. Se il problema si ripresenta, potete procedere con la riapertura issue.
Grazie
