### ISSUE TITLE
time out - chiamata Status Utente

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#106]
salve, 

durante le chiamate al servizio Status Utente riscontriamo spesso dei time out come evidenziato dal log di seguito

[DEBUG] [28/11/2020 16.59.07 266] [pool-4-thread-265] [SCA - SESSIONID [E01C3AE608AC38C020A52D2B73ADCC75.mobile] - COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [cenere.porta] - CASHBACK - WSCall - START BonusPagamentiDigitaliService - enrollmentCitizenStatus ]
[INFO] [28/11/2020 16.59.07 266] [pool-4-thread-265] [SCA - SESSIONID [E01C3AE608AC38C020A52D2B73ADCC75.mobile] - COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [cenere.porta] - CASHBACK - WSCall - BonusPagamentiDigitaliService - enrollmentCitizenStatus - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/citizens/PRTCNR80A01F839L]]
[INFO] [28/11/2020 16.59.07 266] [pool-4-thread-265] [SCA - SESSIONID [E01C3AE608AC38C020A52D2B73ADCC75.mobile] - COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [cenere.porta] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 002bef56-5c37-4ee5-9292-9411e9166b15]]
[INFO] [28/11/2020 16.59.07 266] [pool-4-thread-265] [SCA - SESSIONID [E01C3AE608AC38C020A52D2B73ADCC75.mobile] - COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [cenere.porta] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/citizens/PRTCNR80A01F839L]

[ERROR] [28/11/2020 16.59.12 566] [pool-4-thread-265] [SCA - SESSIONID [E01C3AE608AC38C020A52D2B73ADCC75.mobile] - COMMAND SCA [Async - v1/bancoposta/statoUtenteCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [cenere.porta] - CASHBACK - WSCall - BonusPagamentiDigitaliService - Exception] [java.net.SocketTimeoutException:
Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:171)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
at sun.security.ssl.InputRecord.read(InputRecord.java:503)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)

**Comment by DenisaBraho** [comment]
Ciao,
l'anomalia dovrebbe essere rientrata (nel weekend erano in corso dei test di performance che impattavano dei servizi)
Saluti
