### ISSUE TITLE
Errore generale in update iban

### ISSUE THREAD

**Issue by antessio** [pagopa/issuer_integration#108]
Ambiente : UAT
API: `PATCH /bpd/hb/citizens/<id>` 
request-id : b17c28c3-c07a-40cd-8eb2-7539d8882020

Il servizio risponde con il seguente errore:

```json
{"returnMessages":{"error":[{"message":"Errore generale contattare l'assistenza","messageTitle":"Errore Generale","messageKey":"generic.error","errorCode":null,"severity":"ERROR"}]}} 
```

**Comment by mdesogus** [comment]
Buongiorno,

Potreste fornirci anche il body della chiamata?

**Comment by antessio** [comment]
```json
{
	"accountHolderCF": "BRBWTR89T25L407I",
	"accountHolderName": "walte",
	"accountHolderSurname": "barbagallo",
	"payoffInstr":"IT97E0306967684510327634636",
	"payoffInstrType": "IBAN"
	
}
```

**Comment by daniloMessinaSia** [comment]
Buongiorno,
è possibile riprovare e fornirci riscontro?

Grazie

**Comment by antessio** [comment]
Buongiorno,
risolto. L'utente è riuscito a completare l'attivazione e l'enrollment

Grazie
