### ISSUE TITLE
ABI Issuer

### ISSUE THREAD

**Issue by Carrettoni** [pagopa/issuer_integration#109]
Si richiede un chiarimento relativo alla valorizzazione dell’ABI Issuer nei campi “issuerAbiCode” rispetto al campo “channel” del metodo /bpd/hb/payment-instruments/card/{id}

Considerando lo scenario in cui ABI Issuer (ABI X) che detiene la licenza (principal member Visa / Mastercard) differisce dall’ABI del soggetto che intrattiene il rapporto con il cliente (ABI Y) come devono essere valorizzati i valori di issuerAbiCode e channel? ABI X o ABI Y?

Grazie

**Comment by DenisaBraho** [comment]
Buongiorno,
entrambi i campi servono per identificare l'issuer che mette a disposizione l'interfaccia al proprio cliente e devono essere valorizzati con lo stesso dato. Nel caso di Banca Sella ( basandoci anche sulla valorizzazione del codice abi proveniente nel file delle trx in veste di Acquirer ) ci aspettiamo di ricevere nei campi in questione il codice "03268"
Rimaniamo a disposizione per qualsiasi chiarimento
Saluti

**Comment by Carrettoni** [comment]
Provo a spiegarmi meglio.

Hype (ABI 36772) emette carte come participant di Banca Sella (ABI 03268) e Banca Sella ovviamente emette direttamente anche carte per i propri clienti.

Gestendo noi (Centrico) entrambi gli ABI come dobbiamo comportarci visto che le interfaccie al cliente sono distinte tra Banca Sella ed Hype?

Possiamo valorizzare nel caso di carte emesse da Hype entrambe i campi con 36772  anche se issuer (principal member) è Sella?

Grazie
Fabio

**Comment by DenisaBraho** [comment]
Ciao Fabio,
grazie dell'esempio fornito. Di seguito,, riportiamo i valori attesi nei campi “issuerAbiCode” e "channel":

1.  “issuerAbiCode” - valorizzato sempre con il codice del Principal Member ( es. in questo caso codice Banca Sella = 03268)
2. "channel" - valorizzato con il codice ABI dell'issuer che mette a disposizione l'interfaccia. Relativamente all'esempio fornito, il campo puo essere quindi valorizzato con il codice ABI di Hype oppure con il codice ABI di Banca Sella in base alla interfaccia di riferimento. In particolare:
- per le chiamate provenienti da Hype ci aspettiamo nel channel "36772" mentre IssuerAbiCode quello di B.Sella (03268),
- per le chiamate da Banca Sella ci aspettiamo entrambi i codici uguali e valorizzati con  03268 (Banca Sella).

A disposizione
Saluti
