### ISSUE TITLE
Carte che addebitano su conto non dell'issuer + check sul soggetto fisico

### ISSUE THREAD

**Issue by luca1oo** [pagopa/issuer_integration#11]
Buonasera,
se come issuer emettiamo carte a cliente ma che addebbitano su un conto di altro issuer, non possiamo prevedere l'iscrizione al programma da nostro H/B? Dobbiamo permettergli di inserire un IBAN di altro issuer in fase di onboarding.

In aggiunta, saranno effettuati dei controlli lato CentroStella sulla maggiore età e residenza del soggetto che si iscrive all'iniziativa?

Grazie
Luca

**Comment by DenisaBraho** [comment]
Ciao,
nel caso di inserimento IBAN dal H/M Banking, l’utente può inserire solo IBAN a lui intestati associati esclusivamente a conti aperti presso la Banca Issuer che mette a disposizione il portale stesso. Tuttavia, l'inserimento dell'IBAN non è mandatorio per concludere l'iscrizione al servizio di BPD. L'utente nel caso volesse inserire l'IBAN di un'altro issuer, potrà saltare lo step di inserimento IBAN e proseguire con il completamento dell' iscrizione. La compilazione del campo IBAN da parte dell'utente, puo avvenire successivamente accendendo all'app/portale HM dell'issuer presso il quale è stato aperto il conto, oppure direttamente da APP IO. 

Non sono previsti controlli da CentroStella sui dati età e/o residenza, tuttavia i check sono da considerarsi garantiti in quanto APP IO prevede l'iscrizione all'app tramite CIE o SPID.
