### ISSUE TITLE
Errore cifratura PAN

### ISSUE THREAD

**Issue by mrossano** [pagopa/issuer_integration#110]
Ciao,
integrando la cifratura del PAN in ambiente di UAT ottengo sempre l'errore 400 ErrorPM.

L'errore risulta non essere documentato e non da indicazioni su cosa potrebbe essere sbagliato.

L'errore dovrebbe essere legato alla modalità con cui viene effettuata la cifratura ma anche inserendo il valore di esempio riportato nella documentazione:
{"id":"-----BEGIN PGP MESSAGE-----\nVersion: BCPG C# v1.6.1.0\n\nhQEMA+NENQPn0iNJAQf/ee9tRkksD+IhY84e2SG4Or51kopVtwWbysbzEpWX0oAo\n0aVLq10BHbTs2zEG1L1Xwqf24YrrRvc6IUX73j4Xh6n//Mz7op8dCD47uMSVeSDa\n9EMd239jDKD31d6O3I1CEPfnaTVOPy4veHxgNn6deWxdUai9a1RCZMJXO9AXWKtu\n6oVjUMWiJhpT8zK9OO2KT+YpMUWp8CTJfoQQVMdZx8lqpYvXvmblAAtT7HZfGn41\nFYnPv07mOseniLI5jOeHcUwDb2uVZExysxfotgW8VECUXT/39kLYkqzh4USyvVWo\nMC9XN1Jo3iXV6Z1BYDS9f/BydHPk3EGJeOk41QVY68kuVMrPTKAMluHg49E0vj+X\nSVEP14vqqNn0hsRJDDOYnFUVbOlEhYHW4q31mttOIw==\n=7n38\n-----END PGP MESSAGE-----\n","fiscalCode":"CCCMLG80A01C588S","expireYear":"2022","expireMonth":"11","issuerAbiCode":"36085","brand":"MASTERCARD","holder":"Manuel Rossano","type":"PP","channel":"36085"}

Aggiungo che nella documentazione non è specificato l'algoritmo di cifratura da utilizzare. Potreste indicarlo?

**Comment by daniloMessinaSia** [comment]
Buongiorno, 
a giudicare dalla request il campo expireMonth è errato, il campo corretto è "exp**r**ireMonth"
si prega di rettificare e riprovare l'enrollment,

Grazie

**Comment by mrossano** [comment]
Ciao,
grazie per la repentina risposta, stiamo stati fuorviati dallo swagger e dalla console developer dove ancora il campo è "expireMonth".
