### ISSUE TITLE
Get Status Strumento Pagamento H/M Banking - PAN Cifrato

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#111]
Sarà necessario prevedere la cifratura del PAN anche in Sede di Get Status dello strumento di Pagamento (come per l'enroll della carta)?
Se sì, in che modo sarà cifrato (e passato) il pan di carta in questo scenario ?

**Comment by DenisaBraho** [comment]
Ciao ,
no, la cifratura non è prevista per lo get status PI, ma solo per l'enrollment dello strumento di pagamento. La necessità di cifratura in sede di enrollment è dovuta alla presenza nella chiamata dei dati sensibili PAN e scadenza carta. 
Saluti
