### ISSUE TITLE
Errore in PUT payment-instruments

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#112]
Buonasera, in ambiente di **produzione**, stiamo avendo degli errori _404 - Not Found_ in fase di iscrizione strumento di pagamento

{
    "id": "-----BEGIN PGP MESSAGE-----\nVersion: BCPG v1.65\nhQEMA2HL/E0/MRALAQf/ZmycZeGgkjWLEvE7oupl7qV/TegJ9HrI1NR/4CrPPOMB\n/85cwNz8lXGyhOnb76Lj1crJtSdtReYMY7Jn36D/tX3Yv4xWsn8lUr9+1q0ONdlu\nxMeTHvwkC+WY2LaXYxV2746jDlD/2P7WHLaJYdbI1B2ST4MbdUfb1iMUDqPqoN2A\nX2dOt8y9LNrgMHdmxTNh4GqEK4KUAVFC6QE/B7bqznAM4N248OyQFKRsDbp/d9U+\nZimn0022K3dh3miJp1Xcu3lFPPDAEjvB7kVhEB4AEJVR5pkKtj1l4ryU6C6pHnvo\ntNB/WrhOD4zHwcmYgFUTyzEX1qrHclIi004zdgi6S9JLATJkYjRbfEjI3N3VIyB3\n7HmMl7xpTXU660AbkkFzZd8TB/WjEuv/CPxIdYyUM8wAjxF3UoIKj5pLsNiP9YJW\nspHXp/34QoTEDHup\n=ho/P\n-----END PGP MESSAGE-----",
    "fiscalCode": <codice_Fiscale_Utente>,
    "expireYear": "2023",
    "exprireMonth": "02",
    "issuerAbiCode": "32875",
    "brand": "MASTERCARD",
    "holder": <denominazione_Utente>,
    "type": "PP",
    "channel": "32875"
}

Potete verificare?
Grazie

**Comment by AndreaCaccin** [comment]
Porve eseguite il

- 2020-11-30 17:45:26,498

- 2020-11-30 17:46:51,361

- 2020-11-30 18:14:22,138

**Comment by AndreaCaccin** [comment]
Buonasera, oggi, per lo stesso ambiente, produzione, e la stessa carta otteniamo l'errore 
_"ERROR": [
            {
                "message": "Errore generale contattare l'assistenza",
                "messageTitle": "Errore Generale",
                "messageKey": "generic.error",
                "severity": "ERROR"
            }
        ]_
Potete verificare e darci un riscontro?
Grazie

**Comment by mdesogus** [comment]
Buongiorno, 

potreste cortesemente ripetere il test e fornirci l'esito?

grazie

**Comment by AndreaCaccin** [comment]
Buongiorno, riprovato alle 2020-12-02 16:01:00,442, stesso risultato
status 500 - response {"returnMessages":{"ERROR":[{"message":"Errore generale contattare l'assistenza","messageTitle":"Errore Generale","messageKey":"generic.error","severity":"ERROR"}]}}

_{
"id": "-----BEGIN PGP MESSAGE-----\nVersion: BCPG v1.65\nhQEMA2HL/E0/MRALAQf/ceHy5qSqoCf9tiDDASo/q55t83SACkkvvs5Ghpfv02uG\nwYU55TPStCE/YipIDaudiADv8ImRN2R6821It2wsL2vsNqt1kQLXVPZbCiAwTZCY\nkDFxvnUooGNEpsrdejEzeNTq52c8jZlc9kGho+fP5LQ4Eg5FO1kIks0VKzgWQjaa\nGEhOUaE0/jitbOwOeQhk8HjGvCgC7RkcdfjNMRpGIvwdu9QF3L8Mn0L5WfRRC763\nqa8BWrB1SJotrPreTPXp6qASGLr22EigjHTYmswILm8p89TjxTKtemnFX2srfvfw\ncgsjNvVzT90jSOPcybQWUM+Vt88Mhhf4g8rhvsHDkdJLAYF57Cm2AYWInC+KUJTr\nYro13aZkkz9SO3iUOcumUhXnVC/fpqjNRDNuQsGI3wmMGoqXD0f4ZBi3lBok3dVk\n713r08c9Qk3l5Buq\n=jp/Z\n-----END PGP MESSAGE-----",
"fiscalCode": <codice_Fiscale_Utente>,
"expireYear": "2023",
"exprireMonth": "02",
"issuerAbiCode": "32875",
"brand": "MASTERCARD",
"holder": <denominazione_Utente>,
"type": "PP",
"channel": "32875"
}_

**Comment by mdesogus** [comment]
Buonasera, 

purtroppo non essendo in possesso dello stesso body utilizzato non possiamo replicare il test, potreste sottomettere nuovamente la chiamata al servizio?

grazie

**Comment by AndreaCaccin** [comment]
Buonasera, abbiamo provato ieri sera e l'esito è stato positivo
_class EnrollmentPaymentInstrumentResource {
    activationDate: 2020-12-02T21:18:34.757+01:00
}_

Chiudete voi la issue?

Grazie

**Comment by mdesogus** [comment]
Buongiorno,

a seguito di esito positivo procediamo con la chiusura della issue,

grazie
