### ISSUE TITLE
1.1.6 Status Strumento Pagamento H/M Banking

### ISSUE THREAD

**Issue by devitafederica** [pagopa/issuer_integration#113]
Buongiorno,
in merito all'API _1.1.6 Status Strumento Pagamento H/M Banking_, possiamo assumere che se l'id strumento passato in request corrisponde ad uno strumento che non è mai stato enrollato al programma, riceverò in response status "inactive" con corrispondenti date di attivazione e disattivazione a null?

Diversamente, invece se lo strumento è stato già oggetto di attivazione/disattivazione, riceverò stato inactive con le ultime date di attivazione e disattivazione registrate, corretto?

Grazie

**Comment by daniloMessinaSia** [comment]
Buongiorno,
gli scenari possibili in questo caso sono 2:
1. se lo strumento non è mai stato attivato/disattivato su CentroStella il servizio restituirà un 404 Not Found
2. se lo strumento era già stato attivato/disattivato su CentroStella il servizio restituirà lo status Active/Inactive con le relative date di attivazione/disattivazione

Buona giornata
