### ISSUE TITLE
IBAN cointestati

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#114]
Salve, 

come viene gestito lato pagoPA il controllo su un IBAN associato ad esempio ad un conto cointestato? 
Il controllo di titolarità lo effettuate sia sul CF prevalente che sul CF del cointestatario del conto? 

grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola
entrambi i CF (Titolare o Cotitolare) daranno un esito OK.
Saluti
