### ISSUE TITLE
Errore Impostazione/modifica IBAN da H/M Banking

### ISSUE THREAD

**Issue by mrossano** [pagopa/issuer_integration#115]
Ciao,
in ambiente di UAT riceviamo la seguente risposta:

{"returnMessages":{"ERROR":[{"message":"Errore generale contattare l'assistenza"
,"messageTitle":"Errore Generale","messageKey":"generic.error","severity":"ERROR"}]}}

Il servizio è PATCH bpd/hb/citizens/LVMRTI91H58H501J con i seguenti parametri:
{"accountHolderCF":"LVMRTI91H58H501J","accountH
olderName":"Rita","accountHolderSurname":"Levi Montalcini","payoffInstr":"IT68O3608503200210004434519","payoffInstrType":"IBAN"}

Timestamp: 01-12-2020 15:08:20

**Comment by mdesogus** [comment]
Buongiorno,

sarebbe possibile riprovare e fornirci riscontro?

grazie

**Comment by mrossano** [comment]
Riprovando otteniamo la pagina di servizio:
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by DenisaBraho** [comment]
Ciao,
l'errore non si dovrebbe ripresentare. 
Potreste verificare e fornirci un riscontro?
Saluti

**Comment by DenisaBraho** [comment]
Ciao, 
il servizio attualmente risulta funzionante e non riscontriamo errori. Procediamo con la chiusura della issue. Qualora si ripresentasse un errore, vi chiediamo di procedere con l'apertura di una nuova issue. 
Grazie
Saluti
