### ISSUE TITLE
Errore Enroll Carta di Debito in UAT - PAN cifrato

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#116]
Sottomettendo la richiesta di Enroll della carta con PAN cifrato in ambiente di UAT stiamo riscontrando l'errore **400 ErrorPM**.

Il PAN Utilizzato è **1234567890123456**
La chiave utilizzata è quella da voi indicata per l'ambiente di Test: "**bpd_pm_test_pub.pgp**"

La cifratura produce il seguente testo: 
_-----BEGIN PGP MESSAGE-----\nVersion: BCPG C# v\n\nhQEMA+NENQPn0iNJAQf/fEi9GUKX1oHq2JWRtoleh+zdMhJ/PRaFr78O3ldMO8Un\n5QIXuGa0VzkYyD8owSVtN1lB+Obs/2f7rfwt4yDF4AFypuLq98bUTQZLG/Y3togV\nQN7lGXdWARg5b0oQJH9B26NXBr4jUw8qQd66SU7We8fugwQfZPKZULsCacdtcS+H\ndjvQlilfGnZoUgpvOl/PYiMK/EzPyfOUiEHR/do7UCTUcRBofhepuOdjcYOvUVjN\nfsIIHKFeEIMtt6s0Q/sI0i3h6KHRlSHn9WXPg++kPNqkp5ey9NAYvi7tufslt319\nTzLuT+mbR9ep7uOj88RKBNj9ICbcduDiXnwuObIvpdJDAb3Dndr7iXYevE4HDmel\ndDbg18zxLbj10y1PzJ5BbVwHhqRdPtkAYnxYb7pHLv6p9uBJ+ORr8cHIgYEJGBjF\nOYF2/w==\n=Y9ET\n-----END PGP MESSAGE-----\n_

La richiesta è la seguente:
PUT - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card
REQUEST:
{
    "id": "-----BEGIN PGP MESSAGE-----\nVersion: BCPG C# v\n\nhQEMA+NENQPn0iNJAQf/fEi9GUKX1oHq2JWRtoleh+zdMhJ/PRaFr78O3ldMO8Un\n5QIXuGa0VzkYyD8owSVtN1lB+Obs/2f7rfwt4yDF4AFypuLq98bUTQZLG/Y3togV\nQN7lGXdWARg5b0oQJH9B26NXBr4jUw8qQd66SU7We8fugwQfZPKZULsCacdtcS+H\ndjvQlilfGnZoUgpvOl/PYiMK/EzPyfOUiEHR/do7UCTUcRBofhepuOdjcYOvUVjN\nfsIIHKFeEIMtt6s0Q/sI0i3h6KHRlSHn9WXPg++kPNqkp5ey9NAYvi7tufslt319\nTzLuT+mbR9ep7uOj88RKBNj9ICbcduDiXnwuObIvpdJDAb3Dndr7iXYevE4HDmel\ndDbg18zxLbj10y1PzJ5BbVwHhqRdPtkAYnxYb7pHLv6p9uBJ+ORr8cHIgYEJGBjF\nOYF2/w==\n=Y9ET\n-----END PGP MESSAGE-----\n",
    "fiscalCode": "AAABBB11X11X111A",
    "expireYear": 2025,
    "exprireMonth": 12,
    "issuerAbiCode": "36003",
    "brand": "Mastercard",
    "holder": "Alberto Rossi",
    "type": "DEB",
    "channel": "36003"
}

Sapreste dirci cosa c'è che non va?
Sapreste darci maggiori dettagli in merito a come effettuare la cifratura?

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo notato che il campo "Brand" nel body dovrebbe essere valorizzato con "MASTERCARD" oppure gli altri possibili valori indicati nell'IA (campo brand: enum in upper case).
Potreste verificare e fornirci un feedback in merito?
Grazie

**Comment by albertosangalliflowe** [comment]
Confermo con con "brand": "MASTERCARD" (tutto in CAPITAL case) funziona anche l'enroll con cifratura.
Grazie
