### ISSUE TITLE
Stato utente - 502

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#117]
salve 

riceviamo questo errore

[INFO]    [02/12/2020 09.48.19 496] [pool-4-thread-85] [SCA - SESSIONID [9584375878BDAF69EB5FBEA00EF6191E] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] -
AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - enrollmentCitizenStatus - HTTP URL[https://test.cstar
.pagopa.it/bpd/hb/citizens/PLARST80A01H501Z]]
[INFO]    [02/12/2020 09.48.19 496] [pool-4-thread-85] [SCA - SESSIONID [9584375878BDAF69EB5FBEA00EF6191E] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] -
AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET - REQUEST HEADER -
[Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: c907049d-1a38-4292-89eb-8c2315a965d8]]
[INFO]    [02/12/2020 09.48.19 496] [pool-4-thread-85] [SCA - SESSIONID [9584375878BDAF69EB5FBEA00EF6191E] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] -
AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET - REQUEST PAYLOAD
**- https://test.cstar.pagopa.it/bpd/hb/citizens/PLARST80A01H501Z]**
[INFO]    [02/12/2020 09.48.19 831] [pool-4-thread-85] [SCA - SESSIONID [9584375878BDAF69EB5FBEA00EF6191E] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] -
AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET RESPONSE - HTTP ST
ATUS[502]]
[INFO]    [02/12/2020 09.48.19 831] [pool-4-thread-85] [SCA - SESSIONID [9584375878BDAF69EB5FBEA00EF6191E] -  COMMAND SCA [Async - v1/bancoposta/statoUtenteCashback] -
AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatus-GET RESPONSE - HTTP ENTITY[<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
]]

**Comment by DenisaBraho** [comment]
Ciao @NicolaLamberti 
l'errore è dovuto ad una fase di test in corso nella mattinata. Potreste riprovare adesso?
In attesa di un riscontro

**Comment by DenisaBraho** [comment]
Ciao, 
il servizio attualmente risulta funzionante e non riscontriamo errori. Procediamo con la chiusura della issue. Qualora si ripresentasse un errore, vi chiediamo di procedere con l'apertura di una nuova issue. 
Grazie
Saluti
