### ISSUE TITLE
Modifica Iban ko - issue #99

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#119]
Salve

è possibile "pulire" in ambiente di UAT/collaudo le info dell'utenza segnalata nella issue #99 DDCDBP66A01L736X .Per noi l'iban è dell'utente che usiamo quindi dobbiamo ricevere un ok, e non un KO

Nicola

**Comment by lucasomarugasia** [comment]
ciao Nicola, 
vedo che ancora è apertea la issue #99. 


Abbiamo approfondito il punto e riteniamo che ci sia un disallineamento nel servizio di Poste che PagoPA chiama per verificare la validità dell'associazione. 
Lato nostro non possiamo "pulire" l'ambiente per fare in modo che l'esito del test dia ok. 


Tecnicamente la cosa più veloce sarebbe verificare in ambiente di produzione, dove ci aspetteremmo un ok come risultato.


Lascio in ogni caso la parola a Mario che segue il servizio di validazione IBAN, per eventualmente darti un feedback differente o più approfondito. 


Lato centroStella provvediamo a chiudere la segnalazione perchè motivata e non ci sono defect sul servizio. 


Resto a disposizione per eventuali chiarimenti. 


Grazie e ciao, 
Luca
