### ISSUE TITLE
Errore 404 recupero graduatoria

### ISSUE THREAD

**Issue by W4IR** [pagopa/issuer_integration#120]
Salve

Stiamo ricevendo 404 chiamando il vostro servizio in ambiente in PROD.
Mentre invece in UAT riceviamo 401 nonostante la chiave sia corretta (gli altri servizi funzionano correttamente)

**Esempio servizio in 200 con la stessa chiave:**
`2020-12-03 15:15:16,733\| INFO\|95.74.35.170\|empty-empty\|payment-service\|getCashbackInfo\|app-ios-it\|BRPGNE61B18F132V\|\|asw9wRDypvHCLrpy6OiStQ\|25521ec7d5392669\|25521ec7d5392669\|\|[i.i.d.a.r.i.LoggingClientHttpRequestInterceptor:?]\|_REST_\|OK\|_\|_RESPONSE_BODY={"transactionNumber":0,"totalCashback":0}_\|_**CODE=200**_\|_METHOD=GET_\|_URL=https://test.cstar.pagopa.it/bpd/hb/winning-transactions/total-cashback?fiscalCode=BRPGNE61B18F132V&awardPeriodId=1_\|_STATUS_TEXT=OK_\|_HEADERS_REQUEST=Accept: text/plain, application/json, application/*+json, */* x-request-id: f877d1a9-d579-4c53-9f6c-a68c9f948ce2 **Ocp-Apim-Subscription-Key: 805d8c5266374b00a3bf1a49c409b128** Content-Type: application/json `

**401 UAT:**
`2020-12-03 12:56:26,476|ERROR|95.237.183.209|empty-empty|payment-service|getCashbackInfo|app-ios-it|PPACLD80R20H501A||Dzj9dFsjkwJ2FAR-te9m_A|f1574c56b5b7672a|f1574c56b5b7672a||[i.i.d.a.r.i.LoggingClientHttpRequestInterceptor:?]|_REST_|KO|_|_RESPONSE_BODY={ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }_|_**CODE=401**_|_METHOD=GET_|_URL=https://test.cstar.pagopa.it/bpd/hb/citizen/PPACLD80R20H501A/ranking?awardPeriodId=1_|_STATUS_TEXT=Unauthorized_|_HEADERS_REQUEST=Accept: text/plain, application/json, application/*+json, */* x-request-id: 8a762d83-c5e4-4817-b8b7-833f518a5cf0 **Ocp-Apim-Subscription-Key: 805d8c5266374b00a3bf1a49c409b128** Content-Type: application/json`

**404 PROD:**
`2020-12-03 16:07:23,278|ERROR|93.41.121.41|empty-empty|payment-service|getCashbackInfo|app-android-it|CNVNGL84L29F152C||XAmGYwpVGcv7JzqkA4d9Gg|48acd567c24eb36a|48acd567c24eb36a||[i.i.d.a.r.i.LoggingClientHttpRequestInterceptor:?]|_REST_|KO|_|_**CODE=404**_|_METHOD=GET_|_URL=https://prod.cstar.pagopa.it/bpd/hb/citizen/CNVNGL84L29F152C/ranking?awardPeriodId=0_|_STATUS_TEXT=Not Found_`

Potete verificare?

Grazie

**Comment by mdesogus** [comment]
Buongiorno,

potete riprovare inserendo citizens anzichè citizen nell'url della richiesta?

grazie

**Comment by mdesogus** [comment]
Buongiorno,

da mancata comunicazione consideriamo l'anomalia rientrata.
Qualora il problema persista/ si ripresentasse vi preghiamo di riaprire la presente.

Grazie
