### ISSUE TITLE
TokenPanList - Enrollment strumento di pagamento card - chiarimenti flow

### ISSUE THREAD

**Issue by ChristianRoldo** [pagopa/issuer_integration#121]
Ciao 
la lista dei token collegati ad un PAN è annegata nel metodo di enrollment del PAN.
Come ci si comporta quando:
- il cliente tokenizza la carta post enrollment ?
- i token vengono rinnovati e quindi ci sono nuovi token associati ?

Va fatta una delete ed una nuova put dello strumento di pagamento ?
E' prevista una PATCH o un metodo di aggiornamento dei soli token dato il pan ?

Non si possono a quanto detto eseguire chiamate in modalità  batch / utente offline . 
Va quindi in qualche modo costretto il cliente a rifare questa operazione quando tokenizza una carta post enrollment o quando 
vengono associati nuovi token ? Il processo lato utente sarebbe al quanto macchinoso

Christian

**Comment by mdesogus** [comment]
Buongiorno,

stiamo analizzando tutto il processo che prevede l'enrollment delle carte tokenizzate,
come indicato nel versionamento dell'Interface agreement le nuove integrazioni fanno riferimento alla fase post go-live
(pertanto le interfacce inerenti a disattivazione/aggiornamento prevediamo di pubblicare nelle prossime settimane in quanto ancora in fase di analisi funzionale).

grazie
