### ISSUE TITLE
Esiti metodi Issuer

### ISSUE THREAD

**Issue by BrignoliSIA** [pagopa/issuer_integration#122]
Ciao,

su altro ticket abbiamo ricevuto la seguente risposta:

Buongiorno,
gli scenari possibili in questo caso sono 2:
1.	se lo strumento non è mai stato attivato/disattivato su CentroStella il servizio restituirà un 404 Not Found 
2.	se lo strumento era già stato attivato/disattivato su CentroStella il servizio restituirà lo status Active/Inactive con le relative date di attivazione/disattivazione 

Abbiamo la necessità di sapere se:
- l'esito 404 è relativa solo alla situazione sopra riportata o se viene utilizzata anche per altre casistiche; questo perché ci servirebbe identificare in maniera univoca tale casistica; è possibile?
- dobbiamo avere l'elenco dei possibili esiti con relativa descrizione che potete dare in response (che siano essi http error code o errori applicativi).

Grazie mille
Vittorio

**Comment by mdesogus** [comment]
Buongiorno,

1. gli altri possibili errori, come scritto in documentazione, sono:
  -  409 (se si sta tentando di recuperare lo stato di uno strumento attivo tramite un utente diverso da quello in "possesso" dello 
             strumento su BPD) 
  - 500 nel caso di altri errori

2. la lista dei possibili codici di errore restituito con annessa descrizione è presente nel documento di Interface Agreement

restiamo a disposizione per eventuali chiarimenti, nel caso vi preghiamo di riaprire il presente ticket.
Grazie
