### ISSUE TITLE
produzione - errori 500 su bpd/hb/payment-instruments/card PUT e bpd/hb/citizens PATCH

### ISSUE THREAD

**Issue by luca-delgiudice-dev** [pagopa/issuer_integration#125]
Ciao,

In ambiente di produzione stiamo riscontrando errore 500 su alcune chiamate verso https://prod.cstar.pagopa.it/bpd/hb/citizens metodo PATCH e https://prod.cstar.pagopa.it/bpd/hb/payment-instruments/card metodo PUT.

conteggio errori metodo PATCH bpd/hb/citizens:
2020-12-07 13:00-14:00 -> 149 casi
2020-12-07 14:00-14:40 -> 117 casi

conteggio errori metodo PUT bpd/hb/payment-instruments/card:
2020-12-07 11:00-12:00 -> 1 caso
2020-12-07 12:00-13:00 -> 7 casi
2020-12-07 13:00-14:00 -> 1 caso
2020-12-07 14:00-14:45 -> 2 caso

Riporto di seguito i log di 2 casi, potete verificare?

grazie

https://prod.cstar.pagopa.it/bpd/hb/citizens metodo PATCH

```
2020-12-07 14:08:15,744
updatePaymentMethodUsingPATCH, fs:******* , citizenPatchDTO:class CitizenPatchDTO {
    accountHolderCF: *******
    accountHolderName: *******
    accountHolderSurname: *******
    payoffInstr: ***0015
    payoffInstrType: IBAN
}

2020-12-07 14:08:20,968|ERROR|payx-microservice-security|enrollYAPPagoPA|5fce293f59806|67824055-b5ea-49eb-92a6-8a584636af15|7d1fa54204fdc935|7d1fa54204fdc935|||||HbCitizenApiException - status 500 - response {	"errcode":500,	"errmsg":"Internal Server Error"}
```

---

https://prod.cstar.pagopa.it/bpd/hb/payment-instruments/card metodo PUT

```
2020-12-07 14:04:36,334
PaymentInstrumentDto {
    id: -----BEGIN PGP MESSAGE-----
    Version: BCPG v1.65
    
    hQEMA2HL/E0/MRALAQf9ErRrgTR3Mq6ODzggRzMbIag+2GNGEUtnZNdGVqLm7c+N
    IympjDA6kv0oS1KhyKv5JFHV10CLCqavMDJGyVbMZoqED85FWWum/nt2CdLvidRR
    wyTXErICpjzR+/ku7zwji77S8HQFCqwu2dr3hklVsECKxNBCJwVFf4yb+q0R6cAo
    GTQIu4b1z2MaDC4Qv2ZG0Ehmq+IpTqGYZXJ/pfAEC+U5hDLxNF9XnG5QhXX3suTD
    WjVtmkpn5xM2LCxnzQtFrE2Szs9/2IiZIaDLZ/dW3+hVZhRZvGjIe3Q5xQVy1Nzl
    AsqvwJXyFi2R6tBjbw4N85+kNbS88zlOar5bbYOP9NJLAQYiQ0oehWs/Uie71fPG
    jAic/Wk46b/v7GdSEwqW7efbKmVPQnNU2Cl2p6R7A7xszjqSL5nt3wy+1zW4RK2D
    fy1MqOBxfmxfAVKm
    =+S0R
    -----END PGP MESSAGE-----
    
    fiscalCode: *******
    expireYear: ****
    expireMonth: **
    exprireMonth: **
    issuerAbiCode: 32875
    brand: MASTERCARD
    holder: ***
    type: PP
    channel: 32875
}

Payment Instruments ApiException - status 500 - response {"returnMessages":{"ERROR":[{"message":"Errore generale contattare l'assistenza","messageTitle":"Errore Generale","messageKey":"generic.error","severity":"ERROR"}]}}
```

**Comment by lucasomarugasia** [comment]
Buonasera, sul secondo caso (https://prod.cstar.pagopa.it/bpd/hb/payment-instruments/card metodo PUT) riscontriamo dai log che si sta inserendo un HPAN già registrato. Stiamo verificando le patch su inserimento IBAN

**Comment by DenisaBraho** [comment]
Ciao,
negli ultimi giorni state ricevendo la stessa numerica di errori?  
Grazie

**Comment by DenisaBraho** [comment]
Ciao  @luca-delgiudice-dev ci sono novità in merito alla richiesta?
Qualora l'errore non dovesse piu persistere, vi chiediamo di notificarcelo in modo da procedere con la chiusura issue
Grazie

**Comment by DenisaBraho** [comment]
Ciao,
procediamo con la chiusura issue e vi invitiamo a procedere con la sua riapertura se l'anomalia persiste/si ripresenta. 
saluti
