### ISSUE TITLE
Errore in DELETE /bpd/hb/citizens

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#126]
Buonasera, in ambiente SIT sta andando in errore la chiamata di cancellazione utente dall'iniziativa, DELETE /bpd/hb/citizens

REQUEST 2020-12-07 17:54:25,980
codice fiscale: TTTFNC85S13A222A

RESPONSE 2020-12-07 17:54:26,107
{ "statusCode": 500, "message": "Internal server error", "activityId": "783a91bf-18b0-4b8e-856c-0c595a753f5a" }

Potete verificare?
Grazie

**Comment by DenisaBraho** [comment]
Ciao,
il servizio in SIT è funzionante. Tuttavia, dall'esempio abbiamo notato che non è stato indicato il "channel" necessario nel body della chiamata. Qualora tale parametro non fosse stato inserito nella chiamata d'esempio, vi chiediamo di riprovare inserendo i parametri necessari della chiamata.
Grazie
Saluti
