### ISSUE TITLE
Errore in bpd/hb/award-periods

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#127]
Buonasera, in ambiente di produzione stiamo riscontrando errori in fase di recupero del dettaglio periodi, bpd/hb/award-periods, per esito 500 - Internal Server Error
REQUEST 2020-12-08 17:59:39,471

RESPONSE 2020-12-08 17:59:44,646
{	"errcode":500,	"errmsg":"Internal Server Error"}

Potete verificare?
Grazie

**Comment by lucasomarugasia** [comment]
Buongiorno, il sistema non ha risposto per picco di traffico nell'intorno delle 17.30. Il problema è rientrato
