### ISSUE TITLE
PROD - bpd/hb/citizens PATCH

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#128]
Buonasera, in ambiente di produzione stiamo riscontrando errore 500 su alcune chiamate verso https://prod.cstar.pagopa.it/bpd/hb/citizens metodo PATCH 
Servizio di PATCH
REQUEST 2020-12-08 19:43:00,034
{
    accountHolderCF: {codiceFiscaleUtente}
    accountHolderName: Thomas
    accountHolderSurname: {cognomeUtente}
    payoffInstr: IT92K3287501600N20241630015
    payoffInstrType: IBAN
}
RESPONSE 2020-12-08 19:43:05,267
{	"errcode":500,	"errmsg":"Internal Server Error"}

Potete verificare?
Grazie

**Comment by daniloMessinaSia** [comment]
Buongiorno,
dai controlli effettuati l'IBAN risulta correttamente caricato sui nostri sistemi.
