### ISSUE TITLE
PROD bpd/hb/payment-instruments/card metodo PUT

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#129]
Buonasera, in ambiente di produzione stiamo riscontrando errori  di http status 404 in invocazione del servizio di registrazione carta bpd/hb/payment-instruments/card in PUT
REQUEST 2020-12-08 20:41:32,600
{
    id: -----BEGIN PGP MESSAGE-----
    Version: BCPG v1.65
    
    hQEMA2HL/E0/MRALAQf9GIAKWg0HftHQVVpZQvfZzoZW984lQnLW0HSjmZNRupmF
    wXhfS8KTRjEFdpouqAaX743NYH2OMXl1GksOG72a59Y0sQ96lU43GkuxUX+jPH9W
    xFcyl7wiMChGq7ZNe2lNYglEBviHRkU/bM5dIo8xnNFHXWbzUNaZGLvX4psUGLdW
    fo8RzcBFliw/TlBwhsYWQLwwY87c74M72alwpuKNvoXJGspclSxgznezUXJWMrR/
    u+kyFBihSlyCvqKTLCHGjIxYfG7I3AkZ+ywzHdj+G5+csX+NNIu7s4cR9GXSYGJe
    L08GGqGCbnMjKWsIMfeSZzhvpc+qIanjb3GtYQAOzdJLAZtnN2zYEpIwWVWqowrr
    j0hyMG7mI8TgPwfaxRlZmQx6iBBnscP9md8DrtZUb/5fZUhLdp2byyKRBwzNYeBH
    JX3bkmY1PpMSQy75
    =8wYu
    -----END PGP MESSAGE-----
    
    fiscalCode: {codiceFiscaleUtente}
    expireYear: 2024
    expireMonth: 06
    exprireMonth: 06
    issuerAbiCode: 32875
    brand: MASTERCARD
    holder: {anagraficaTitolare}
    type: PP
    channel: 32875
}
RESPONSE 2020-12-08 20:41:32,922

Potete verificare?
Grazie

**Comment by DenisaBraho** [comment]
Ciao,
dalla chiamata d'esempio vediamo che il parametro exprireMonth è stato inserito due volte. Potreste riprovare la chiamata inserendo i dati corretti?
Grazie

**Comment by AndreaCaccin** [comment]
non è settato due volte: uno è il parametro as-is exprireMonth, uno è il parametro come dovrebbe essere, expireMonth, in previsione di prossime vostre sistemazioni. Attualmente abbiamo in situazione di errore segnalata dalla issue (404 - Not Found) il 20% delle chiamate. Potete verificare?
Grazie

**Comment by AndreaCaccin** [comment]
chiudo questa issue perchè la situazione anomala si riscontra solo sporadicamente
