### ISSUE TITLE
Errore in registrazione iban

### ISSUE THREAD

**Issue by Pierwide** [pagopa/issuer_integration#13]
Ciao,
quando proviamo ad invocare il servizio di registrazione iban (/bpd/hb/citizens/{id}) abbiamo l'errore di : "Il campo payoffinstr non è valido".
Abbiamo effettuato delle prove sostituendo una lettera del nostro iban con un numero ed il servizio ha dato ok.
Riporto l'esempio;
- iban ko: ITXXXXXXXXXXXXXNXXXXXXXXXXX
- iban ok: ITXXXXXXXXXXXXX0XXXXXXXXXXX
sembra che ci sia un errore nel controllo formale.

Grazie
Pier

**Comment by daniloMessinaSia** [comment]
Buongiorno,
è possibile riprovare?
restiamo in attesa di feedback

Grazie
