### ISSUE TITLE
PagoBancomat - Brand in /bpd/hb/payment-instruments/card

### ISSUE THREAD

**Issue by Carrettoni** [pagopa/issuer_integration#130]
Vorremmo sapere come valorizzare il brand quando viene fatto enrolment di un PagoBancomat (PAN Nazionale)

Dalle specifiche 
type of circuit String(VISA,MASTERCARD, MAESTRO,VISA_ELECTRON, AMEX, OTHER)

sembrerebbe OTHER, mi chiedo se questo crei problemi di visualizzazione in app IO dove il PagoBancomat viene visualizzato con il logo relativo e la Banca

Grazie
Fabio

**Comment by DenisaBraho** [comment]
Ciao Fabio,
confermiamo che il tipo circuito per bancomat rientra tra "OTHER". Tuttavia, da quanto emerso da verifiche congiunte con gli altri gruppi di lavoro, questo non causa problemi nella visualizzazione in APP IO, in quanto al momento, per i bancomat, viene applicata una logica che è indipendente da quell'attributo. Da APP IO gli utenti vedono il logo corretto. 

Saluti
Denisa

**Comment by Carrettoni** [comment]
Il comportamento descritto non è quello reale, da verfiche su APP IO non si vede il logo corretto ma un logo generico

Di seguito il msg di sottoscrizione con brand OTHER se serve posso allegare videata

{"id":"-----BEGIN PGP MESSAGE-----\nVersion: BCPG v1.67\n\nhQEMA6MJbtF2elYYAQf9Fnd5B5xn+hmvfYyY7S61nYFbplqmAnNvPqrXGM2KsF5c\nWsnJOLwWk2ZkP/XUsp9n1pjXQhoBSQIY369aFRMezamzOhKxx13ckKqBlJGZY/ZB\nIDBmy6xFSh/daO82IX0sI4wpMOdt+j0l8w8DJzj/0plUYUZDAAyPiCmbaRXmGgkE\nTAiBm+MMfxEPsw91H5iC/VBqVvl8Xswq5ORTSEdqmMeKVkqyEOSlMZTVvuOdNutV\nh8ZpgYjzDmhGnbSpr+rEeSejgz/VGxO9KDDs+zXX2RSSxcppUyocwidrhF5R9nJC\n3dSiAm726oA14jyfE60NJKtQzp9KvrHQP6vNlueC6dI+AYLfkoPkxsaWSC9/DaD4\n31e1Uj5JvcbbCv5NoVfg6ZBA1aasI/9ZNfqzBZvOjy23+9Fg2bfBbJrdvfA3oTw=\n=D1FR\n-----END PGP MESSAGE-----\n","fiscalCode":"xxxxxxx","expireYear":"2022","exprireMonth":"12","issuerAbiCode":"03268","brand":"OTHER","holder":"xxxxxxx","type":"DEB","channel":"03268"}
