### ISSUE TITLE
Carta attiva non visibile da app IO

### ISSUE THREAD

**Issue by Carrettoni** [pagopa/issuer_integration#131]
Il metodo bpd/hb/payment-instruments/card ci restituisce carta attiva ma da app IO non è più visibile (lo era in precedenza).

C’è un limite di carte visibili? Si è creata inconsistenza dovuta alle prove di attiva / disattiva?

{"hpan":"987a6f0af49a905a1b2805347d0ac4751b04c20fa748f0bcf54ccb8fa4e3bb30","fiscalCode":" xxx","activationDate":"2020-12-08T21:32:53.567+01:00","Status":"ACTIVE"}

**Comment by Carrettoni** [comment]
Aggiungo altra segnalazione di cliente sempre in produzione situazione disallineata tra risposta del metodo e visibilità in app IO

{"hpan":"d2f74634ac9c2524c0e4f8dce5cc81d0a63360a63d7d780db055eb15a9c26c40","fiscalCode":"xxx","activationDate":"2020-12-11T00:01:51.902+01:00","Status":"ACTIVE"}

Grazie
Fabio

**Comment by DenisaBraho** [comment]
Ciao,
è stato ffettuato un  intervento per sanare l'anomalia segnalata. Per vedere correttamente lo strumento di pagamento segnalato, Il cittadino deve, una volta fatto accesso alla app IO, forzare l’aggiornamento con il tastino “aggiorna”.
