### ISSUE TITLE
Enroll carta tramite issuer

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#132]
Buonasera,
ho visto che ad oggi in app IO è necessario che l'utente dopo aver enrollato la carta deve anche abilitarla.
Quando invece l'utente completa l'enroll della carta tramite issuer terzi è implicita anche l'attivazione?

Inoltre, in caso di riemissione carta (per furto, danneggiamento, ecc), PagoPA ha problemi a ricevere l'enroll di una carta con stesso PAN?

Grazie

**Comment by DenisaBraho** [comment]
Ciao,
l'enrollment della carta su BPD da H/M Banking, comporta la sua l'attivazione; ossia la carta è attiva su BPD nel momento in cui **viene chiamato il servizio esposto da BPD di enrollment carta.**
No, in caso di riemissione, non si prevedono problematiche dovute all'inserimento di una carta con lo stesso PAN.
Saluti
