### ISSUE TITLE
SuperCashback

### ISSUE THREAD

**Issue by GabrieleCurreli** [pagopa/issuer_integration#133]
Ciao, 

facendo alcuni test riguardanti il Supecashback, volevo chiedervi alcune conferme: 

Il 01.01.2021 avrà inizio il primo periodo con la funzionalità, il servizio cosa risponderà per i campi maxTransactionNumber e minTransactionNumber? 

1) Per rientrare in classifica sono necessarie 50 transazioni. Quindi immagino che un primo periodo (quando nenanche un cittadino avrà raggiunto le 50 transazioni) per ogni interrogazione del servizio avremo questi due campi a "0", corretto?
Dopodichè alcuni cittadini supereranno le 50 transazioni e rientreranno in classifica. A questo punto avremo max transaction number >50, ma finchè 100.000 cittadini non saranno rientrati in classifica mintransaction number sarà uguale a 0. è corretto? dai test sembrerebbe così: 
]
[
  {
    "totalParticipants": 100014,
    "ranking": 100003,
    "maxTransactionNumber": 145,
    "minTransactionNumber": 0,
    "transactionNumber": 11,
    "awardPeriodId": 1
  }
]

2) Per i cittadini che non hanno ancora effettuato transazioni il ranking è sembre uguale a totalParticipants +1?

[
  {
    "totalParticipants": 100014,
    "ranking": 100015,
    "maxTransactionNumber": 145,
    "minTransactionNumber": 0,
    "transactionNumber": 0,
    "awardPeriodId": 1
  }
]

Grazie

**Comment by DenisaBraho** [comment]
Ciao,
rispondiamo per punti:
1. Quando non è presente alcuna transazione su BPD, il ranking non restituirà dei valori. Appena saranno presenti delle transazioni per l'award period di riferimento, a prescindere dal raggiungimento delle 50 transazioni per singolo cittadino, verranno comunque calcolati i parametri del Ranking con i dati _"reali"_ della graduatoria ossia il minTransaction verrà valorizzato con il numero minimo delle trx fatte da un cittadino e maxTransactionNumber con il numero massimo delle transazioni effettuate da un cittadino. Una volta superato il numero di 100.000 cittadini che hanno effettuato delle transazioni valide, i parametri della graduatoria saranno valorizzati  come segue:
-  il minTransactionNumber conterrà il numero minimo di transazioni che l'utente dovrà fare per ottenere il SuperCashback
- maxTransactionNumber quello delle transazioni effettuate dal primo utente in classifica per il Supercashback. 
2. si , corretto

A disposizione
