### ISSUE TITLE
PROD - Abilitazione chiamate

### ISSUE THREAD

**Issue by mrossano** [pagopa/issuer_integration#134]
Ciao,
dalle prime chiamate in produzione con chiavi di autenticazione e certificati target, riceviamo il seguente messaggio di errore:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>

La chiamata in esame è una di prova all'indirizzo PUT https://prod.cstar.pagopa.it/bpd/hb/citizens/RSS che dovrebbe fallire poiché il codice fiscale non risulta valido.

Ci saremmo aspettati però un errore applicativo. Come mai riceviamo in risposta una pagina HTML di servizio?

**Comment by DenisaBraho** [comment]
Ciao, 
ci potreste indicare se possibile l'header della chiamata?
Grazie

**Comment by DenisaBraho** [comment]
Ciao @mrossano ci sono novità circa la nostra richiesta di cui sopra?
Grazie

**Comment by mrossano** [comment]
Chiudo la segnalazione poiché applicativamente non riscontriamo errori.
