### ISSUE TITLE
Retrieve ranking vuoto

### ISSUE THREAD

**Issue by luca-delgiudice-dev** [pagopa/issuer_integration#135]
Ciao,

in ambiente di produzione riceviamo sempre un body vuoto in risposta al servizio GET /bpd/hb/citizens/{id}/ranking.
E' corretto?
Come awardPeriodId inviamo 1.

metodo GET
/bpd/hb/citizens/{id}/ranking?awardPeriodId=1

grazie,
Luca

**Comment by DenisaBraho** [comment]
Ciao,
essendo appena partito il servizio e non avendo i dati necessari per determinare il ranking dei cittadini, la risposta della chiamata è quella attesa.
Saluti
