### ISSUE TITLE
Processo aggiornamento T&C

### ISSUE THREAD

**Issue by ismyuser** [pagopa/issuer_integration#136]
I T&C vengono recuperati online e la loro accettazione viene verificata online con le API messe a disposizione. 
Qual è il processo previsto in caso di aggiornamento del testo dei T&C per un utente che ha già sottoscritto il servizio BPD ed accettato i T&C in passato?
Non abbiamo rilevato dalle API esposte nessun campo che possa farci capire che l'utente debba procedere con una nuova accettazione degli stessi e come gli verrà comunicato l'aggiornamento: 
- non va previsto nulla? 
- i T&C non verranno mai modificati? 
- chi gli notifica l'eventuale variazione?
- l'utente non dovrà procedere ad una nuova accettazione?

Grazie

**Comment by DenisaBraho** [comment]
Ciao,
vista la natura e la durata del servizio non è previsto un aggiornamento dei T&C e di conseguenza non è stata previsto attualmente un processo di notifica variazione T&C.
Saluti

**Comment by ismyuser** [comment]
Scusa ma non concordo con la motivazione. Il cashback non è solo quello di Natale. I T&C valgono anche per l'altro cashback o sbaglio?

**Comment by ismyuser** [comment]
Potete riaprire la issue per favore?

**Comment by ismyuser** [comment]
Il fatto che il regolamento sia a livello dinutente era chiaro. 
State dicendo quindi che non ci sarà mai esigenza di cambiare o aggiornare il contenuto dei Termini e Condizioni?
Assumiamo che nel caso si occupi PagoPa o il centro stella a comunicare agli utenti registrati il nuovo regolamento ad esempio via mail?
