### ISSUE TITLE
Logo Maestro non visibile su AppIO

### ISSUE THREAD

**Issue by luca1oo** [pagopa/issuer_integration#137]
Ciao, tra i loghi esposti in fase di iscrizione carta su AppIO, non è rappresentato il logo Maestro. Questo crea confusione ai clienti che pensano che non si possa aggiungere una carta con circuito Maestro, quando in realtà è possibile.
Grazie

**Comment by DenisaBraho** [comment]
Ciao, 
a seguito degli approfondimenti effettuati con gli altri gruppi di lavoro, ci è stato comunicato che nella prossima versione non ci sono più i loghi, ma soltanto un link che rimanda alla pagina https://io.italia.it/metodi-pagamento. La nuova versione IO sarà disponibile nei primi giorni di questa settimana.
Saluti
