### ISSUE TITLE
Integrazione lato Issuing

### ISSUE THREAD

**Issue by BrignoliSIA** [pagopa/issuer_integration#138]
Ciao,

stiamo integrando i servizi lato issuing e abbiamo un problema nel gestire la response per via del formato della data che ci viene restituito
{
               "fiscalCode": "TSTPGP91E25F704H",
               "timestampTC": "2020-12-14T11:26:13.5+01:00",
               "enabled": true
}
org.codehaus.jackson.map.JsonMappingException: Can not construct instance of java.util.Date from String value '2020-12-14T11:26:13.5+01:00': not a valid representation (error: Can not parse date "2020-12-14T11:26:13.5+01:00": not compatible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd"))

In teoria il formato corretto sarebbe con le tre cifre per i millesimi di secondo (2020-12-14T11:26:13.500+01:00), mentre quello che riceviamo da PagoPa ha solo i decimi.

Mi confermate che è corretto che utilizziate il formato solo ai decimi e non ai millesimi?

Grazie mille
Vittorio

**Comment by mdesogus** [comment]
Ciao,

da verifiche effettuate confermiamo che il campo utilizzato è quello espresso in millesimi, a tale proposito abbiamo più volte replicato la fase di censimento di nuovi utenti al fine di replicare la chiamata in allegato ed il valore del campo timestampTC è sempre quello atteso (es. 2020-12-14T19:15:40.**293**+01:00).
Tuttavia confermiamo che utilizzando il fiscalcode presente in allegato (VTSTPGP91E25F704H) il risultato è come indicatoci, una prima ipotesi è che la chiamata è stata recepita nel millisecondo "00" e perciò viene troncata.

Potreste cortesemente riprovare a cominciare dal processo di enrollment del cittadino e fornirci riscontro?

grazie

**Comment by BrignoliSIA** [comment]
Abbiamo provato e ha funzionato correttamente;  a questo punto presumo che l’errore ci sia anche in caso di 2 cifre decimali, e se fosse così i casi di errore si attesterebbero al 10% del totale.
Non è possibile fare in modo che anche quando '0' ci venga restituito?

**Comment by BrignoliSIA** [comment]
Ciao,

nel frattempo abbiamo sistemato noi per poter gestire anche la restituzione del timestamp troncato.

Ora riceviamo errore nella chiamata di enrollment iban, in questo caso la risposta è un errore “400 – Bad request” quindi immagino non sia un errore di comunicazione ma proprio PagoPa che ci dà picche.
Controllando però la richiesta mi sembra conforme alle specifiche che ci avete inviato (capitolo 1.1.3.2), l’unico punto aperto è il valore del canale che al momento è impostato come “TBD” non sapendo quale valore è stato assegnato a BanomatPay.
Ci potete segnalare con che valore dobbiamo valorizzare il campo CANALE e perché andiamo in 400?

Grazie - riporto sotto di seguito request e response:
INFO 2020-12-15 11:54:56,849  AbstractRestClient(?: ?)  Send PUT request:
 ID: 6c54387b-d5b2-47e5-a8bf-5a8462167952
 Endpoint: https://test.cstar.pagopa.it/bpd/hb/payment-instruments/bpay/4b5909562e4d6de3628b3209948b24b15caeea36b5e09900233c88c20ac1ac70ab892deb26485497c83f7fe436b3c29f3ed84e6380dd738af5f124a68122219c7ac5573ecf31bf0f6be06365f13f16ba0f16bf1cce7820b0e45ba61532f976e0af7ead44d564edd30e6aaef82f6f6796612fb44d6e5ec4a948032816075f41baba34aa3cbb29925c12e7afa05b040e07f009f7bec3ddbabf1bd7b3c013db5e882553d7c58354812a2f804ce750ce652c34a5ed1a4ccf5b86b383a431897d41bd7da9a8e9ff7c149ace044683581bda2e2e5867fe6813f6ddf5e71f7e3c80d12b3be7da1239408d453fc983ec17aea414453b66df7d4c57e9d1f6afa91c17e538
{
  "fiscalCode" : "PGPTST91E25F704H",
  "channel" : "TBD",
  "groupCode" : "06085",
  "instituteCode" : "89034",
  "bank" : "CEDACRICassa di risparmio di Asti S.P.A.",
  "nameHolder" : "Pag***",
  "surnameHolder" : "Tes***",
  "phoneNumber" : "+3938*******153",
  "serviceStatus" : "true",
  "infoPaymentInstrument" : {
    "iban" : "IT00C0608500000000000663597",
    "flagPreferredPaymentPI" : true,
    "flagPreferredIncomingPI" : true
  }
}

ERROR 2020-12-15 11:54:57,057  AbstractRestClient(?: ?)  Failed : HTTP error code : 400 - Bad Request

**Comment by DenisaBraho** [comment]
Ciao Vittorio,
per l'enrollment di Bancomat Pay, come indicato nell'IA aggiornata (1.1.3.2) il campo canale dev'essere sempre valorizzato con il valore fisso "BPAY1". Potreste riprovare e fornirci un riscontro? Grazie

**Comment by BrignoliSIA** [comment]
Ciao,
anche usando il canale indicato otteniamo lo stesso errore.
Ho provato anche con una chiamata di recupera stato pagamento (GET) ed anche in questo caso otteniamo un errore 400 Bad request, ma essendo una GET non è prevista proprio alcuna richiesta se non l’endpoint.

INFO  2020-12-15 16:14:52,760  AbstractRestClient(?: ?)        Send GET request:
Endpoint: https://test.cstar.pagopa.it/bpd/hb/payment-instruments/4b5909562e4d6de3628b3209948b24b15caeea36b5e09900233c88c20ac1ac70ab892deb26485497c83f7fe436b3c29f3ed84e6380dd738af5f124a68122219c7ac5573ecf31bf0f6be06365f13f16ba0f16bf1cce7820b0e45ba61532f976e0af7ead44d564edd30e6aaef82f6f6796612fb44d6e5ec4a948032816075f41baba34aa3cbb29925c12e7afa05b040e07f009f7bec3ddbabf1bd7b3c013db5e882553d7c58354812a2f804ce750ce652c34a5ed1a4ccf5b86b383a431897d41bd7da9a8e9ff7c149ace044683581bda2e2e5867fe6813f6ddf5e71f7e3c80d12b3be7da1239408d453fc983ec17aea414453b66df7d4c57e9d1f6afa91c17e538
ERROR 2020-12-15 16:14:52,941  AbstractRestClient(?: ?)        Failed : HTTP error code : 400 - Bad Request

Potete verificare perché ci rispondete 400? Purtroppo siamo bloccati ottenendo sempre ko.

Mi fate sapere?

Tks
Vittorio

**Comment by mdesogus** [comment]
Buongiorno,

abbiamo verificato quanto segnalatoci ed il problema risiede nell'id della chiamata, tale campo per impostazione di architettura supporta un id della lunghezza massima di 260 caratteri.
Se ne avete la possibilità dovreste utilizzare un algoritmo di crittografia che generi un id entro quella lunghezza.

restiamo in attesa di un vostro riscontro,
Grazie

**Comment by BrignoliSIA** [comment]
Buona giornata, l'hashpan per noi è lungo 512.

Tale lunghezza è stata concordata anche con voi ed è già in produzione lato acquiring.

Vi preghiamo di sistemare e di permetterci anche sulla componente issuing di mandarvi gli hashpan lunghi 512.

**Comment by DenisaBraho** [comment]
Ciao Vittorio,
di seguito le evidenze dei test effettuati:

 
1 – manca il campo numeroTelefonicoCriptato --> aggiorniamo il body della chiamata lato nostro col nuovo campo atteso
2 – statoServizio è “true” >> dovrebbe essere uno tra [NFC_IN_COR, ATT, NFC_ESTINTO, ATTPND, DISPND, SAT_GG, SAT_NO, DIS, SAT_MM, SOSP]

 
Grazie

**Comment by DenisaBraho** [comment]
Ciao @BrignoliSIA lato vostro ritenete i test di integrazione conclusi o necessitate di ulteriori informazioni/supporto?
Saluti
