### ISSUE TITLE
Assistenza poste italiane, integrazione mw api_gw, 200/204 in delete payment instruments (collaudo)

### ISSUE THREAD

**Issue by AndreaMorettiPoste** [pagopa/issuer_integration#139]
In ambiente di collaudo, il MW API GW di poste italiane riscontra un comportamento non lineare della risposta alla delete del servizio payment instruments.
Si richiede verifica
[lista chiamate delete payment-instruments.txt](https://github.com/pagopa/issuer_integration/files/5701497/lista.chiamate.delete.payment-instruments.txt)

**Comment by mdesogus** [comment]
Per poter effettuare le opportune verifiche abbiamo necessità che ci venga fornito l'url della chiamata, il body della stessa ed un log dell'errore ricevuto.

Grazie

**Comment by mdesogus** [comment]
Buongiorno,

Per poter effettuare le opportune verifiche avremmo necessità che ci vengano forniti anche i log di sistema.
204 No content è la risposta standard che ci aspettiamo dall'api, ragion per cui non capiamo quale sia il comportamento inatteso

grazie

**Comment by mdesogus** [comment]
Buongiorno,

Sul file ricevuto vediamo i vari url delle delete ed il messaggio di stato ok (204), avremmo necessità di sapere qual'è il comportamento non lineare oltre che un log di evidenza.

grazie

**Comment by AndreaMorettiPoste** [comment]
lato BFF PIX vi invio questo log:

20-12-11 Fri 15:46:05.671 DEBUG 1 --- [XNIO-1 task-11] RestTemplate                             : HTTP DELETE https://apit.gp.posteitaliane.it/col/internet/pagopa/payment-instruments/5333171000641122 
20-12-11 Fri 15:46:05.672 DEBUG 1 --- [XNIO-1 task-11] RestTemplate                             : Accept=[application/json, application/*+json]
20-12-11 Fri 15:46:06.462 DEBUG 1 --- [XNIO-1 task-11] RestTemplate                             : Response 200 OK
20-12-11 Fri 15:46:06.467 INFO  1 --- [XNIO-1 task-11] LoggingReporter                          : Span reported: 5a104d3cb571b5b3:95ba5c69494e5c33:5a104d3cb571b5b3:1 - delete-payment-instruments
20-12-11 Fri 15:46:06.567 ERROR 1 --- [XNIO-1 task-11] WorkflowService                          : [deletePaymentInstruments] STEP  of type REST:
org.springframework.web.client.ResourceAccessException: I/O error on DELETE request for "https://apit.gp.posteitaliane.it/col/internet/pagopa/payment-instruments/5333171000641122":  null; nested exception is java.io.EOFException
               at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:744)

non è presente un body in quanto nella delete non è richiesto, la chiave ocp-apim-subscription-key utilizzata è 16c19a4cbc0a41a888fa6f3cb64c6992

Dato che alcune volte si riceve 204 no content e altre volte 200 Ok, vorremmo capire il comportamento corretto del servizio per gestire la risposta alla delete

**Comment by mdesogus** [comment]
una precisazione al fine di indirizzo delle verifiche:

l'url che vediamo nel log non è lo stesso presente nel file (prendo un 200 a campione come esempio: https://test.cstar.pagopa.it/bpd/hb/payment-instruments/4023602000025369).

replicando tutte le chiamate presenti nel file ricevuto questa mattina otteniamo sempre e solo 204.
ci confermate che le chiamate presenti in quel file contengono esattamente l'url che voi invocate (https://test.cstar.pagopa.it quindi) e non quelli che vediamo nel log (https://apit.gp.posteitaliane.it/col/internet/pagopa)?

**Comment by AndreaMorettiPoste** [comment]
ciao,
provo a fare un pò di ordine : lato assistenza non possiamo invocare direttamente i servizi di PagoPA che dunque invochiamo tramite intermediazione del nostro MW aziendale (API GW).

Nel file di testo che ho allegato alla issue ci sono tutte le chiamate intercettate da API GW dell'operation DELETE della payment instruments, dove si evince che alcune operazioni tornavano 200. 

il MW API GW non fa logica sulla chiamata e gira la response verso il FE di assistenza clienti.

Se mi dite che riprocessando le richieste vanno tutte a 204 faccio fare qualche altro tentativo in collaudo. In produzione il problema però è ancora presente.

Riassumendo lo schema è : 

Front end assistenza--> API GW --> PagoPA

Di seguito un esempio di chiamate dell'11/12 che restituiva 200 (da API GW) : 

url di chiamata DELETE _https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030_           
body non presente
Estratto dei log:
12/11 15:46:06.080  The target URL is resolved to 'https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000641122'
status_code       **200 OK**

**Comment by smAPIgtw** [comment]
Buongiorno,
potreste dare seguito alla richiesta? Le informazioni inviate sono sufficienti o vi occorre altro?

**Comment by mdesogus** [comment]
Buongiorno,

Sono tutt'ora in corso delle verifiche, 
se avete evidenze inerenti alle giornate di oggi o Venerdì potreste cortesemente segnalarcele?

grazie

**Comment by smAPIgtw** [comment]
Buongiorno,
nella giornata del 21 abbiamo osservato due response 200 a seguito di una delete, di seguito le evidenze:
- December 21st 2020, 08:28:09.727 DELETE https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5354760568760185 -> response 200 OK 
-  December 21st 2020, 08:35:24.237 DELETE https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5354760568760185 -> response 200 OK 

Tutte le altre richieste hanno dato esito 204 No content negli ultimi 7 giorni

**Comment by mdesogus** [comment]
Buongiorno,

da verifiche effettuate confermiamo che in alcune circostanze il backend dell'Api Management risponde 200 invece di 204.

Essendo una verifica che necessita di un sopporto da parte del team Microsoft (owner del prodotto), e la problematica non ha priorità elevata in quanto non bloccante riprenderemo le analisi in un secondo momento.

Grazie

**Comment by AndreaMorettiPoste** [comment]
Buongiorno,
vorrei sapere se ci sono aggiornamenti rispetto a questa tematica. Come indicato nel thread la stessa è presente anche in ambiente di produzione.

grazie

**Comment by AndreaMorettiPoste** [comment]
Buongiorno, sollecito un vostro aggiornamento su questa segnalazione. E' passato quasi un mese, il problema è ancora presente e non abbiamo avuto aggiornamenti

**Comment by DenisaBraho** [comment]
Ciao Andrea,
abbiamo contattato il supporto Microsoft, è stata effettuata una modifica in ambiente di UAT che dovrebbe aver risolto la problematica riscontrata. Vi preghiamo di effettuare dei check fornendoci un riscontro in merito oppure indicarci eventuali evidenze in caso di errori inattesi.
Rimaniamo a disposizione
Saluti

**Comment by AndreaMorettiPoste** [comment]
salve,
abbiamo fatto un test in ambiente di collaudo e la problematica non risulta superata. Di seguito due tentativi fatti a pochi minuti di distanza sulla stessa carta  :

01/02/2021 13:06:45.804  HTTP response code 204 for  HTTP/1.1 DELETE 'https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000577136'

01/02/2021 11:25:45.716 HTTP **response code 200** for HTTP/1.1 DELETE  'https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000577136'

**Comment by mdesogus** [comment]
Buonasera,

abbiamo riportato i casi indicati nell'ultima segnalazione al team di supporto Microsoft, non appena avremo riscontri vi forniremo ulteriori aggiornamenti.

grazie

**Comment by AndreaMorettiPoste** [comment]
Si sollecita un riscontro su questa issue, si ribadisce che la stessa è presente anche in ambiente di produzione.

**Comment by mdesogus** [comment]
Buongiorno,

avremmo necessità di effettuare alcuni test congiunti, è stata inviata una mail per verificare la disponibilità.

grazie

**Comment by mdesogus** [comment]
Buongiorno,

ci sono esiti sull'esecuzione dei test pianificati nella call di ieri?

grazie

**Comment by smAPIgtw** [comment]
Buonasera,
sembra che il problema sia ancora presente, infatti dalla lista delle ultime chiamate ci sono sia 200 che 204, come potete vedere di seguito
March 11th 2021, 10:16:47.865  200 OK  [..]payment-instruments/5333171000577110    
March 11th 2021, 09:16:10.742  204 No Content  [..]payment-instruments/5333171000577136    
March 11th 2021, 09:11:49.629  200 OK  [..]payment-instruments/5333171000577136    
March 11th 2021, 08:40:14.428  204 No Content  [..]payment-instruments/5333171000575403    
March 10th 2021, 19:22:30.737  200 OK  [..]payment-instruments/5333171000577110    
March 10th 2021, 19:21:41.536  200 OK  [..]payment-instruments/5333171000577136    
March 10th 2021, 19:21:08.329  200 OK  [..]payment-instruments/5333171000575403    
March 10th 2021, 12:30:34.736  204 No Content  [..]payment-instruments/5333171000575148 

saluti

**Comment by mdesogus** [comment]
Ciao,

Per conferma, le chiamate indicate sono state effettuate dal vostro sistema o come nella call utilizzando postman?
nel caso in cui fossero fatte da sistema le stesse da postman hanno lo stesso esito?

grazie

**Comment by smAPIgtw** [comment]
buonasera,
le chiamate indicate sono state effettuate dal sistema client, invece utilizzando postman riceviamo con gli stessi pan sempre 204, chiedo una verifica al client, nel frattempo penso che ancora non possiamo chiudere la issue.

saluti

**Comment by mdesogus** [comment]
buongiorno,

grazie, restiamo a disposizione ed in attesa di riscontro.

saluti

**Comment by smAPIgtw** [comment]
Buonasera,
il client ci fa sapere che la problematica non si presenta più, possiamo chiudere la issue.

grazie per la disponibilità

saluti
