### ISSUE TITLE
Richiesta configurazione certificato MTLS per API in ambiente di SIT

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#14]
Leggendo la vostra documentazione (in special modo nel documento “Issuer Interface Agreement_v2.pdf”, paragrafo “Appendice 1 - Autenticazione Issuer”) avremmo la necessità di configurare il certificato per l’autenticazione MTLS dell’ambiente di SIT.

Nel vostro documento, per lo specifico ambiente di SIT,  fate riferimento a:
1)	Registrazione su sito https://bpd-dev.developer.azure-api.net/ con generazione di API-Key 
2)	Fornitura del certificato Self-Signed in formato “pfx” + chiave pubblica in formato “cer” a PagoPA

Per il secondo punto tuttavia non ci è chiaro come fornirvi il certificato.
Potreste darci indicazione di che modalità utilizzare per inviarvelo al fine di iniziare a testare le API in questione?

**Comment by alessio-cialini-sia** [comment]
Per SIT dovete inviare il vostro certificato self-signed, in formato pfx (e relativa password), oltre che alla catena di certificati delle CA utilizzate (Root ed intermedia), in format .cer, potete inviare a TeamCentroStella@sia.eu.
