### ISSUE TITLE
bpd/hb/payment-instruments/card metodo PUT -- UAT

### ISSUE THREAD

**Issue by daviogg** [pagopa/issuer_integration#140]
PUT: 'https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card'
{
    "id": "-----BEGIN PGP MESSAGE-----\nVersion: BCPG C# v\n\nhQEMA+NENQPn0iNJAQgAoED5QbUXIASDtAwV2DKmTYvAHA991uRQPW9mdM45mwSH\ndDiGliJrkuERvgLKzmJ8b1z1LUDUMczGWiDvgP0FZktdDBaRcy8Hp0e9rQUZO1Yg\nxDUpuK8WtwJpjrkDkv5szffkIFB+vPacNmm15j60bXsBcno1fNy8Y24LFo9Sm7PL\n3LjPdInWX+/u7sTiDfOGY7KI7j9MQZ2MFYSUOiQViAWoGSfSfMmEBHbw+JAcmPa6\nn9EvtuSVkzRHl/hsxIdhYMp9Phhz41aner8LpoCum5GLQeivPEiZGfFcaMycO4hS\n/bLpSSngw7+57FVdmwtrWR8zBNcYRZGkeaeNyjbW9NJDAV86c5g3KEVTUD7Rj3Ws\npgkjin5q97SEGJ5QS1pC1iO4Ix21BDBIIQdL+bdsIhvmm8395ynLs6RQc+AYdAtp\nFGHsWw==\n=FfCi\n-----END PGP MESSAGE-----\n",
    "fiscalCode": "{{FiscalCode}}",
    "expireYear": 2025,
    "exprireMonth": 9,
    "issuerAbiCode": "36003",
    "brand": "MASTERCARD",
    "holder": "OGGIONI SIMONE",
    "type": "DEB",
    "channel": "36003"
}

Buongiorno, sto avendo problemi con la chiamata ricevendo un 400 Error PM,
temo che sia dovuto all'expireMonth, è corretto che bisogna mandare in stringa "09" e non un numeric?

**Comment by mdesogus** [comment]
Buongiorno,

confermiamo quanto detto, il campo "expireMonth" deve essere mandato in formato stringa di 2 caratteri.

grazie
