### ISSUE TITLE
Internal Server error enrollment strumento di pagamento

### ISSUE THREAD

**Issue by antessio** [pagopa/issuer_integration#141]
Ambiente: **UAT**
x-request-id: **e18c6c13-a9fc-41d9-86b0-d21f36702bc5**
Path: `/bpd/hb/payment-instruments/satispay/93c0a980-23c0-4ec3-ad0a-bed22e0d79af`
Request Body:
```json
 {
	"fiscalCode":"LMBGNN91P05B157M",
	"channel": "SATISPAY"
}
```

Http Status: **500**
Response Body:
```json
{
  "statusCode": 500,
  "message": "Internal server error",
  "activityId": "45e80b8f-627f-412b-88c9-087c9204906e"
}
```

In UAT abbiamo questo errore cercando di fare l'enrollment dello strumento di pagamento, l'utente si era attivato in precedenza, ha cancellato la sua iscrizione chiamando `DELETE /bpd/hb/citizens/LMBGNN91P05B157M`

Lo stesso risultato lo otteniamo per un utente mai iscritto.

**Comment by mdesogus** [comment]
il valore del campo channel nel caso specifico deve essere valorizzato con "STPAY".
Sarebbe possibile riprovare e fornirci riscontro?

**Comment by antessio** [comment]
Salve,
in realtà il servizio inviava il channel corretto, ma ho riportato una chiamata sbagliata. 

Da qualche minuto comunque sembra essersi risolto. 

Grazie

**Comment by mdesogus** [comment]
grazie per il riscontro, 
procediamo dunque alla chiusura della issue
