### ISSUE TITLE
Errore in set IBAN

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#142]
Buongiorno, il servizio PATCH bpd/hb/citizens/{id} ritorna errore 400

{"returnMessages":{"ERROR":[{"message":"Unknown","messageTitle":"Unknown","messageKey":"resource.not-enabled.error","retry":false,"errorCode":"UNKNOWN","severity":"ERROR"}]}} 

in caso nel campo di input accountHolderSurname sia presente un apostrofo.
Dobbiamo eliminare questo carattere nella request al servizio? Dobbiamo applicare la stessa bonifica anche nel campo accountHolderName? Dobbiamo intercettare anche le lettere accentate?

Grazie

**Comment by mdesogus** [comment]
Buongiorno,

per poter  effettuare le opportune verifiche avremmo necessità di sapere su quale ambiente è stato effettuato il test e che ci forniste anche l'url ed il body della chiamata.

grazie

**Comment by AndreaCaccin** [comment]
L'ambiente è produzione, per ovvie ragioni di privacy di seguito la response coi dati sensibili oscurati
{ 
    accountHolderCF: *******
    accountHolderName: *******
    accountHolderSurname: *******'oro
    payoffInstr: IT69A3287501600N17344460015
    payoffInstrType: IBAN
}

La mia domanda comunque era in generale: nei campi indicati sono previsti caratteri non ammessi tra 
- apostrofi
- lettere accentate
Grazie

**Comment by mdesogus** [comment]
a seguito di test effettuati confermiamo che non ci sono problematiche inerenti all'inserimento di apostrofi, maiuscole o caratteri accentati all'interno dei campi segnalati.

visionando il log di errore notiamo:

{"returnMessages":{"ERROR":[{"message":"Unknown","messageTitle":"Unknown","messageKey":"**resource.not-enabled.error**","retry":false,"errorCode":"UNKNOWN","severity":"ERROR"}]}}

potete verificare che l'utente per cui si stia effettuando la patch sia effettivamente attivo?

**Comment by AndreaCaccin** [comment]
L'utente risulta avere il timestamp di accettazione T&C valorizzato ma campo enabled false: è questo il motivo dell'errore quindi?
 {
    enabled: false
    fiscalCode: *******
    payoffInstr: null
    payoffInstrType: null
    timestampTC: 2020-12-09T17:22:32.797+01:00
}

Grazie

**Comment by mdesogus** [comment]
corretto, 
 
in fase di censimento/aggiornamento dell'iban l'algoritmo verifica in un primo momento che l'utente in questione sia attivo (parametro enabled valorizzato a true dunque);
qualora il valore risulti essere valorizzato a false, verrà restituito un errore come quello in evidenza nel log in cronologia.

procediamo alla chiusura della issue, per ulteriori segnalazioni vi preghiamo di riaprire la presente

Grazie

**Comment by AndreaCaccin** [comment]
La valutazione del campo enabled è necessaria solo per il censimento dell'iban o per disciminare lo stato complessivo del codice fiscale? Nello specifico, in caso il campo sia false, per proseguire l'utente deve accettare nuovamente i termini e condizioni?
Grazie
