### ISSUE TITLE
Errore 403 /bpd/hb/citizens/{id} PUT

### ISSUE THREAD

**Issue by DavidePiva** [pagopa/issuer_integration#143]
Buonasera,

potreste per favore verificare la causa dell'errore 403 che stiamo ricevendo in ambiente di INT per la chiamata /bpd/hb/citizens/BRPGNE61B18F132V ? 
Da documentazione il 403 non dovrebbe essere uno stato possibile per la chiamata PUT.

Grazie

**Comment by mdesogus** [comment]
Buonasera, 

Per poter effettuare le opportune verifiche avremmo necessità che indichiate l'ambiente corretto oltre che tutti i parametri della chiamata (url completo e body) ed il log di errore.

grazie

**Comment by DavidePiva** [comment]
Buongiorno,
ecco i dettagli richiesti:

Ambiente: SIT

Servizio: https://bpd-dev.azure-api.net/bpd/hb/citizens/BRPGNE61B18F132V (body non presente nella chiamata PUT).

 Il certificato utilizzato per la mutua autenticazione è il: CN=pagopa.stgb2b.nexi.it, O=NEXI, L=Milano, ST=Milano, C=IT .

Grazie

**Comment by DavidePiva** [comment]
Buonasera,

ho visto la risposta alla issue https://github.com/pagopa/issuer_integration/issues/146 , siamo due gruppi di Nexi differenti ma utilizziamo entrambi lo stesso certificato. E' necessario che venga riabilitato quanto prima, potete procedere gentilmente?

Grazie

**Comment by mdesogus** [comment]
Buongiorno,

i certificati sono riabilitati, potete riprovare e fornirci riscontro?

grazie

**Comment by DavidePiva** [comment]
Confermo che le chiamate hanno ripreso a funzionare.

Grazie e buon lavoro
