### ISSUE TITLE
Valutazione campo "enabled" di citizen

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#144]
La valutazione del campo enabled è necessaria solo per il censimento dell'iban o per disciminare lo stato complessivo del codice fiscale? Nello specifico, in caso il campo sia false, per proseguire l'utente deve accettare nuovamente i termini e condizioni?
Grazie

_Originally posted by @AndreaCaccin in https://github.com/pagopa/issuer_integration/issues/142#issuecomment-748209579_

**Comment by mdesogus** [comment]
Il campo enabled di per sè indica che un utente è iscritto al programma, perciò è utile per discriminare lo stato del codice fiscale.
E' necessario che il campo sia valorizzato a true per procedere con il censimento/aggiornamento dell'iban.
Se valorizzato a false per per proseguire l'utente deve accettare nuovamente i termini e condizioni.

grazie
