### ISSUE TITLE
Richiesta Data Preparation

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#145]
Buonasera,
per tracciatura della richiesta di Data Preparation in ambiente di UAT per poter testare la soluzione.
Riferimento dell'email:
- mittente: marco.denovellis@mail-bip.com
- data e ora: 18/12/2020  18:24
- oggetto: Richiesta Data Preparation per test

**Comment by SteveGiudice** [comment]
Ci sono novità su questo tema?

**Comment by DenisaBraho** [comment]
Buongiorno ,

la data preparation finalizzata alla creazione degli scenari da voi richiesti, riportati nella mail in calce, è stata terminata. Potreste gentilmente verificare se il data set risulta allineato con quanto richiesto?
 
Saluti

**Comment by SteveGiudice** [comment]
Buongiorno,

purtroppo non possiamo verificare la bontà della data preparation a causa della issue https://github.com/pagopa/issuer_integration/issues/150

**Comment by DenisaBraho** [comment]
Ciao,
la issue 150 è stata risolta. Vi preghiamo di verificare e di fornirci un feedback in merito
Grazie mille

**Comment by DenisaBraho** [comment]
Lato BPD l'anomalia adesso risulta rientrata. Se riscontrate nuovamente delle anomalie oppure problemi con la data preparation, vi chiediamo di procedere con la riapertuara della issue in questione oppure con l'apertura di una nuova segnalazione.
Grazie
Saluti

**Comment by MarcoDeNovellis** [comment]
Ciao,

Confermiamo che il precedente disallineamento non si verifica più.

Grazie mille

MDN

Marco De Novellis


[cid:image001.png@01D58B24.0372DB00]


Piazza San Babila 5
20122 Milano
www.bipconsulting.com<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.bipconsulting.com%2F&data=02%7C01%7Cmarco.denovellis%40mail-bip.com%7C7f76b875ef664d667b9e08d79423148c%7Cbb1a63ebeb09471aa00537b07792a5b5%7C0%7C0%7C637140750690553164&sdata=9XHlNeXD3qEdIug3vuwZKBARnXiYOO%2F4K5yNwXkKxto%3D&reserved=0>

Our Offices:
Italy Milano, Roma, Mogliano Veneto, Bologna
EMEA London, Madrid, Barcelona, Bruxelles, Lugano, Istanbul, Abu Dhabi
North America New York
South America Sao Paulo, Rio De Janeiro, Santiago de Chile
