### ISSUE TITLE
errore 403 ambiente SIT

### ISSUE THREAD

**Issue by luca-delgiudice-dev** [pagopa/issuer_integration#146]
Ciao,
in ambiente SIT riceviamo errore 403 su tutte le chiamate verso api /bpd/*

Di seguito il log di un caso:

metodo GET
https://bpd-dev.azure-api.net/bpd/hb/citizens/TSTMIA00L14A074F

Date: Mon, 21 Dec 2020 09:31:49 GMT
HTTP/1.1 403 Forbidden

Potete verificare?

grazie,
Luca

**Comment by mdesogus** [comment]
Buongiorno,

purtroppo abbiamo un numero limitato di certificati client che possiamo caricare in ambiente di SIT. 

Dato che i servizi sono attivi sia in produzione che in uat, abbiamo dovuto temporaneamente rimuovere anche il vostro certificato(mail ad Alessio.Nava@nexi.it in data 17/12) .

Qualora ci sia l'esigenza di effettuare ulteriori sessioni di test in SIT lo possiamo ricaricare.

grazie

**Comment by luca-delgiudice-dev** [comment]
Buongiorno,
avremmo bisogno di riattivare le chiamate per completare alcuni sviluppi in ambiente SIT.
grazie,
Luca

**Comment by mdesogus** [comment]
Buongiorno,

i certificati sono riabilitati, potete riprovare e fornirci riscontro?

grazie

**Comment by luca-delgiudice-dev** [comment]
Ora le chiamate funzionano correttamente.
grazie,
Luca

**Comment by mdesogus** [comment]
grazie per il riscontro, procediamo dunque con la chiusura della issue.

buona giornata
