### ISSUE TITLE
Errori in winning-transactions

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#147]
Buongiorno, in ambiente di produzione, da questa mattina, stiamo rilevando sistematicamente errori 500 in invocazione del servizio bpd/hb/winning-transactions: di seguito una chiamata di esempio
REQUEST 2020-12-23 12:06:11,785
bpd/hb/winning-transactions/fiscalCode=CCCNDR82H10B563M&awardPeriodId=1

RESPONSE 2020-12-23 12:06:12,777
{	"errcode":500,	"errmsg":"Internal Server Error"}

Potete verificare?

Grazie

**Comment by DenisaBraho** [comment]
Ciao, l'anomalia è stata risolta. vi chiediamo di verificare nuovamente.
Grazie

**Comment by AndreaCaccin** [comment]
Confermo che risulta rientrata. Grazie

A disposizione
