### ISSUE TITLE
PROD error GET /bpd/hb/citizens/

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#148]
Buongiorno, da circa le 11:30 stiamo ricevendo "503 Service Temporarily Unavailable" nelle invocazioni al servizio di recupero info cliente GET /bpd/hb/citizens/
Di seguito un caso di esempio
REQUEST 2021-01-01 11:41:32,408
/bpd/hb/citizens/CCCNDR82H10B563M

RESPONSE 2021-01-01 11:41:32,617
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

Potete verificare?

Grazie

Andrea Caccin

**Comment by AndreaCaccin** [comment]
Adesso l'errore riscontrato è error 500

REQUEST 2021-01-01 12:08:51,763
/bpd/hb/citizens/CCCNDR82H10B563M

RESPONSE 2021-01-01 12:08:56,997
{	"errcode":500,	"errmsg":"Internal Server Error"}

**Comment by DenisaBraho** [comment]
Ciao,
l'anomalia non dovrebbe essere piu presente.
Potreste riprovare?

**Comment by AndreaCaccin** [comment]
Confermiamo. Grazie
