### ISSUE TITLE
PROD response null in Ranking

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#149]
Buonasera, stiamo ricevendo response null nella chiamata /bpd/hb/citizens/{id}/ranking.
Di seguito un caso di esempio
REQUEST 2021-01-01 18:41:04,105
/bpd/hb/citizens/CCCNDR82H10B563M/ranking[1]

RESPONSE 2021-01-01 18:41:04,291
null

Potete verificare? Grazie

**Comment by DenisaBraho** [comment]
Ciao,
adesso dovrebbe funzionare, potreste riprovare ? Grazie

**Comment by AndreaCaccin** [comment]
Confermiamo. Grazie
