### ISSUE TITLE
Recupero graduatoria (/bpd/hb/citizens/{id}/ranking) Formato invalito attributo "awardPeriodId"

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#150]
Buongiorno,
questa mattina in ambiente di UAT effettuando la chiamata al servizio di "Recupero graduatoria" (/bpd/hb/citizens/{id}/ranking) riscontriamo un formato invalido nel campo "awardPeriodId".

In documentazione infatti è dichiarato un tipo "Numeric" mentre noi riceviamo un valore "all" che fa fallire il parsing della chiamata.

Qui di seguito un esempio:

URL: GET - https://test.cstar.pagopa.it/bpd/hb/citizens/RSTFBA85H03L259F/ranking
RESPONSE:
[
    {
        "awardPeriodId": **all**,
        "transactionNumber": 0,
        "ranking": 100001,
        "totalParticipants": 5000000,
        "minTransactionNumber": -1,
        "maxTransactionNumber": 500
    }
]

Potreste risolvere per favore?

**Comment by SteveGiudice** [comment]
Vorrei evidenziare che questo problema è ostativo al rilascio in produzione della funzionalità!
è possibile avere una risposta a breve?

**Comment by DenisaBraho** [comment]
Ciao, l'anomalia è stata risolta.  Vi preghiamo di verificare. 
Grazie
Saluti
