### ISSUE TITLE
Rimozione profilo - simulazione errore "TOO_MANY_CHANNELS" - SIT

### ISSUE THREAD

**Issue by DanieleConti** [pagopa/issuer_integration#151]
Buongiorno,
chiedo se è possibile simulare un profilo che presenti il seguente errore:

400 KO ("TOO_MANY_CHANNELS" - risultano presenti strumenti di pagamento attivi su altri canali diversi da quello dell’Issuer chiamante)

In seguito alla richiesta di rimozione del profilo stesso:

DELETE https://bpd-dev.azure-api.net/bpd/hb/citizens/_FiscalCode_
REQUEST 
{
    "channel": "36003"
}

in modo tale da poter eseguire un test su SIT.

Grazie

**Comment by daniloMessinaSia** [comment]
Buongiorno, 
dovreste fornici, se possibile, dei CF di esempio in modo da poter predisporre l'ambiente con quanto richiesto

**Comment by DenisaBraho** [comment]
Ciao,
adesso è possibile simulare l'errore in SIT. 

Per effettuare tale simulazione, è sufficente censire due strumenti di pagamento con channel differenti (es.  36003; altra stringa ). Nel momento di recesso, inserendo nel body della chiamata,uno dei channel ( oppure un'altro valore) dovreste ricevere l'errore "TOO_MANY_CHANNELS
Saluti
