### ISSUE TITLE
SIT - Errore durante richiesta recesso cittadino

### ISSUE THREAD

**Issue by amarano-github** [pagopa/issuer_integration#153]
Ciao,
stiamo riscontrando problemi nel provare a richiedere il recesso di più utenze attualmente abilitate/attive sulla piattaforma.

Abbiamo analizzato l'ultima documentazione da voi rilasciata e la nostra interfaccia risulta allineata con la descrizione dell'api.
Ci sono stati aggiornamenti nell'ambiente di SIT riguardanti anche la DELETE in questione? 

Non ottenendo la causa specifica dell'errore che riceviamo, potreste verificare?
Qui di seguito, i dettagli di una delle chiamate effettuate:

x-request-id: 3bc4c2d3-7acf-4ff6-8e3d-2d96fc6bd81e

Request:   
DELETE https://bpd-dev.azure-api.net/bpd/hb/citizens/RSSMRA82A01B212O
{"channel":"36024"}

Response:
{"returnMessages":{"ERROR":[{"message":"Errore generale contattare l'assistenza","messageTitle":"Errore Generale","messageKey":"generic.error","severity":"ERROR"}]}}

Grazie in anticipo.

**Comment by DenisaBraho** [comment]
Ciao,
il servizio adesso funziona correttamente.
Vi preghiamo di verificare. 
Grazie
