### ISSUE TITLE
Error 500 in ambiente UAT su integrazione Issuer

### ISSUE THREAD

**Issue by BrignoliSIA** [pagopa/issuer_integration#156]
In ambiente di test per tutta la giornata riscontriamo da parte vostra degli esiti 500 a fronte delle chiamate di gestione Issuer; vi riporto un esempio:

INFO  [hjgbkzsfda7iu8t2wq3gsj][d5776fb6-a045-48be-82d5-8620430ca208][920f19d96e78456c8cc657973872cb30][89034][05704] 2021-01-15 14:15:04,388    AbstractRestClient(?: ?)        Send DELETE request:
 ID: b23f3bc6-fb4b-44e3-b6ba-fdfad446f100
 Endpoint: https://test.cstar.pagopa.it/bpd/hb/citizens/SITSIT01A01F205A
ERROR [hjgbkzsfda7iu8t2wq3gsj][d5776fb6-a045-48be-82d5-8620430ca208][920f19d96e78456c8cc657973872cb30][89034][05704] 2021-01-15 14:15:04,572    AbstractRestClient(?: ?)        Failed : HTTP error code : 500 - Internal Server Error

Potreste verificare il perchè?

Grazie mille
VB

**Comment by DenisaBraho** [comment]
Ciao VIttorio,
ci potreste fornire il body della chiamata?
Grazie

**Comment by DenisaBraho** [comment]
A seguito della mail ricevuta, procediamo con la chiusura issue. Qualora dovesso presentarsi problemi, vi preghiamo di procedere con l'apertura di una nuova issue. 
Saluti
