### ISSUE TITLE
[PROD] Errore API /bpd/hb/payment-instruments/card "hpan already exists"

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#157]
Stiamo riscontrando dei casi per il quale l'enroll della carta di debito di alcuni dei nostri clienti riscontrano l'errore "hpan already exists".
Qui i dettagli:

URL: https://prod.cstar.pagopa.it/bpd/hb/payment-instruments/card
RESPONSE: 
{
    "returnMessages": {
        "ERROR": [
            {
                "message": "Unknown",
                "messageTitle": "Unknown",
                "messageKey": "hpan already exists",
                "retry": false,
                "errorCode": "UNKNOWN",
                "severity": "ERROR"
            }
        ]
    }
}

La nostra richiesta è legata al fatto che, dato il PAN 1234567890123456 dell'utente che riscontra l'errore "hpan already exists", verificando lo status della carta attraverso l'API:
https://prod.cstar.pagopa.it/bpd/hb/payment-instruments/1234567890123456

Riscontriamo l'associazione di un codice fiscale DIVERSO da quello del nostro cliente richiedente (in alcuni casi il codice fiscale che risulta in possesso del PAN in input non è nemmeno un nostro cliente)

Riuscireste a darci un riscontro?

**Comment by DenisaBraho** [comment]
Ciao,
lato funzionamento servizio non riscontrimo degli errori applicativi . In caso di segnalazioni lato utenti di questo tipo, è necessario segnalare il caso specifico all'assistenza clienti PagoPa e la segnalazione verrà analizzata.
Saluti

**Comment by albertosangalliflowe** [comment]
Ok.
Tuttavia sono in attesa da circa una settimana (data richiesta il 20/1/2021) della  Generazione della Password Temporanea PagoPA (mail automatica di Service Now) ma senza risposta.
Tale password non mi è mai arrivata.
Voi sapreste indirizzarmi a un contatto per sbloccare la situazione?
