### ISSUE TITLE
1.1.5 Status Citizen H/M Banking

### ISSUE THREAD

**Issue by devitafederica** [pagopa/issuer_integration#158]
Mi confermate che la logica per verificare se i T&C PagoPA sono accettati e validi per proseguirecon l'attivazione di uno strumento è la seguente?

Interrogo il servizio 1.1.5 Status Citizen H/M Banking e verifico:

enabled = true (considerando come data di riferimento di accettazione quella indicata nel campo timestampTC)

Se l'utente fa recesso, eseguendo l'inquiry il campo **enabled** risulterebbe  valorizzato a false. Corretto?

Quindi se il valore è false prima di poter procedere ad un enrollment di un nuovo strumento, l'utente DEVE riaccettare i T&C, corretto?

Grazie
Federica

**Comment by DenisaBraho** [comment]
Ciao Federica,

si esatto, confermiamo tutti i punti e passaggi del processo da te descritti.  

a disposizione
Saluti
