### ISSUE TITLE
1.1.8 Lista periodi premi

### ISSUE THREAD

**Issue by devitafederica** [pagopa/issuer_integration#160]
Ci confermate che il formato dei seguenti campi restituiti dal servizio in oggetto, sarà sempre senza millisecondi?

"startDate":"2021-07-01","endDate":"2021-12-31"

In generale le date sono sempre fornite  con l’indicazione dei millisecondi, mentre in questo caso arrivano senza. 
E’ corretto così? Se sì potete garantirci che non cambierà in futuro?
Per una corretta visualizzazione delle date in app, dobbiamo applicare un formato data specifico in input che non si può modificare a runtime.

Grazie
Federica

**Comment by DenisaBraho** [comment]
Ciao,
confermiamo che il formato contiene solo la data (senza millisecondi); a livello di "giorno di inizio" e "giorno di fine" di un periodo non c'è un ora legata all'informazione.
Saluti
