### ISSUE TITLE
1.1.9 Recupero graduatoria - Dati restituiti incoerenti

### ISSUE THREAD

**Issue by devitafederica** [pagopa/issuer_integration#161]
Ciao,
stiamo eseguendo i test interni sull'app BPay.
Volevamo verificare la bontà dei dati restituiti dai servizi di recupero graduatoria.
La posizione in classifica che ci viene restituita però non ci sembra corretta e coerente.
Riscontriamo posizione in classifica più bassa del totale dei partecipanti, ovvero:
ranking =10408103
totalParticipants = 10408102
 
Di seguito un estratto dei log:

INFO   2021-01-21 12:21:03,507    AbstractRestClient(?: ?)        Send GET request:
 ID: 5deb3a08-71e8-489a-bc64-36e3ff2589aa
 Endpoint: https://test.cstar.pagopa.it/bpd/hb/citizens/SITSIT01A01F205A/ranking?awardPeriodId=1
INFO   2021-01-21 12:21:03,707    AbstractRestClient(?: ?)        Received GET response:
 ID: 5deb3a08-71e8-489a-bc64-36e3ff2589aa
 HttpResponseProxy{HTTP/1.1 200 OK [Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Transfer-Encoding: chunked, Content-Type: application/json;charset=UTF-8, Expires: 0, X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, X-Frame-Options: DENY, Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4, Date: Thu, 21 Jan 2021 11:21:03 GMT]}
 Content object:
 [{**"ranking":10408103,"totalParticipants":10408102,**"maxTransactionNumber":120,"minTransactionNumber":15,"transactionNumber":0,"awardPeriodId":1}]

Potete verificare?
Si tratta per caso di valori fittizi tipo stubbati e restituiti di default?

Grazie
Federica

**Comment by DenisaBraho** [comment]
Ciao Federica, 
le logiche attuali implementate prevedono che il ranking di tutti i cittadini che non hanno effettuato **nessuna** transazione durante il periodo di riferimento, sia uguale a _"totalParticipants +1"._

Di conseguenza, se per il citizen d'esempio utilizzato nella chiamata indicata non ci sono delle trx associate nel periodo 1, la risposta della chiamata è da ritenersi corretta. 
A disposizione
