### ISSUE TITLE
Servizi di Inquiry - Dati restituiti incoerenti

### ISSUE THREAD

**Issue by devitafederica** [pagopa/issuer_integration#162]
Ciao,
stiamo eseguendo test interni su APP BPay. In delle prove eseguite ieri però, abbiamo riscontrato delle incoerenze sulla restituzione dei dati, che non ci permettono di testare in modo esaustivo i nostri sviluppi.

In particolare poco prima delle 13.00 per l'utente oggetto del test il programma cashback risultava abilitato con strumento bpay abilitato. Senza aver fatto nessuna chiamata di enrollment, recesso o disattivazione, alle 14.47 il servizo di inquiry per lo stesso utente risponde che aveva sia cashback che strumento bpay disabilitati. 5 minuti dopo e senza altre chiamate lo stesso servizio restituisce che il cashback è attivo e lo strumento disattivo.

Riporto in allegato
[20210121_chiamate_enrollmentCashBackPagoPa.log](https://github.com/pagopa/issuer_integration/files/5855187/20210121_chiamate_enrollmentCashBackPagoPa.log)

 dettaglio delle chiamate eseguite tra le 12.40 e le 14.50 del 21/01/2021.
Potreste verificare come mai ci vengono restituiti questi dati incoerenti?

**Comment by DenisaBraho** [comment]
Ciao Federica,
dato che le chiamate sono eseguite in ambiente di test (UAT) potrebbero presentarsi delle situazioni simili nel caso in cui ci siano degli altri gdl che effettuano sviluppi/test parallelli che usano la stessa base dati.
Qualora questa problematica si riscontrasse nuovamente su piu casi, vi preghiamo di segnalarcelo in modo da indirizzare al meglio le verifiche del caso.
Saluti

**Comment by daniloMessinaSia** [comment]
Ciao,
scusate il ritardo nella risposta.
Relativamente al tema incongruenze, vi portiamo un aggiornamento.
Da verifiche effettuate, lo stato degli strumenti di pagamento è mutato poichè sono state effettuate bonifiche massive per riallineare la base dati con quella della componente Payment Manager pertanto abbiamo verificato che anche i vostri strumenti di pagamento sono rientrati in tale operazione.

Gli interventi di bonifica si sono conclusi nei giorni scorsi pertanto non dovrebbero più presentarsi tali incongruenze.

Buona serata
