### ISSUE TITLE
Errore 500 payment-instruments/card PUT

### ISSUE THREAD

**Issue by DavidePiva** [pagopa/issuer_integration#164]
Buongiorno,

potreste verificare come mai indicativamente da ieri nel tardo pomeriggio queste chiamate hanno cominciato ad andare in 500 in ambiente di UAT per favore?

METHOD=PUT
URL=https://developer- test.cstar.pagopa.it/bpd/hb/payment-instruments/card

REQUEST_BODY={"id":"************6536","fiscalCode":"XXXXXXXXXXXX","expireYear":2025,"exprireMonth":"11","issuerAbiCode":"05696","brand":"MASTERCARD","holder":"XXXXXXXXXXXXX","type":"CRD","channel":"05555"}

|KO|_|_CODE=500_|_STATUS_TEXT=Internal Server Error

HEADERS_REQUEST=Server: Apache-Coyote/1.1 Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4 Date: Fri, 29 Jan 2021 10:17:30 GMT Connection: close 

HEADERS_RESPONSE=Accept: text/plain, application/json, application/*+json, */* x-request-id: 60998cbb-cade-44fd-b235-37ebd3870f33 Ocp-Apim-Subscription-Key: XXXXXXXXXXXXXXX

Grazie

**Comment by mdesogus** [comment]
buongiorno,

potreste rieseguire il test utilizzando l'url
 https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card  invece di quello da voi utilizzato e fornirci riscontro?

grazie

**Comment by DavidePiva** [comment]
Buongiorno,

l'endpoint chiamato è quello da voi indicato (scusate c'era un errore dovuto ad una rielaborazione manuale del log).
Abbiamo riprovato in questo momento una nuova chiamata:
2021-02-01 11:54:47      
x-request-id: 6662432c-1b31-4f64-93a0-9edf6b76af7a

Riceviamo ancora l'errore 500. Potete ricontrollare per favore?

Grazie

**Comment by DenisaBraho** [comment]
Ciao,
l'id dello strumento utlizzato per la chiamata è stato pgpizzato con la chiave condivisa?
Grazie

**Comment by DavidePiva** [comment]
Ciao,
no, ma salvo errori però fino a poco tempo fa non era obbligatorio il pgp in questo ambiente. Comunque quasi certamente la causa è quella. 
Grazie
