### ISSUE TITLE
Non aggiornamento del cumulativo

### ISSUE THREAD

**Issue by BrignoliSIA** [pagopa/issuer_integration#165]
Buona giornata,

a fronte di operatività in test su utenti con strumento BancomatPay regolarmente registrato su cashback, non vediamo sull'app di circuito l'aggiornamento dell'operatività dello stesso utente.

Abbiamo verificato che i flussi acquiring con tale operatività vi sono stati inoltrati e che nelle response dei servizi Issuer tale operatività non ci viene rilasciata.
Vi forniamo dei casi di esempio allegati nella componente attachment con due utenti (operatività in azzurro e rosa) sui quali non vediamo l'aggiornamento del cumulativo rispetto alle operazioni [indicate.]([url](url
[Evidenze di prove su cashback.docx](https://github.com/pagopa/issuer_integration/files/5903960/Evidenze.di.prove.su.cashback.docx)
))

Fateci sapere 

Grazie mille
Vittorio

**Comment by edo621** [comment]
Buongiorno Valerio,

scusa per il ritardo nella risposta, abbiamo comunque preso in carico l'attività.

Vi daremo un riscontro risolutivo quanto prima

Edoardo

**Comment by edo621** [comment]
Buonasera Vittorio,

sarebbe possibile avere in aggiunta a quanto  già condiviso:
- CF
- hpan
- di quanto non torna il cumulativo
- nome del flusso ed ora è stato inviato in Centrostella (UAT)

Gentilmente, potete fornire le informazioni richieste a cons.BuosoEdoardo@sia.eu, mettendo in Cc TeamCentroStella@sia.eu

Grazie

**Comment by DenisaBraho** [comment]
Buongiorno ,

come descritto via mail, Il disallineamento sembrerebbe essere stato causato da un intervento di bonifica avvenuto in quel periodo in UAT.Per far rielaborare correttamente i flussi correttamente (UAT), proporrei di procedere nel modo seguente s possibile:

1) Potreste fornire lo stato di attivazione (se possibile anche la data di ultima disattivazione e di ultima attivazione) previsto per gli strumenti interessati dal flusso del 29/01 e 30/01 nei giorni di interesse?

2) Potreste fornire anche la data di attivazione (accetazione T&C) dei CF associati a tali strumenti?

3) Avute questi dati, potremmo ripristinare i dati a sistema e quindi far risottemere il file. Vi daremo riscontro ad operazione avvenuta.

A disposizione per ulteriori chiarimenti
