### ISSUE TITLE
Issuer Integration Telepass/TelepassPay - Card type payment instrument enrolment

### ISSUE THREAD

**Issue by Matteo-tlp** [pagopa/issuer_integration#166]
Ciao,

durante l'incontro tecnico del 18/01 c'è stato indicato di utilizzare la seguente API **/bpd/hb/payment-instruments/card** per l'enrolment dei metodi di pagamento Telepass/TelepassPay in quanto considerata una funzionalità generica di "**payment instrument enrolment**".

La natura dei metodi di pagamento elettronici Telepass e TelepassPay differisce però dal contesto delle carte. Volevamo per questo motivo chiedervi prima di tutto un riscontro sulla struttura dei campi della request che abbiamo ipotizzato, e come seconda cosa se è possibile censire dei valori ad HOC per quei campi come **brand** o **type** per i quali non abbiamo trovato un valore disponibile che fa al caso nostro.

```
{
"id": "750000001", // può non essere cifrato? Rappresenta il codice contratto di Telepass/TPay
"fiscalCode": "FRNFNC80A01D612R",
"expireYear": 0, // non abbiamo un anno di scadenza
"expireMonth": null, // e nemmeno un mese
"issuerAbiCode": null, // soltanto TPay ha un codice abi. Cosa possiamo utilizzare per telepass?
"brand": "Telepass/TPay", // possiamo prevedere due nuovi valori per Telepass e per TelepassPay?
"holder": "Franco Franchi",
"type": null, // è necessario censire un nuovo tipo di pagamento?
"channel": null, // sembra debba essere valorizzato con il codice abi. Come sopra, abbiamo un abi solo per TelepassPay. Che valore utilizziamo per Telepass?
"tokenPanList": [], // possiamo lasciare vuoto?
"PAR": null // cos'è il Payment Account Reference? Possiamo lasciarlo vuoto?
}

```

Grazie

**Comment by DenisaBraho** [comment]
ciao, stiamo ultimando le analisi e gli approfondimenti necessari in merito alla issue in questione. A breve forniremo una risposta.

**Comment by DenisaBraho** [comment]
Ciao,
perdonate il ritardo nel rispondere.
 
La soluzione per l'enrolment per telepass/tpay è stata consolidata e l'API da utilizzare è quella relativa all'enrolment di "OTHER payment instruments" , i dettagli della quale sono presenti nell'IA:  https://github.com/pagopa/issuer_integration/blob/master/ops_resources/Issuer%20Interface%20Agreement_v4_Eng_(Additions%20Post%20Release).pdf nel paragrafo (1.1.3.4) 

Rimaniamo a disposizione per ulteriori chiarimenti
Saluti
