### ISSUE TITLE
Mancato aggiornamento posizione in produzione

### ISSUE THREAD

**Issue by BrignoliSIA** [pagopa/issuer_integration#167]
Ciao,

ci è arrivata una segnalazione di un utente che ha effettuato un'operazione in produzione in data 20/01 ma che non se la ritrova ancora caricata sul cash back.
Abbiamo verificato e l'operazione è stata inserita all'interno del flusso acquiring creato in data 21/01.
I dettagli dell'operazione sono i seguenti:

BPAY1 | 0 | 8 | 3e9679cc49331c29169fc0a9f96a363eb76662987ad2c11b3cda52e45030fb826813f143c312a4aad67408d9332eae005ccd523fca3b595e39e61b0c4ada42dc52bc15b8215591f8d39c45f4121a6f2db168f13eaeaf8482bc0cf2b55f1fa38eeb684fb5bdd275253e145889a04929185d17be09728d448d1df9e8eeaa8ab4739171be52d8c18296adc6300de8277d37aa0328c12d15a567bd5eebc708657d1815d76dbb64d31371d62b9c03ff644134faa19f4342d3efdf0b7779329babff9d610be1938ab5d8b81e3f19e9bc80d93172d2e5a49b6b6e516d7126c5b898488f6c22b29fb05a8d96f304f14b5a67976c12d3fb37522cf1cd5c75f3e0e0e9e327 | 2021-01-20T18:42:32.031+01:00 | P2B0003P621001511902064 | P2B0003P621001511902064 | 8232 | 978 | 3069 | CL173PV | 10029 | 5034 | 5411
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Potete cortesemente verificare e farci sapere?

Tks
Vittorio

**Comment by DenisaBraho** [comment]
Ciao Vittorio,
verifichiamo e vi facciamo sapere.
Tuttavia precisiamo che per le segnalazioni di questo tipo, il canale da utilizzare è ServiceNow.
Grazie

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo analizzato la vostra segnalazione ma per fornirvi una risposta ci servirebbe il codice fiscale dell'utente (se disponibile) o in altenativa hpan (non pgpizzato) dello strumento di pagamento e id_trx_acquirer della transazione mancante

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo analizzato la vostra segnalazione ma per fornirvi una risposta ci servirebbe il codice fiscale dell'utente (se disponibile) e id_trx_acquirer della transazione mancante

**Comment by DenisaBraho** [comment]
Ciao Vittorio,
ci servirebbe il CF utente in modo da controllare il motivo del eventuale scarto/non caricamento della transazione in quanto potrebbe essere legato anche ad un recesso cittadino oppure disattivazione strumento.
Grazie

**Comment by BrignoliSIA** [comment]
Ciao,

il CF noi non lo abbiamo in chiaro e ci risulta un po' difficile recuperarlo ma nei dettagli che vi abbiamo inviato (nelle segnalazioni sopra riportate) è presente l'hashpan e l'id della transazione (P2B0003P621001511902064).
Non sono sufficienti?

Tks
Vittorio

**Comment by BrignoliSIA** [comment]
Nel frattempo cmq abbiamo chiesto per questa casistica particolare il CF direttamente all'utente.

Eccolo
DDTDVD71T13F205Z
 
Davide Diodato

Fateci sapere
Tks
Vittorio

**Comment by DenisaBraho** [comment]
Ciao Vittorio,

la transazione effettivamente è stata inviata verso CentroStella ma è stata scartata perche ha una data trx del 20/01 e la carta utilizzata dall'utente è stata enrollata proprio nella stessa data. Le transazioni per poter essere conteggiate su BPD devono avere una data transazione successiva alla data di enrolment (data T+1). Per tale motivo, solo le transazioni effettuate dal 21/01 in poi verranno conteggiate correttamente.

Saluti
