### ISSUE TITLE
Acquirer Integration Telepass/TelepassPay - Fields in the Standard PagoPA Flow

### ISSUE THREAD

**Issue by Matteo-tlp** [pagopa/issuer_integration#168]
Ciao,

faccio riferimento alla Issue precedentemente aperta per la parte di Issuer Integration https://github.com/pagopa/issuer_integration/issues/166, per chiedervi chiarimenti anche per la parte relativa la processo di acquiring.

Nello specifico vorremmo capire come valorizzare alcuni dei campi del CSV contente l'elenco delle transazioni che deve essere fornito in ingresso al processo batch PagoPA. I campi in questione sono:

- **acquirer_code:** soltanto TPay ha un codice abi. Cosa possiamo utilizzare per telepass?
- **circuit_type:** possiamo prevedere due nuovi valori per Telepass e per TelepassPay? Magari potremmo utilizzare i valori che verranno censiti per il campo brand dell'API **/bpd/hb/payment-instruments/card** di payment instrument enrolment (https://github.com/pagopa/issuer_integration/issues/166).
- **acquirer_id:** quali valori suggerite di utilizzare per Telepass e per TelepassPay?
- **merchant_id:** potrebbe identificare il partner a cui telepass/TelepassPay si appoggia per offrire il servizio. Va fornito un codice o una sorta di descrizione parlante?
- **terminal_id:** si pensava di utilizzare un unico valore virtuale, potrebbe andare bene?
- **bank_identification_number (BIN):** cosa si può utilizare per Telepass e per TelepassPay?
- **MCC:** cosa si può utilizare per Telepass e per TelepassPay?

Grazie

**Comment by DenisaBraho** [comment]
Ciao, 
analizziamo la richiesta e vi forniamo un riscontro appena possibile. 

Per le eventuali nuove richieste lato Acquiring, per garantire una migliore gestione segnalazioni/domande, il canale da usare rimane sempre github, ma suggeriamo di procedere con la apertura delle issue sulla repository dedicata: https://github.com/pagopa/rtd-ms-transaction-filter/issues

Grazie.
Vi aggiorniamo appena possibile
