### ISSUE TITLE
(Swagger) GET /bpd/hb/payment-instruments/{id}   - Schema mancante

### ISSUE THREAD

**Issue by wallaroo** [pagopa/issuer_integration#17]
nel file openapi [bpd-hb-payment-instruments-api.yaml](https://github.com/pagopa/issuer_integration/blob/master/ops_resources/swagger/bpd-hb-payment-instruments-api.yaml)
non è presente lo schema per il content della response '200'

**Comment by daniloMessinaSia** [comment]
Buongiorno,
è stata caricata una nuova versione con il content richiesto
