### ISSUE TITLE
Bpay - UAT- 404- CF non censito

### ISSUE THREAD

**Issue by macorighvanessa** [pagopa/issuer_integration#171]
[Vanessa_20210212_UAT_Cedacri.log](https://github.com/pagopa/issuer_integration/files/5982061/Vanessa_20210212_UAT_Cedacri.log)

[Vanessa_20210215_UAT_Cedacri.log](https://github.com/pagopa/issuer_integration/files/5982472/Vanessa_20210215_UAT_Cedacri.log)

Ciao,
Per due utenze riscontriamo un ko 404 
ES. La seconda chiamata ( ab30a3f6c7e747e99d597a7d07931615 ) verso il servizio PagoPa va in ko 404 . probabilmente a causa di codice fiscale non censito.

potete aiutarmi? 
Grazie
Vanessa

**Comment by daniloMessinaSia** [comment]
Buongiorno,
se l'errore rilevato è un 404 in fase di GET sullo stato dello strumento di pagamento, è probabile che lo stesso non sia stato censito (richiamando il metodo PUT).
Potreste cortesemente verificare di aver effettuato l'enrollment sullo strumento indicato?

In caso dovesse persistere, potreste fornirci il CF dell'utente per effettuare ulteriori verifiche?

Grazie

**Comment by macorighvanessa** [comment]
Fornisco CF
SGRGLE91M52L750U
GFNSVT81E18A783M

**Comment by alecastagno** [comment]
Ciao Vanessa,
i CF che ci hai fornito non sono presenti nei nostri sistemi. 
È possibile che non sia stato fatto l'enrollment degli utenti in questione?
Ti ricordo che è possibile effettuare il censimento richiamando l'API di "Accepting T&C from H/M Banking" come descritto nella documentazione [https://github.com/pagopa/issuer_integration/blob/master/ops_resources/Issuer%20Interface%20Agreement_v4_Eng_(Additions%20Post%20Release).pdf](url).

Ciao
Alessandro

**Comment by DenisaBraho** [comment]
Ciao, a seguito della risposta fornita, procediamo con la chiusura issue. Qualora ci fossero ancora dei problemi o dubbi in merito a tale servizio, vi chiediamo di procedere gentilmente con la riapertura issue / apertura di una nuova su github. 
Grazie
