### ISSUE TITLE
UAT - CashBack PagoPA - Inquiry con status differenti

### ISSUE THREAD

**Issue by MarafinoSIA** [pagopa/issuer_integration#172]
In UAT, per l’idUtente 5704U3240213412 attivo dal 09/11/2020

•	CF -> MRFRNT80A41D612W
•	hpan 
5b5727c4168dc56f02d8e8437181848cbba5e16a48463ba4a7b0e8175eeb383d110c00fc20676722c0d0ee65c5f24123fc7607ccd0455ef422dde882ebc89732297bdc2711a69900fe5c066dbcd402ecde63730896d6002997ae30b004a8adf4cad7fd80291ef01ddaae5a75886962cb05889df5619d59f72b619adf49b67c419f41e3b4226d8cea3eaa655bae9f64c75a76f26fc430246aab3ddab9267807ceb132bde759355f4619dd55dd2ef0f3d90f7127bba62d5cd469065e2e8d14b6521b71d3a75365c75c0c95c86e3719ffb17270017b854147d042ce0b987f0ce428f53677db5e627be3d8ddc1ac0e91b745ce582e0c73ddb11ce1a49644e9099e0d
 
 Riscontriamo quanto segue: 
•	dal 29/01 al 01/02 l’utente risultava attivo come da log sotto in azzurro con stato Active, e poi non è stato più disattivato
•	dal 11/2 riscontro invece per la stessa utenza stato Inactive dal 09/12 come da log sotto in nero 

In allegato i LOG. 
[LOG idUtente 5704U3240213412.docx](https://github.com/pagopa/issuer_integration/files/5983075/LOG.idUtente.5704U3240213412.docx)

Cortesemente è possibile verificare la causa di Inquiry con status differenti? 

Attendiamo Vs. news, grazie. 
Saluti, 
Renata

**********************

INFO  [791269b1-42e6-4cd3-aa45-0405e300c9fb][ba5fb99c-6b59-4071-be51-c871f4b2aab0][b9790db68d5f43f6bde76a09aeae3721][89034][05704] 2021-02-01 12:07:45,567      AbstractRestClient(?: ?)        Send GET request:
ID: 92c327f2-df2b-4288-903d-7fb7580dbe62
Endpoint: https://test.cstar.pagopa.it/bpd/hb/payment-instruments/bpay?id=5b5727c4168dc56f02d8e8437181848cbba5e16a48463ba4a7b0e8175eeb383d110c00fc20676722c0d0ee65c5f24123fc7607ccd0455ef422dde882ebc89732297bdc2711a69900fe5c066dbcd402ecde63730896d6002997ae30b004a8adf4cad7fd80291ef01ddaae5a75886962cb05889df5619d59f72b619adf49b67c419f41e3b4226d8cea3eaa655bae9f64c75a76f26fc430246aab3ddab9267807ceb132bde759355f4619dd55dd2ef0f3d90f7127bba62d5cd469065e2e8d14b6521b71d3a75365c75c0c95c86e3719ffb17270017b854147d042ce0b987f0ce428f53677db5e627be3d8ddc1ac0e91b745ce582e0c73ddb11ce1a49644e9099e0d
INFO  [791269b1-42e6-4cd3-aa45-0405e300c9fb][ba5fb99c-6b59-4071-be51-c871f4b2aab0][b9790db68d5f43f6bde76a09aeae3721][89034][05704] 2021-02-01 12:07:45,833      AbstractRestClient(?: ?)        Received GET response:
ID: 92c327f2-df2b-4288-903d-7fb7580dbe62
HttpResponseProxy{HTTP/1.1 200 OK [Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Transfer-Encoding: chunked, Content-Type: application/json;charset=UTF-8, Expires: 0, X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, X-Frame-Options: DENY, Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4, Date: Mon, 01 Feb 2021 11:07:45 GMT]}
Content object:
{"hpan":"9f20fb301937db030e410e55431437380982197bea5544def6375d9213c375fc","fiscalCode":"MRFRNT80A41D612W","activationDate":"2020-11-09T16:56:06.748+01:00","Status":"ACTIVE"}
INFO  [791269b1-42e6-4cd3-aa45-0405e300c9fb][ba5fb99c-6b59-4071-be51-c871f4b2aab0][b9790db68d5f43f6bde76a09aeae3721][89034][05704] 2021-02-01 12:07:45,835      AbstractRestClient(?: ?)        Response Java: <it.sempla.p2p.engine.backend.model.integration.rest.pagoPa.ResponseStatusStrumento><hpan>9f20fb301937db030e410e55431437380982197bea5544def6375d9213c375fc</hpan><fiscalCode>MRFRNT80A41D612W</fiscalCode><Status>ACTIVE</Status><activationDate>2020-11-09 15:56:06.748 UTC</activationDate></it.sempla.p2p.engine.backend.model.integration.rest.pagoPa.ResponseStatusStrumento>
p2pbesv01

**********************
INFO  [a166432e-8894-436f-ac45-5d750b0f82dd][655eea1a-b5e0-47f7-8be1-0ab386a43a45][136948544625453292ec493d2d0d9f2c][89034][05704] 2021-02-11 17:18:09,613      AbstractRestClient(?: ?)        Send GET request:
ID: e1b20015-971d-4446-ab93-e6f5809579d2
Endpoint: https://test.cstar.pagopa.it/bpd/hb/payment-instruments/bpay?id=5b5727c4168dc56f02d8e8437181848cbba5e16a48463ba4a7b0e8175eeb383d110c00fc20676722c0d0ee65c5f24123fc7607ccd0455ef422dde882ebc89732297bdc2711a69900fe5c066dbcd402ecde63730896d6002997ae30b004a8adf4cad7fd80291ef01ddaae5a75886962cb05889df5619d59f72b619adf49b67c419f41e3b4226d8cea3eaa655bae9f64c75a76f26fc430246aab3ddab9267807ceb132bde759355f4619dd55dd2ef0f3d90f7127bba62d5cd469065e2e8d14b6521b71d3a75365c75c0c95c86e3719ffb17270017b854147d042ce0b987f0ce428f53677db5e627be3d8ddc1ac0e91b745ce582e0c73ddb11ce1a49644e9099e0d
INFO  [a166432e-8894-436f-ac45-5d750b0f82dd][655eea1a-b5e0-47f7-8be1-0ab386a43a45][136948544625453292ec493d2d0d9f2c][89034][05704] 2021-02-11 17:18:09,860      AbstractRestClient(?: ?)        Received GET response:
ID: e1b20015-971d-4446-ab93-e6f5809579d2
HttpResponseProxy{HTTP/1.1 200 OK [Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Transfer-Encoding: chunked, Content-Type: application/json;charset=UTF-8, Expires: 0, X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, X-Frame-Options: DENY, Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4, Date: Thu, 11 Feb 2021 16:18:09 GMT]}
Content object:
{"hpan":"9f20fb301937db030e410e55431437380982197bea5544def6375d9213c375fc","fiscalCode":"MRFRNT80A41D612W","activationDate":"2020-11-09T16:56:06.748+01:00","deactivationDate":"2020-12-09T16:56:06+01:00","Status":"INACTIVE"}
INFO  [a166432e-8894-436f-ac45-5d750b0f82dd][655eea1a-b5e0-47f7-8be1-0ab386a43a45][136948544625453292ec493d2d0d9f2c][89034][05704] 2021-02-11 17:18:09,863      AbstractRestClient(?: ?)        Response Java: <it.sempla.p2p.engine.backend.model.integration.rest.pagoPa.ResponseStatusStrumento><hpan>9f20fb301937db030e410e55431437380982197bea5544def6375d9213c375fc</hpan><fiscalCode>MRFRNT80A41D612W</fiscalCode><Status>INACTIVE</Status><activationDate>2020-11-09 15:56:06.748 UTC</activationDate><deactivationDate>2020-12-09 15:56:06.0 UTC</deactivationDate></it.sempla.p2p.engine.backend.model.integration.rest.pagoPa.ResponseStatusStrumento>

**********************

**Comment by daniloMessinaSia** [comment]
Ciao,
Da verifiche effettuate, lo stato degli strumenti di pagamento è mutato poichè sono state effettuate bonifiche massive per riallineare la base dati con quella della componente Payment Manager pertanto abbiamo verificato che anche i vostri strumenti di pagamento sono rientrati in tale operazione.

Gli interventi di bonifica si sono conclusi nei giorni scorsi pertanto non dovrebbero più presentarsi tali incongruenze.

Buona serata
