### ISSUE TITLE
Identificazione rimborsi cashback di stato

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#173]
Dal punto di vista di una banca issuer, esiste una combinazione di filtri che consente di sapere con certezza che tot bonifici sono relativi ai rimborsi per il cashback di stato?
Ad esempio: ogni volta che un utente riceve un bonifico con emittente "Consap S.p.A." e causale "Rimborso cashback di stato", tale bonifico è di sicuro relativo al cashback di stato.
Ecco ci servirebbe capire una combinazione di tale tipo che ci dia la certezza che quel bonifico è relativo al cashback di stato

**Comment by DenisaBraho** [comment]
Come piattaforma CentroStella noi inviamo verso Consap le seguenti informazioni:
uniqueId (identificativo pagamento); Cashback di Stato (tipologia vincita) ; data inizio e data fine periodo (relative al periodo di riferimento)  che sono presenti nella causale del bonifico: template: **"uniqueId - Cashback di Stato - dal <data> al <data>"**

Dovrebbe essere presente anche presente l'indicazione dell' ordinante "CONSAP CONCESSIONARIA SERVIZI ASSIC" nella descrizione bonifico.

Saluti
