### ISSUE TITLE
Errore payment-instrument/v2 - UAT 

### ISSUE THREAD

**Issue by albertomarini1992** [pagopa/issuer_integration#175]
Buon pomeriggio, 

invocando le nuove API payment-instrument/v2 in ambiente di UAT, per il recupero stato [GET] e la cancellazione [DELETE] di una carta, stiamo ottenendo errore "404 Wallet Service Error".

Potreste verificarne il motivo? 
Ieri il servizio rispondeva con errore 500 probabilmente causato dalla valorizzazione errata del campo id tra gli header.

Grazie
Saluti
Alberto

**Comment by daniloMessinaSia** [comment]
Buongiorno,
come da comunicazione esterna, purtroppo l'api non è ancora disponibile in ambiente di UAT.
Verrà comunicato tramite canale mail quando sarà possibile procedere con i test.

Buona giornata

**Comment by albertomarini1992** [comment]
Buonasera, 

ci hanno confermato il rilascio delle API ma otteniamo ancora errore. 
Potreste confermarci la data di rilascio in SIT o UAT?
Grazie
