### ISSUE TITLE
ATM Poste Italiane, integrazione API GTW, PaymentInstruments errore 400 ErrorPM

### ISSUE THREAD

**Issue by smAPIgtw** [pagopa/issuer_integration#176]
Buonasera,
invocando il seguente servizio:

PUT https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card

riceviamo un errore STATUS 400 ErrorPM con body vuoto, in allegato request e response di dettaglio

Potreste verificare?

[request response payment instruments API GTW.txt](https://github.com/pagopa/issuer_integration/files/6084426/request.response.payment.instruments.API.GTW.txt)

**Comment by smAPIgtw** [comment]
Buongiorno, 
ci potreste dare un ritorno sulla richiesta?

**Comment by DenisaBraho** [comment]
Ciao, 
abbiamo notato che nella chiamata sono presenti degli errori.
In particolare, il nome del campo "expirymonth" inserito nella chiamata è censito come **exprireMonth**. Inoltre, il mese deve contenere 2 char mentre l'anno 4 char.
Potreste riprovare?
Saluti
