### ISSUE TITLE
ATM Poste Italiane, integrazione API GTW, Citizen 500 internal server error

### ISSUE THREAD

**Issue by smAPIgtw** [pagopa/issuer_integration#178]
Buonasera,
invocando il seguente servizio

DELETE https://test.cstar.pagopa.it/bpd/hb/citizens/VTLLGU75R12H501F
in data 03/09 16:24:28.380

otteniamo il seguente errore

{
    "statusCode": 500,
    "message": "Internal server error",
    "activityId": "e106603f-aa31-46a7-8752-35532987d182"
}

Ci potreste indicare da cosa dipende?

**Comment by smAPIgtw** [comment]
La problematica persiste, potreste dare seguito alla richiesta?

**Comment by DenisaBraho** [comment]
Ciao,

abbiamo notato che manca il parameter channel nel body, Potreste riprovare?

Saluti

**Comment by smAPIgtw** [comment]
buonasera,
nonostante il client ha riprovato aggiungendo il channel, l'errore si ripresenta, di seguito i dettagli:

DELETE /citizen/VTLLGU75R12H501F HTTP/1.1
Content-Type: application/json
x-request-id: c84e525e-a24a-4600-a397-e5801e5cad7d
Content-Length: 26
{
"channel": "07601"
}
HTTP/1.1 500 Internal Server Error
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: application/json
Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4
Date: Thu, 11 Mar 2021 11:13:52 GMT
X-Global-Transaction-ID: 276539326049fb7001c24961
X-RateLimit-Limit: name=default,100;
X-RateLimit-Remaining: name=default,99;
{ "statusCode": 500, "message": "Internal server error", "activityId": "d6347520-924f-4c72-b3e1-6fab257fbfc2" }

**Comment by DenisaBraho** [comment]
Ciao, 
non riusciamo a replicare l'errore. Effettuando la stessa chiamata, aggiungendo la chiave di sottoscrizione nell'header e inserendo nel body;  {"channel": "07601" } lato CentroStella la chiamata va a buon fine. Potreste riprovare?

**Comment by smAPIgtw** [comment]
Ciao,
appena abbiamo un ritorno dal client, daremo un riscontro

**Comment by smAPIgtw** [comment]
Buonasera,
il client ci fa sapere che il servizio restituisce ancora errore, di seguito il dettaglio:

request
DELETE /citizen/VTLLGU75R12H501F HTTP/1.1
x-request-id: 4a7b098f-f88b-4586-9c3d-1fcfe6689502
Ocp-Apim-Subscription-Key: RIMOSSO
x-ibm-client-secret: RIMOSSO
x-ibm-client-id: d974b7b16a32e6a7afce8348e1e9f5bd
Content-Type: application/json
Host: apit.gp.posteitaliane.it
Content-Length: 26
{
"channel": "07601"
}

response
HTTP/1.1 500 Internal Server Error
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: application/json
Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4
Date: Tue, 23 Mar 2021 12:56:35 GMT
X-Global-Transaction-ID: 276539326059e583004b7497
X-RateLimit-Limit: name=default,100;
X-RateLimit-Remaining: name=default,93;
{ "statusCode": 500, "message": "Internal server error", "activityId": "fecb3b9c-ca07-4b7f-850a-4056541048c2" }

Potete verificare?

**Comment by smAPIgtw** [comment]
Buonasera,
non abbiamo avuto più ritorno in merito alla richiesta precedente, potreste darci un riscontro?

saluti

**Comment by DenisaBraho** [comment]
Ciao, abbiamo riprovato nuovamente la chiamata ma lato centrostella la chiamata funziona. Riscontrato tale errore solo per la chiamata di delete o anche per altre chiamate?

**Comment by smAPIgtw** [comment]
Buonasera,
L’errore 500 persiste solo sulla DELETE. la prova è stata fatta alle 15:16 di oggi 20/04 con lo stesso esito. Dal centro stella fate la stessa chiamata o state provando con un altro CF e body diverso? Di seguito i dettagli

DELETE /citizen/VTLLGU75R12H501F

{
    "statusCode": 500,
    "message": "Internal server error",
    "activityId": "0d481eeb-2a4f-4f3b-98f6-09e6fb5acdac"
}

Potete verificare?

**Comment by DenisaBraho** [comment]
Ciao,
possiamo provare ad effettuare una sessione di test congiunta? Proponiamo di fissare una call per venerdi alle 12.00
In attesa di un riscontro
Saluti

**Comment by smAPIgtw** [comment]
Ciao,
mi potresti indicare quali persone possiamo coinvolgere nel meeting?
