### ISSUE TITLE
SIT - Problema bloccante per invocazione API

### ISSUE THREAD

**Issue by amarano-github** [pagopa/issuer_integration#179]
Ciao,
stiamo riscontrando problemi nel provare a richiedere l'impostazione/l'aggiornamento di un nuovo IBAN rispetto ad una specifica utenza.
La response che otteniamo sembrerebbe essere legata alla non accettazione del certificato. Qui di seguito, quello che riceviamo:

"HTTP/1.1 403 Certificate not verified: 518C24C9C2DF4DE9BE1728BFA7142C55714AE80F"

La nostra request è stata la seguente:
PATCH https://bpd-dev.azure-api.net/bpd/hb/citizens/BTTLSN80C01L219B
x-request-id: 5b87372e-eaaa-4a6f-9d4b-b601ea6d2793
{"id":"BTTLSN80C01L219B","accountHolderCF":"BTTLSN80C01L219B","accountHolderName":"Alessandro","accountHolderSurname":"Battista","payoffInstr":"IT89V3602476950000007837894","payoffInstrType":"IBAN"}

Abbiamo verificato se il problema fosse legato alla specifica API PATCH /bpd/hb/citizens/{fiscalCode}. Otteniamo purtroppo lo stesso codice di errore anche all'invocazione di altri servizi come l'accettazione dei termini o lo stato dell'utenza precedentemente censita.

Il problema quindi sembra bloccante, essendo coinvolto totalmente l'ambiente di test.

Potreste cortesemente verificare per poi avere un riscontro?

Grazie in anticipo.

**Comment by manuel-alongi-sia** [comment]
Buongiorno, il problema dovrebbe essere risolto.
Potete riprovare per favore e farci sapere l'esito?

grazie

**Comment by amarano-github** [comment]
Buongiorno @manuel-alongi-sia,
grazie per il riscontro.

Confermo che è stato risolto il problema.

Grazie ancora per il supporto.
