### ISSUE TITLE
Recupero informazioni clienti

### ISSUE THREAD

**Issue by luca1oo** [pagopa/issuer_integration#18]
Ciao,
Al fine di ottimizzare i processi di sottoscrizioni e/o recuperare informazioni dei clienti è possibile eseguire chiamate in batch ai vostri sistemi oppure prevedete di scaricare periodicamente file con le informazioni di pertinenza delle singole banche?
Ci sono limitazioni di chiamate e/o fasce orarie consigliate?
Grazie

**Comment by menottistefano** [comment]
le API possono esser invocate solo su azione esplicita dell'utente che opera sui touch point messi a disposizione dell'issuer dello strumento di pagamento o dall'App IO.  non sono previste azioni "batch" massive startate dall'issuer per recuperare in modo massivo informazioni. le API non possono esser utilizzate per questi scopi

**Comment by luca1oo** [comment]
La necessità di eseguire chiamate batch nasce dall'esigenza di gestire il lifecycle della carta di pagamento iscritta tramite nostro canale issuer.
Come verranno gestiti i rinnovi/sostituzioni per le carte iscritte già al programma? Il cliente dovrà abilitare nuovamente la carta al programma?

**Comment by menottistefano** [comment]
esatto. il cittadino in caso di nuovi strumenti di pagamento dovrà registrarli volontariamente. in caso di rinnovo (stesso PAN) non c'è bisogno invece che effettui nuove azioni.

**Comment by Carrettoni** [comment]
Visto che viene passata anche la data scadenza, in che modo andrete ad aggiornarla? Ci sono casi di rinnovi anticipati per cui la scadenza cambia prima del termine validità

**Comment by DenisaBraho** [comment]
Ciao,

in merito alla gestione delle carte, il processo prevede che sia il cittadino a gestire le proprie carte. Quindi in caso di carta scaduta, l'utente potrà procedere alla sua rimozione. 
Nel caso in cui la carta si rinnovi mantendendo lo stesso PAN, il processo funzionerà correttamente in quanto verranno considerate le transazioni effettuate con la "nuova" carta, senza necessità di effettuare nuovamente l'enrollment. Tuttavia, in questo caso sarà visibile all'utente nel proprio portale/app come data scadenza quella precedente inserita in fase di enrollment. In questi casi, l'utente potrà comunque disattivare/cancellare la carta precedente e inserire la "nuova".
A disposizione per ulteriori chiarimenti 
Saluti
