### ISSUE TITLE
PROD - errore PATCH

### ISSUE THREAD

**Issue by albertomarini1992** [pagopa/issuer_integration#180]
Buonasera, 
abbiamo notato un errore invocando la chiamata PATCH per l'inserimento del codice IBAN in ambiente di produzione. 

L'errore ricevuto è il seguente: 
{
"status":400,
"message":"invalid.body.error;accountholdername;invaid utf-8 middle byte 0x22;unknown",
"validationStatus":null
}

Il campo accountHolderName passato in input è NICOLÒ

Potreste fornirci dettagli relativi all'errore?
Saluti
Alberto

**Comment by DenisaBraho** [comment]
Ciao,
ci potreste indicare il body della chiamata?
Grazie

**Comment by albertomarini1992** [comment]
Ciao, 
sono dati di produzione. E' possibile comunicarvi il body via mail e non pubblicamente tramite questo canale?
Grazie

**Comment by DenisaBraho** [comment]
Ciao Alberto,
si, per i dati di produzione il canale corretto è quello via mail. L'indirizzo a cui scrivere è: TeamCentroStella@sia.eu
indicando la issue github e le informazioni richieste.
Grazie,
Saluti

**Comment by albertomarini1992** [comment]
Ciao, 
va bene. 
Grazie

**Comment by daniloMessinaSia** [comment]
Buonasera,
sui nostri ambienti di test la chiamata, utilizzando il body fornitoci, risulta andare a buon fine, 
modificando i campi oscurati.

Vi chiederemmo di riprovare a fornirci riscontro,
Grazie

**Comment by albertomarini1992** [comment]
Buonasera, 
riuscite a recuperare l'esatta request andata in errore dai vostri log? 
L'errore l'abbiamo ottenuto in produzione dal servizio richiamato  quindi non riusciamo a chiedere un nuovo test al cliente

Grazie
Alberto

**Comment by DenisaBraho** [comment]
Ciao, 
purtroppo non riusciamo a recuperare le request.
Qualora si dovesse presentare un errore analogo a quello indicato, vi preghiamo di aprire una nuova issue. Grazie
