### ISSUE TITLE
Disattivazione carta - UAT - v2

### ISSUE THREAD

**Issue by albertomarini1992** [pagopa/issuer_integration#181]
Buon pomeriggio, 

Stiamo effettuando in ambiente di UAT alcuni test di recupero stato carta e disattivazione carta richiamando le api payment-instruments/v2.
Dopo aver recuperato lo stato di una carta attiva, con risposta: 
{
    "hpan": "a7244b705f3a74f6138d75d741d2cc6dcf45040ce6878e13b6ac5b462c70d178",
    "fiscalCode": "PDV****05E",
    "activationDate": "2021-02-17T12:16:26.81+01:00",
    "deactivationDate": null,
    "Status": "ACTIVE"
}
Abbiamo provato la disattivazione con successo. 
La nuova risposta al recupero stato carta, però, ha aggiornato oltre alla deactivationDate anche il valore della activationDate: 
{
    "hpan": "a7244b705f3a74f6138d75d741d2cc6dcf45040ce6878e13b6ac5b462c70d178",
    "fiscalCode": "PDV****05E",
    "activationDate": "2021-03-15T16:16:20.088+01:00",
    "deactivationDate": "2021-03-15T16:16:20.074+01:00",
    "Status": "INACTIVE"
} 

E' corretto questo comportamento? 

Grazie
Saluti
Alberto

**Comment by DenisaBraho** [comment]
Ciao Alberto,
grazie della segnalazione. Confermiamo che il comportamento non è corretto e stiamo pianificando una fix in merito.
Saluti
