### ISSUE TITLE
gestione conti tecnici

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#182]
Salve, 

ci potreste confermare che solo i seguenti servizi hanno impatti sulla nuova gestione dei conti tecnici? 
- 1.1.2 Setting/modifying IBAN from H/M Banking
- 1.1.5 Citizen H/M Banking Status

Inoltre potreste per favore indicarci il motivo della modifica dei nuovi servizi elencati di seguito: 
-	par. 1.1.4 Accepting T&Cs from H/M Banking
-	par. 1.1.6 H/M Banking Payment Instrument Status	
-	par. 1.1.7 H/M Banking Payment Instrument deactivation
-	par. 1.1.9 Retrieving ranking
-	par. 1.1.10 Retrieving cashback total
-	par. 1.1.11 Unsubscribe Citizen

Grazie mille 

Nicola

**Comment by daniloMessinaSia** [comment]
Buongiorno,
vi confermo che relativamente ai conti tecnici verranno impattati solo i servizi indicati (1.1.2-1.1.5).

La motivazione dietro la modifica degli altri servizi con la creazione di una versione 2 delle Api è relativa a temi di sicurezza.
Come descritto nel documento di IA, è stato effettuato lo spostamento (e in alcuni casi la cifratura PGP, vedi 1.1.6-1.1.7) di alcuni campi dall'URI agli Header/Request body delle chiamate.

Buona giornata,
