### ISSUE TITLE
Riconoscimento Movimenti di Accredito Cashback su conto corrente

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#183]
Buongiorno,
Abbiamo notato che i movimenti inerenti all'acccredito del cashback (a termine del concorso) hanno le seguenti caratteristiche:

•	IBAN: **IT73R0100503239000000002636**
•	Ordinante: **CONSAP CONCESSIONARIA SERVIZI ASSIC**
•	Causale: **XXXXXXXXX - Cashback di Stato - dal 08/12/2020 al 31/12/2020**

E' ragionevole ipotizzare che tutti i bonifici relativi all'ottenimento del cashback effettuati ai sottoscrittori del programma del Cashback di Stato arriveranno sempre dall'IBAN: **IT73R0100503239000000002636** ?

**Comment by DenisaBraho** [comment]
Lato CentroStella non abbiamo visibilità sull'iban che l'ordinante sceglie di utilizzare, quindi non riusciamo a confermarvi quanto richiesto sul valore dell'IBAN.
