### ISSUE TITLE
Chiamate API lente in ambiente di test

### ISSUE THREAD

**Issue by daviogg** [pagopa/issuer_integration#184]
Stiamo riscontrando dei rallentamenti sul sistema, 
ad esempio chiamando la seguente API (ma non solo) abbiamo dei tempi di risposta che variano dai 30'' al 1.30' 

GET: https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5573830050385877

Questo sta causando diversi timeout sui nostri ambienti di test.

**Comment by daniloMessinaSia** [comment]
Buongiorno,
potreste riprovare e darci riscontro?

Grazie

**Comment by daviogg** [comment]
Buongiorno, purtrobbo risulta ancora lento

**Comment by daniloMessinaSia** [comment]
Buongiorno,
lato nostro, in ambiente di uat, non abbiamo evidenza di questi rallentamenti.
anche effettuando la vostra chiamata di esempio, otteniamo risposta entro 1".

riuscite a verificare di non aver problemi lato rete vostra?
Utilizzate un gateway/proxy prima di invocare i nostri servizi?

**Comment by daviogg** [comment]
No nessun proxy, sto provando direttamente da postman

**Comment by daniloMessinaSia** [comment]
Sono in corso verifiche lato rete,
vi aggiorneremo appena avremo riscontro

**Comment by daniloMessinaSia** [comment]
Buongiorno,
potreste riprovare e darci riscontro?

Grazie
