### ISSUE TITLE
Chiamate /v2 lente in ambiente di test uat

### ISSUE THREAD

**Issue by albertomarini1992** [pagopa/issuer_integration#185]
Buon pomeriggio, 
Stiamo riscontrando dei rallentamenti importanti durante le chiamate alle nuove API v2 per il recupero stato carta e cancellazione carta.
Potreste effettuare una verifica? Le chiamate rimangono in attesa anche per alcuni minuti
Questi rallentamenti stanno causando problemi significativi ai test.

Saluti
Alberto

**Comment by daniloMessinaSia** [comment]
Buongiorno,
potreste riprovare e darci riscontro?

Grazie

**Comment by albertomarini1992** [comment]
Buonasera, 
ora il servizio ha ripreso a rispondere anche se con tempistiche superiori ai 10 secondi.
E' una tempistica accettabile lato vostro?
Saluti
Alberto

**Comment by DenisaBraho** [comment]
Sono in corso verifiche lato rete,
vi aggiorneremo appena avremo riscontro

**Comment by daniloMessinaSia** [comment]
Buongiorno,
potreste riprovare e darci riscontro?

Grazie

**Comment by albertomarini1992** [comment]
Buon pomeriggio, 
ora l'API sembra rispondere correttamente in pochi secondi. 

Grazie
Alberto
