### ISSUE TITLE
UAT: PUT /bpd/hb/payment-instruments/card - Status 500 ErrorPM

### ISSUE THREAD

**Issue by lucacerretani** [pagopa/issuer_integration#188]
Buonasera,
effettuando la richiesta al metodo per l'enroll del payment instrument riceviamo un errore 500 con messaggio ErrorPM
potete aiutarci?

**Endpoint:** https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card
**Method:** PUT
**Body:**
{ 
"fiscalCode":"{{fiscalCode}}",
"exprireMonth":"11",
"channel":"01030",
"issuerAbiCode":"01030",
"id":"-----BEGIN PGP MESSAGE-----\nVersion: BCPG v1.52\n\nhQEMA+NENQPn0iNJAQf/Vm0DF+i8WJPFpluYCDolqvgL6cC1mmiQtPfdB918Um9x\n2eoa83X0Zws6KUiTwp9lsr/SIe1Y4q2HiTueDnDzCyIbiyNkVhCIuIRPH6k5O9n0\nC4rzd92afv66L+MwOB4+jcC0/tE1tkpc9K8/rL7wuBx4QzbCU2HeShjN+c7UvoEz\nBe4KwOL+z/GoFjlIli/D/0DgyR7aeJGIKgEwF98HwWJyXoQbjixMgGmrrun1SLjY\nNIBHX+axfBlG91vJjeaE5wB3cbk6B2T7h5qUcF5k8NXcAtW1uLK9hTjNarHfAL0e\nr8WIto2e9zzmHwGtjf+OeTvaTdMbkjLHZu5koh9Lh9JAAW5d67wdDI8xyVVbSVp9\nM79Ok8A2YfJTz5QxQ0zj2xLCUKLGN1h17Al7bPpeDBsktT7thF2z3DojOd84+eTp\nhg==\n=VpTF\n-----END PGP MESSAGE-----\n",
"type":"DEB",
"expireYear":"2022",
"brand":"MAESTRO"
}

Grazie

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo notato che nella chiamata manca il parametro/campo HOLDER. Vi preghiamo di inserire il campo mancante e  riprovare la chiamata.
Saluti

**Comment by lucaallbus** [comment]
Ciao,
valorizzando il campo HOLDER l'attivazione ha funzionato.
Nella documentazione tuttavia il campo risulta NON obbligatorio.

Grazie comunque per il supporto.

**Comment by lucacerretani** [comment]
Ciao,
valorizzando il campo HOLDER l'attivazione ha funzionato.
Nella documentazione tuttavia il campo risulta NON obbligatorio.

Grazie comunque per il supporto.
