### ISSUE TITLE
Data disattivazione su enrollment strumento

### ISSUE THREAD

**Issue by BrignoliSIA** [pagopa/issuer_integration#189]
Buon pomeriggio,

in ambiente di test ci sono delle situazioni di inquiry che ci vanno ko perchè presentano una situazione non gestita.

A fronte di un servizio in stato active ci aspettiamo di ricevere in response solo la data di attivazione ma non quella di disattivazione; in alcuni casi però ci arrivano entrambi e l'app va in crash.

Vi riporto un esempio di ieri:

ESEMPIO DI ANOMALIA (utenza 6220U3407101699 ieri 10.26)

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <ns2:enrollmentCashBackPagoPaResponse xmlns:ns2="http://p2p.sempla.it/srv/pp">
      <return>
        <esito>
          <avvertenza>false</avvertenza>
          <codice>00000</codice>
          <esito>true</esito>
          <guid>a69570f9a2324569a36205bca6884701</guid>
          <messaggio>Esito positivo</messaggio>
        </esito>
        <activationDate>2021-04-07T10:25:43.366+02:00</activationDate>
        <deactivationDate>2021-03-24T10:28:14.273+01:00</deactivationDate>
        <fiscalCode>SGRGLE91M52L750U</fiscalCode>
        <hpan>a97f61adaf753f9c90d68943b6f88fd941b4d4c6c9267666d07746bbee8a0298</hpan>
       <status>ACTIVE</status>
      </return>
    </ns2:enrollmentCashBackPagoPaResponse>
  </soap:Body>
</soap:Envelope>

Potete verificare e farci sapere?

Tks
Vittorio

**Comment by daniloMessinaSia** [comment]
Ciao,
se lo strumento è stato attivatio disattivato e riattivato nuovamente la data di disattivazione arriverà popolata come da processo.

a disposizione,
Ciao
