### ISSUE TITLE
Enrollment strumento di pagamento di tipo Carta - Parametro "Channel"

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#19]
Leggendo la vostra documentazione (in special modo nel documento “Issuer Interface Agreement_v2.pdf”, paragrafo "**1.1.3.1 Enrollment strumento di pagamento di tipo Carta**" non riusciamo a capire come valorizzare il parametro: "channel".

Nello Swagger viene infatti indicato come "_canale che identifica univocamente l'issuer sulla piattaforma_".
Sapreste darci indicazione su come valorizzare tale campo?

**Comment by DenisaBraho** [comment]
Ciao, riportiamo di seguito il dominio previsto per il parametro channel:

1. Enrollment strumento di pagamento di tipo Carta -> corrisponde al codice ABI Issuer
2. Enrollment strumento di pagamento di tipo BancomatPay -> da valorizzare con il valore fisso "BPAY" 
3. Enrollment strumento di pagamento di tipo Satispay -> da valorizzare con il valore fisso "SPAY"

La documentazione "“Issuer Interface Agreement_v2.pdf” è stata aggiornata includendo le indicazioni sulla valorizzazione campo channel. 

A disposizione per ulteriori chiarimenti,
Saluti
