### ISSUE TITLE
 ATM Poste Italiane, integrazione API GTW, Citizen HTTP redirection code 302

### ISSUE THREAD

**Issue by smAPIgtw** [pagopa/issuer_integration#190]
Buonasera,
a seguito della seguente chiamata 

GET https://test.cstar.pagopa.it/bpd/hb/citizens/CLLTMA93C03D810N
al seguente orario  04/12 17:57:25.641

riceviamo il messaggio HTTP response code 302,
potreste verificare?

**Comment by albertomarini1992** [comment]
Buonasera, 

anche noi abbiamo i test bloccati e stiamo riscontrando lo stesso errore in fase di chiamata.

Potreste verificare?
Grazie
Alberto

**Comment by DenisaBraho** [comment]
Ciao, verifichiamo e vi facciamo sapere a stretto giro

**Comment by DenisaBraho** [comment]
Ciao, potreste riprovare e verificare se l'errore si ripresenta?
Grazie

**Comment by smAPIgtw** [comment]
buonasera,
il problema non si ripresenta, potete chiudere la issue
