### ISSUE TITLE
Gestione IBAN tecnico

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#191]
Salve
stiamo effettuando i test di integrazione tra i nostri BE e le API da voi esposte. 

é stata effettuata una prova inviandovi un iban tecnico.  
Impostando a true flagTechnicalAccount , non stanno tornando i campi

- technicalAccountHolder
- issuerCardId	

Di seguito il log:

[INFO] [Thu Apr 15 09:42:32 CEST 2021] BonusPagamentiDigitaliService - modificaImpostazioniIBANEstesa - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/citizens/RSTDNT79P29G793R]
[INFO] [Thu Apr 15 09:44:46 CEST 2021] BonusPagamentiDigitaliService - method modificaImpostazioniIBANEstesa-PATCH - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: a2f4229b-33e0-4661-a3d9-6af693c8a99d, Content-Type: application/json]
[INFO] [Thu Apr 15 09:44:46 CEST 2021] BonusPagamentiDigitaliService - method modificaImpostazioniIBANEstesa-PATCH - REQUEST PAYLOAD - {"technicalAccountHolder":"Posteitaliane s.p.a.","accountHolderSurname":"Rosati","accountHolderCF":"RSTDNT79P29G793R","payoffInstr":"ITxxxx","accountHolderName":"Dante","payoffInstrType":"IBAN","issuerCardId":"0000000012937794"}
2021/04/15 09:44:48:008 CEST [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2021/04/15 09:44:48:029 CEST [DEBUG] RequestAuthCache - Auth cache not set in the context
2021/04/15 09:44:48:038 CEST [DEBUG] BasicHttpClientConnectionManager - Get connection for route {s}->https://test.cstar.pagopa.it:443
2021/04/15 09:44:48:730 CEST [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2021/04/15 09:44:49:950 CEST [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.125:52919<->20.54.178.216:443
2021/04/15 09:44:49:957 CEST [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2021/04/15 09:44:49:987 CEST [DEBUG] wire - http-outgoing-0 >> "PATCH /bpd/hb/citizens/RSTDNT79P29G793R HTTP/1.1[\r][\n]"
2021/04/15 09:44:49:992 CEST [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2021/04/15 09:44:49:998 CEST [DEBUG] wire - http-outgoing-0 >> "x-request-id: a2f4229b-33e0-4661-a3d9-6af693c8a99d[\r][\n]"
2021/04/15 09:44:50:006 CEST [DEBUG] wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
2021/04/15 09:44:50:012 CEST [DEBUG] wire - http-outgoing-0 >> "Content-Length: 228[\r][\n]"
2021/04/15 09:44:50:017 CEST [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2021/04/15 09:44:50:023 CEST [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2021/04/15 09:44:50:027 CEST [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2021/04/15 09:44:50:032 CEST [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2021/04/15 09:44:50:039 CEST [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2021/04/15 09:44:50:043 CEST [DEBUG] wire - http-outgoing-0 >> **"{"technicalAccountHolder":"Posteitaliane s.p.a.","accountHolderSurname":"Rosati","accountHolderCF":"RSTDNT79P29G793R","payoffInstr":"ITxxxx","accountHolderName":"Dante","payoffInstrType":"IBAN","issuerCardId":"0000000012937794"}"**
2021/04/15 09:44:51:180 CEST [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2021/04/15 09:44:51:185 CEST [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
2021/04/15 09:44:51:191 CEST [DEBUG] wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
2021/04/15 09:44:51:197 CEST [DEBUG] wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2021/04/15 09:44:51:202 CEST [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
2021/04/15 09:44:51:208 CEST [DEBUG] wire - http-outgoing-0 << "Expires: 0[\r][\n]"
2021/04/15 09:44:51:213 CEST [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2021/04/15 09:44:51:216 CEST [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2021/04/15 09:44:51:218 CEST [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
2021/04/15 09:44:51:221 CEST [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2021/04/15 09:44:51:224 CEST [DEBUG] wire - http-outgoing-0 << "Date: Thu, 15 Apr 2021 07:44:46 GMT[\r][\n]"
2021/04/15 09:44:51:225 CEST [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2021/04/15 09:44:51:227 CEST [DEBUG] wire - http-outgoing-0 << "19[\r][\n]"
2021/04/15 09:44:51:228 CEST [DEBUG] wire - http-outgoing-0 << "{"validationStatus":"OK"}[\r][\n]"
2021/04/15 09:44:51:230 CEST [DEBUG] wire - http-outgoing-0 << "0[\r][\n]"
2021/04/15 09:44:51:231 CEST [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2021/04/15 09:44:51:307 CEST [DEBUG] BasicHttpClientConnectionManager - Releasing connection 192.168.200.125:52919<->20.54.178.216:443
2021/04/15 09:44:51:308 CEST [DEBUG] BasicHttpClientConnectionManager - Connection can be kept alive indefinitely
[INFO] [Thu Apr 15 09:44:51 CEST 2021] BonusPagamentiDigitaliService - method modificaImpostazioniIBANEstesa-PATCH RESPONSE - HTTP STATUS[200]
[INFO] [Thu Apr 15 09:44:51 CEST 2021] BonusPagamentiDigitaliService - method modificaImpostazioniIBANEstesa-PATCH RESPONSE - HTTP ENTITY[{"validationStatus":"OK"}]
[DEBUG] [Thu Apr 15 09:44:51 CEST 2021] BonusPagamentiDigitaliService - modificaImpostazioniIBANEstesa-PATCH **[{"validationStatus": "OK"}]**

Poi richiamando lo statusUtente

[INFO] [Thu Apr 15 09:50:26 CEST 2021] BonusPagamentiDigitaliService - enrollmentCitizenStatusEstesa - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/citizens/RSTDNT79P29G793R]
[INFO] [Thu Apr 15 09:50:27 CEST 2021] BonusPagamentiDigitaliService - method enrollmentCitizenStatusEstesa-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 53fb7433-e890-4799-80f5-effda0c58a19]
[INFO] [Thu Apr 15 09:50:27 CEST 2021] BonusPagamentiDigitaliService - method enrollmentCitizenStatusEstesa-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/citizens/RSTDNT79P29G793R?flagTechnicalAccount=true
2021/04/15 09:50:27:567 CEST [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2021/04/15 09:50:27:574 CEST [DEBUG] RequestAuthCache - Auth cache not set in the context
2021/04/15 09:50:27:575 CEST [DEBUG] BasicHttpClientConnectionManager - Get connection for route {s}->https://test.cstar.pagopa.it:443
2021/04/15 09:50:27:694 CEST [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2021/04/15 09:50:27:982 CEST [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.125:53017<->20.54.178.216:443
2021/04/15 09:50:27:982 CEST [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2021/04/15 09:50:27:985 CEST [DEBUG] wire - http-outgoing-0 >> **"GET /bpd/hb/citizens/RSTDNT79P29G793R?flagTechnicalAccount=true HTTP/1.1[\r][\n]"**
2021/04/15 09:50:27:985 CEST [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2021/04/15 09:50:27:985 CEST [DEBUG] wire - http-outgoing-0 >> "x-request-id: 53fb7433-e890-4799-80f5-effda0c58a19[\r][\n]"
2021/04/15 09:50:27:987 CEST [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2021/04/15 09:50:27:987 CEST [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2021/04/15 09:50:27:987 CEST [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2021/04/15 09:50:27:987 CEST [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2021/04/15 09:50:27:988 CEST [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2021/04/15 09:50:28:220 CEST [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2021/04/15 09:50:28:220 CEST [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
2021/04/15 09:50:28:220 CEST [DEBUG] wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
2021/04/15 09:50:28:221 CEST [DEBUG] wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2021/04/15 09:50:28:221 CEST [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
2021/04/15 09:50:28:222 CEST [DEBUG] wire - http-outgoing-0 << "Expires: 0[\r][\n]"
2021/04/15 09:50:28:222 CEST [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2021/04/15 09:50:28:222 CEST [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2021/04/15 09:50:28:223 CEST [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
2021/04/15 09:50:28:223 CEST [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2021/04/15 09:50:28:223 CEST [DEBUG] wire - http-outgoing-0 << "Date: Thu, 15 Apr 2021 07:50:23 GMT[\r][\n]"
2021/04/15 09:50:28:224 CEST [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2021/04/15 09:50:28:224 CEST [DEBUG] wire - http-outgoing-0 << "75[\r][\n]"
2021/04/15 09:50:28:224 CEST [DEBUG] wire - http-outgoing-0 << "{"fiscalCode":"RSTDNT79P29G793R","payoffInstr":"ITxxxx","timestampTC":"2021-04-15T09:32:43.527+02:00","enabled":true}[\r][\n]"
2021/04/15 09:50:28:225 CEST [DEBUG] wire - http-outgoing-0 << "0[\r][\n]"
2021/04/15 09:50:28:225 CEST [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
[INFO] [Thu Apr 15 09:50:28 CEST 2021] BonusPagamentiDigitaliService - method enrollmentCitizenStatusEstesa-GET RESPONSE - HTTP STATUS[200]
[INFO] [Thu Apr 15 09:50:28 CEST 2021] BonusPagamentiDigitaliService - method enrollmentCitizenStatusEstesa-GET RESPONSE **- HTTP ENTITY[{"fiscalCode":"RSTDNT79P29G793R","payoffInstr":"ITxxxx","timestampTC":"2021-04-15T09:32:43.527+02:00","enabled":true}]**

**Comment by NicolaLamberti** [comment]
ciao @DenisaBraho questa anomalia attualmente blocca i test di integrazione.  Ci sono novità su una possibile data di rientro?

**Comment by daniloMessinaSia** [comment]
Buongiorno,
potreste riprovare e fornirci riscontro?

Grazie

**Comment by NicolaLamberti** [comment]
ciao @DenisaBraho . Adesso i campi tornano tutti. 

Grazie
