### ISSUE TITLE
SWAGGER: errore CitizenRankingMilestoneResource 

### ISSUE THREAD

**Issue by wallaroo** [pagopa/issuer_integration#192]
Salve la descriozione del DTO CitizenRankingMilestoneResource all'interno del file issuer_integration/ops_resources/swagger/bpd-hb-citizen-api-v2.yaml non sembra corrispondere a quanto documentato in ops_resources/Issuer%20Interface%20Agreement_v5_Eng_(Additions%20Post%20Release).pdf o a quanto effettivamente ritornato dall'API.

Potete controllare?
grazie mille

**Comment by corradogiancaspro** [comment]
Buongiorno ci sono novità sulla domanda in oggetto?

Grazie
Corrado

**Comment by DenisaBraho** [comment]
Ciao,
stiamo sistemando le interfacce e a breve verrà rilasciata una nuova versione (indicativamente entro Venerdi 28/05)
Saluti
