### ISSUE TITLE
Aggiornamento versione API

### ISSUE THREAD

**Issue by corradogiancaspro** [pagopa/issuer_integration#194]
Buongiorno

quando scadrà l'attuale versione delle API a favore della v2?

Grazie
Corrado

**Comment by DenisaBraho** [comment]
Buonasera,

a tutti i soggetti Issuer è stato richiesto di recepire le nuove specifiche e di valutare l'inserimento delle attività di adeguamento con priorità alta. Lato CentroStella considereremo i "vecchi" servizi come deprecati a partire dal 01/06/2021. 

(mail di riferimento: "CentroStella PagoPA>>>Issuer Integration - aggiornamento roadmap" del 16/02 )

Saluti

**Comment by corradogiancaspro** [comment]
Buongiorno,

il 1 Giugno è la scadenza della v1... ma la v2 da quando sarà utilizzabile nei vari ambienti?

Grazie
Corrado

**Comment by DenisaBraho** [comment]
Ciao,
la v2 è disponibili in tutti gli ambienti 
Saluti
