### ISSUE TITLE
Gestione Iban tecnico -  response errata servizio https://test.cstar.pagopa.it/bpd/hb/citizens/PLARST80A01H501Z?flagTechnicalAccount=true

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#195]
Salve, 

il servizio stato Utente non risponde con i dati del conto tecnico: 

[INFO] [04/05/2021 08.57.15 377] [pool-4-thread-101] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBANEstesa-PATCH -
REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: bb4b259b-0e4d-4fc5-921b-b44898c59477, Content-Type: application/json]]
[INFO] [04/05/2021 08.57.15 377] [pool-4-thread-101] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBANEstesa-PATCH -
**REQUEST PAYLOAD - {"technicalAccountHolder":"Postepay S.p.A.","accountHolderSurname":"Rosati","accountHolderCF":"PLARST80A01H501Z","payoffInstr":"IT33B3608105138PPAYSTA
NDARD","accountHolderName":"Paolo","payoffInstrType":"IBAN","issuerCardId":"0000000010783315"}]**
[INFO] [04/05/2021 08.57.15 861] [pool-4-thread-101] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBANEstesa-PATCH RE
SPONSE - HTTP STATUS[200]]
[INFO] [04/05/2021 08.57.15 861] [pool-4-thread-101] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBANEstesa-PATCH RE
SPONSE - HTTP ENTITY[{"validationStatus":"OK"}]]
[DEBUG] [04/05/2021 08.57.15 862] [pool-4-thread-101] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - modificaImpostazioniIBANEstesa-PATCH [{"valida
tionStatus": "OK"}]]

**Lo stato utente risponde con l’iban tecnico:** 

[DEBUG] [04/05/2021 08.57.15 953] [pool-4-thread-102] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/statoUtenteCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - START BonusPagamentiDigitaliService - enrollmentCitizenStatusEstesa ]
[INFO] [04/05/2021 08.57.15 953] [pool-4-thread-102] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/statoUtenteCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - enrollmentCitizenStatusEstesa - HTTP URL[http
s://test.cstar.pagopa.it/bpd/hb/citizens/PLARST80A01H501Z]]
[INFO] [04/05/2021 08.57.15 953] [pool-4-thread-102] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/statoUtenteCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatusEstesa-GET - RE
QUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 152630be-40ee-4b74-89b8-f886beacc1e8]]
[INFO] [04/05/2021 08.57.15 954] [pool-4-thread-102] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/statoUtenteCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatusEstesa-GET - RE
**QUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/citizens/PLARST80A01H501Z?flagTechnicalAccount=true]**
[INFO] [04/05/2021 08.57.16 267] [pool-4-thread-102] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/statoUtenteCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatusEstesa-GET RESP
ONSE - HTTP STATUS[200]]
[INFO] [04/05/2021 08.57.16 267] [pool-4-thread-102] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentCitizenStatusEstesa-GET RESPONSE - HTTP ENTITY[{"fiscalCode":"PLARST80A01H501Z","payoffInstr":"IT33B3608105138PPAYSTANDARD","timestampTC":"2020-12-08T17:50:49.908+01:00","enabled":true}]]
[DEBUG] [04/05/2021 08.57.16 268] [pool-4-thread-102] [SCA - SESSIONID [ADFB35FAA1BD580AA4C62B32E93F93DF.mobile] - COMMAND SCA [Async - v4/bancoposta/statoUtenteCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - **CASHBACK - WSCall - BonusPagamentiDigitaliService - enrollmentCitizenStatusEstesa-GET [{
"timestampTC": "2020-12-08T17:50:49.908+01:00",
"fiscalCode": "PLARST80A01H501Z",
"payoffInstr": "IT33B3608105138PPAYSTANDARD",
"enabled": true
}]]**

**Comment by DenisaBraho** [comment]
l'ambiente è ripristianato, potete riprovare.
In caso di eventuali ulteriori anomalie, prego di darcene riscontro
