### ISSUE TITLE
Attivazione subscription key

### ISSUE THREAD

**Issue by GuidoMarco** [pagopa/issuer_integration#199]
Salve,
abbiamo registrato 2 subscriptionKey per gli ambienti di UAT e PROD con il nome:

    nexi_ivr_stg

    nexi_ivr_prd

è possibile attivarle?
Grazie,
Marco

**Comment by edo621** [comment]
Ciao,

Sub Key di UAT attiva.
Entro Lunedì verrà attivata anche quella relativa a Prod.

Saluti

**Comment by edo621** [comment]
CIao,

Sub Key di Prod Attive.

Saluti
