### ISSUE TITLE
servizio 1.1.1 Restituzione file HTML T&C 

### ISSUE THREAD

**Issue by devitafederica** [pagopa/issuer_integration#20]
Abbiamo ricevuto l'endpoint di test del servizio in oggetto.
Noto però che i contenuti non sono ancora stati caricati… L’esigenza lato nostro è di poterli visualizzare per adattare le grafiche in app.
Una bozza di quelli che saranno i contenuti sarà caricata anche in test? Se si, quando?

**Comment by daniloMessinaSia** [comment]
Siamo ancora in attesa di una prima versione condivisibile.
Non appena ci verrà fornita la renderemo disponibile
