### ISSUE TITLE
API v2 in produzione

### ISSUE THREAD

**Issue by Carrettoni** [pagopa/issuer_integration#200]
Da quando saranno disponibili / utilizzabili in produzione le API v2

Grazief
Fabio

**Comment by DenisaBraho** [comment]
Ciao, 
le API v.2 sono già in Produzione dal 06/04
Saluti

**Comment by Carrettoni** [comment]
Ci risultano ancora errori in ambiente UAT oltre che la roadmap non le indica rilasciate in UAT

**Comment by DenisaBraho** [comment]
Ciao,
ci potete fornire degli esempi degli errori che riscontrate in UAT?
grazie

**Comment by wallaroo** [comment]
Ciao,
non è propriamente un'api v2... diciamo un'api v1.5 ma:

PUT /bpd/hb/payment-instruments/card?subscription-key=<apikey>
```{
	"id": "-----BEGIN PGP MESSAGE-----\nVersion: BCPG C# v1.6.1.0\n\nhQEMA+NENQPn0iNJAQgAlN5XSVXBhtT8UIwuETrp+4oAgUyvIIlGiEd4IjAv3jGI\nJf4EhyN/QFl8XdQonOGVNSQYembgYTHd83/jS8UtdPRROvj+CQd7a7UBRDY5PT72\nLEKrtoaUrdYR8oK2K//Qn6Q5CahqLZQYcRRbRqoRLoFoPI2d7faSDo6mj4x68XL5\n2EdYSe6q/NCFXSzS6goX8uE6MSNc7ljc1ZH1I9qSi+ciR6jyKaA7qm7flfKRK6pc\nxoBBz7tOr01WtOVHqiVXJNQXwjgwg44esPw56NCXxC5N/WwKcNtGjKagk8C2JMdl\nMLXoIaDp8Qm14CEiBwrQlfDcVaxa7EVnQtUAf+FBm8kuy5pQIrzvxnRcIfiNdSuX\nShvuDj3qfNeU4xMhCRsLveVKxJMnzJtsLgV6kgLzuw==\n=WeXz\n-----END PGP MESSAGE-----\n",
	"fiscalCode": "CVGNDR82S03C133A",
	"expireYear": "2022",
	"exprireMonth": "05",
	"issuerAbiCode": "03268",
	"brand": "MASTERCARD",
	"holder": "Andrea Cavagnet",
	"type": "PP",
	"channel": "03268",
	"tokenPanList":[<TOKENPAN1>,<TOKENPAN2>]
}

response:
< HTTP/1.1 400 ErrorPM
< Date: Thu, 27 May 2021 06:48:55 GMT
< Server: Apache
< Content-Length: 0
< Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4
< Vary: User-Agent
< Connection: close


in **ambiente di Produzione** invece ho notato nei giorni scorsi delle instabilità su:
GET /bpd/hb/citizens/v2/ranking
purtroppo non ho requestid da darvi ma a fronte della stessa chiamata ho avuto come ritorno, in modo aleatorio, un array vuoto...
se dovesse ricapitare vi giro la requestID

**Comment by daniloMessinaSia** [comment]
Buongiorno,
effettuando un test con il vostro id strumento, abbiamo notato che rimuovendo i caratteri "\n" di fine stringa, lo strumento viene decifrato correttamente.
Potreste riprovare con queste condizioni?

per completezza allego la stringa dell'id dello strumento testata
"-----BEGIN PGP MESSAGE-----\nVersion: BCPG C# v1.6.1.0\n\nhQEMA+NENQPn0iNJAQgAlN5XSVXBhtT8UIwuETrp+4oAgUyvIIlGiEd4IjAv3jGI\nJf4EhyN/QFl8XdQonOGVNSQYembgYTHd83/jS8UtdPRROvj+CQd7a7UBRDY5PT72\nLEKrtoaUrdYR8oK2K//Qn6Q5CahqLZQYcRRbRqoRLoFoPI2d7faSDo6mj4x68XL5\n2EdYSe6q/NCFXSzS6goX8uE6MSNc7ljc1ZH1I9qSi+ciR6jyKaA7qm7flfKRK6pc\nxoBBz7tOr01WtOVHqiVXJNQXwjgwg44esPw56NCXxC5N/WwKcNtGjKagk8C2JMdl\nMLXoIaDp8Qm14CEiBwrQlfDcVaxa7EVnQtUAf+FBm8kuy5pQIrzvxnRcIfiNdSuX\nShvuDj3qfNeU4xMhCRsLveVKxJMnzJtsLgV6kgLzuw==\n=WeXz\n-----END PGP MESSAGE-----"

Buona serata
