### ISSUE TITLE
Conferma V2

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#201]
Buonasera, potete confermare che l'operazione di PUT di uno strumento di pagamento (paragrafo 1.1.3.1 Card type payment instrument enrolment della documentazione), /bpd/hb/payment-instruments/card, NON verrà migrata nelle api V2?
Dal 01/06 quale sarà l'effetto lato client se si provasse a richiamare le API migrate? Riceveremmo un http status 500?

Grazie

Andrea

**Comment by AndreaCaccin** [comment]
Per procedere all'iscrizione di un pan nella versione V2 si deve utilizzare l'operation /bpd/hb/payment-instruments PATCH?
Grazie

**Comment by daniloMessinaSia** [comment]
Buongiorno,
al momento l'api di iscrizione di uno strumento di pagamento rimarrà la PUT descritta nella V1, sono in corso delle valutazione per definire se verrà migrata o meno.
L'Api di PATCH a cui si fa riferimento è disponibile per un altro tipo di operazione relativo alle tokenizzate, tema ancora in fase di sviluppo

Buona giornata
