### ISSUE TITLE
API Patch su Token - v2

### ISSUE THREAD

**Issue by corradogiancaspro** [pagopa/issuer_integration#202]
Buongiorno,

il metodo raggiungibile al path "/bpd/hb/payment-instruments" in PATCH sarà migrato alla v2 delle API o rimarrà in v1 e non cambierà neanche l'endpoint da chiamare?

Grazie
Corrado

**Comment by daniloMessinaSia** [comment]
Buongiorno,
anche il metodo di PATCH sarà oggetto di migrazione nella V2 delle API.
Attualmente, le API che non rientrano in questo tema sono quelle di PUT per gli enrollment degli strumenti, che saranno invocabili come definito nella V1.

Buona giornata
