### ISSUE TITLE
Iscrizione nuovo strumento di pagamento V2

### ISSUE THREAD

**Issue by PasqualeTalarico** [pagopa/issuer_integration#205]
Ciao, 

nei portali pagopa tra gli endpoint BPD HB Payment Instruments API V2, non vedo nessun metodo per **l'iscrizione di un nuovo PAN**, ma trovo solo l'operazione /bpd/hb/payment-instruments PATCH, che però pare non funzionare.
Va usato questo metodo o verrà migrato alla versione 2 l'operazione enrollPaymentInstrumentHB PUT?

**Comment by daniloMessinaSia** [comment]
Buongiorno,
al momento l'api di iscrizione di uno strumento di pagamento rimarrà la PUT descritta nella V1, sono in corso delle valutazione per definire se verrà migrata o meno.
L'Api di PATCH a cui si fa riferimento è disponibile per un altro tipo di operazione relativo alle tokenizzate, tema ancora in fase di sviluppo

Buona giornata
