### ISSUE TITLE
Verifica funzionamento V2 in produzione

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#206]
Ciao, in ambiente di produzione riceviamo un errore nell'invocazione delle seguenti api v2

x-request-id --> prova_status
2021-05-21 11:55:46,763
bpd/hb/payment-instruments/v2/5330044273096220
2021-05-21 11:55:47,023
500 NOT_FOUND

x-request-id --> prova_history
2021-05-21 11:58:18,304
bpd/hb/award-periods/v2
2021-05-21 11:58:18,480
404 Resource not found

Potete verificare? Grazie

**Comment by daniloMessinaSia** [comment]
Buongiorno, 
la versione 2 dell'api presente in ambiente di produzione è:
**Path**: bpd/hb/payment-instruments/v2/
**Request Header**:
- id: <id dello strumento di pagamento cifrato pgp>
- Ocp-Apim-Subscription-Key: <api key>

Buona giornata

**Comment by AndreaCaccin** [comment]
In merito al secondo end point segnalato (indico timestamp della prova eseguita oggi pomeriggio),
x-request-id --> prova_history
2021-05-25 16:18:33,395
bpd/hb/award-periods/v2
2021-05-25 16:18:33,586
404 Resource not found

avete riscontri? Continua ad andare in errore in ambiente di produzione, mentre in fase di test riceviamo una response corretta.
Grazie

**Comment by DenisaBraho** [comment]
Ciao,
adesso il servizio dovrebbe funzionare correttamente.
Saluti
