### ISSUE TITLE
SWAGGER: errore definizione body di DELETE /bpd/hb/citizens/v2/

### ISSUE THREAD

**Issue by wallaroo** [pagopa/issuer_integration#207]
nel file swagger https://github.com/pagopa/issuer_integration/blob/master/ops_resources/swagger/bpd-hb-citizen-api-v2.yaml
nella definizione di DELETE /bpd/hb/citizens/v2/ manca la definizione del body 
{
    "channel":"12345"
}

**Comment by DenisaBraho** [comment]
Ciao,
lo swagger verrà aggiornato e caricato in settimana (entro venerdi 30/05)
Saluti
