### ISSUE TITLE
Disattivazione Servizio Cashback

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#21]
Salve, 

la disattivazione del servizio come da voi indicato verrà rilasciata in UAT/Collaudo il 19/11, 
Per i nostri test interni per le app di Poste abbiamo la necessità di disattivare l'adesione al servizio per poter riutilizzare la stessa utenza per più test. 

Esiste un workaround per la disattivazione? Possiamo inviarvi la lista delle utenze per le quali disattivare il servizio? 

Grazie in anticipo per la risposta

Nicola

**Comment by lucasomarugasia** [comment]
ciao, potete inviare la lista a TeamCentroStella@sia.eu, indicando l'ambiente in cui effettuare la bonifica. Grazie,
