### ISSUE TITLE
Verifica funzionamento V2 in produzione

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#210]
Ciao,
in merito all'end point bpd/hb/award-periods/v2, abbiamo riprovato oggi pomeriggio coi dati seguenti

x-request-id --> prova_history
2021-05-25 16:18:33,395
bpd/hb/award-periods/v2
2021-05-25 16:18:33,586
404 Resource not found

ma continua ad andare in errore in ambiente di produzione, mentre in fase di test riceviamo una response corretta.
Potete verificare?

Grazie

**Comment by DenisaBraho** [comment]
Ciao, 
in merito all'API bpd/hb/award-periods/v2, confermiamo che non è stata ancora rilasciata in Produzione.
Sono ancora in corso i test di validazione API.  Non è stato ancora definita una data di rilascio in Prod.
Precisiamo che le API V2 in Produzione sono quelle relative alla CItizen e PaymentInstrument.
Saluti
