### ISSUE TITLE
Rimozione strumento di pagamento V2

### ISSUE THREAD

**Issue by mrossano** [pagopa/issuer_integration#211]
Ciao,
nell'aggiornamento dei servizi V2 ho notato una stranezza che si manifesta nel caso in cui si tenta di rimuovere/aggiungere uno strumento di pagamento aggiunto nei mesi scorsi con i servizi V1.

Nella fattispecie aggiunta e rimozione rispondono con successo ma non hanno alcun effetto sullo strumento di pagamento per il quale risulta impossibile muovere il suo stato.

Effettuando una disinscrizione completa dell'utente dal programma e una nuova iscrizione il problema sopra evidenziato non si presenta più.

Riuscite a verificare? I dati utilizzati con la V1 non sono utilizzabili con i servizi V2?

**Comment by DenisaBraho** [comment]
Ciao,
ci potete indicare il body della chiamata (o solo ID dello strumento cifrato)?
Grazie, Saluti

**Comment by mrossano** [comment]
Qui la chiamata di delete:
id=-----BEGIN PGP MESSAGE-----\nVersion: BCPG v1.45\n\nhQEMA+NENQPn0iNJAQgA35nSEiUDg6qtq13IkLABEaYQKhBpgA/6kCubQi+SJ2XG\nvS+/kEyDCEMARPQu95OqQgfHbO3smdYe/U6+4o/9eB90TfGT6tDqps4P1p83iDms\ny99Kn79FXojPpyvMUzMv+9Nk4OdxsgV9A8JrKIKRv8zBSkVLOuu42Yc54oqgjbDs\nVgLObzhufe2eTSH+XkekG/3249S9/Cv/bjQebueiB2yQoJ+s7wqVDY/ucy2rzO90\ns6HazutFAdVCvCcIOgHw3/gXwh3m14Kf6dNFA0eaBZYULmZqw1FBq3zyejR9fLCR\nP/f5I5Iwi/VPleVdmxkvIns5q4oANqXMlw9VxPKPg8k6h37Ly+n6I2VVBcgkJ2w/\nUq3TGPSFEzQ3I65v8++SRb1QW46vdWeLPzTz2NQDHpRv+eTkKv7t2dtOIw==\n=Pqjj\n-----END PGP MESSAGE-----\n
x-request-id=[66b7b178-81c2-4092-83d4-d39f7c11105e

Qui la successiva GET:
id=-----BEGIN PGP MESSAGE-----\nVersion: BCPG v1.45\n\nhQEMA+NENQPn0iNJAQf/fb28ZDpv7WPdHQWs0eXGstKo3O508dvQ0oHi8i1OLBSR\n+zK2NaOoO8x83PWpDRnq7pz1LAjjzUTnfULBlzhUSqo+NXf+k7IGm7U9QTmNTd5a\nP2/Bs0HklWhD3fvwb84L+k9ZPN773Bb9+cA/glVKookaitg2NWwhvbf/gxxAXszK\niRw16BXkLHuHHO5VmM3xeZYLR4rxDblBHjmoXRKkkUKJvdCubQFmw/dkiCkZgmjN\n4EbKvOCS3C2oJqs5EopLU3LG+e+R9QtWNBeGO98CXOHw+0w61miUqxfYHIcO6NiQ\nZMTP8df4/7pt81nKi5u4GV5x4xjSOjDgFwdyYViUT8k7ndAq/gXvwebcjwhV4+Bm\n5x0lSWAyP2/dTXipfUBR2sS6Y3RZaxul/1Yl91+EFoYKO6+UaAgJIPajX4M=\n=XEAw\n-----END PGP MESSAGE-----\n]
x-request-id=[3db242e4-9489-4a7a-ace3-2907847be5b8

Response: {"hpan":"1c29d64a1918f7f777d752633ba4a89325afd8b385119f8ae48149063ca54057","fiscalCode":"FRTMDA89R11F912C","activationDate":"2021-04-23T16:29:21.670493+02:00","deactivationDate":"2021-01-21T18:47:12.81+01:00","Status":"ACTIVE"}

Qui dopo la DELETE lo stato è rimasto ACTIVE e la deactivationDate non è variata.

**Comment by albertomarini1992** [comment]
Buonasera, 

la stessa stranezza/problematica è stata riscontrata anche da un altro team di sviluppo. 

Grazie
Alberto

**Comment by mrossano** [comment]
Ciao Alberto,
da cosa dipende il problema? Ci state lavorando?

Informazione più importante: si presenta nei soli ambienti di test oppure è presente anche in Produzione?

**Comment by mrossano** [comment]
I servizi v1 saranno comunque deprecati nella giornata di domani 01/06 Giugno. Confermate?

**Comment by albertomarini1992** [comment]
Buongiorno, 
@DenisaBraho avete novità? 
I servizi v1 verranno deprecati? 
In tutti gli ambienti? 

Alberto

**Comment by DenisaBraho** [comment]
Buongiorno Alberto,

la data di deprecazione delle V1 è stata posticipata
. 
In merito all'anomalia descritta sulla disattivazione strumento di pagamento, abbiamo replicato in UAT la chiamata d'esempio e il comportamento sembra corretto, lo strumento dopo la delete passa in INACTIVE e la data disattivazione viene aggiornata. Potreste riprovare? 

Qualora l'anomalia dovesse persistere, potete indicarci anche l'url della chiamata?

Grazie

**Comment by albertomarini1992** [comment]
Buongiorno, 

lato nostro stiamo richiamando test.cstar.pagopa.it/bpd/hb/payment-instruments/v2 con il seguente id

-----BEGIN PGP MESSAGE-----\nVersion: BCPG v1.46\n\nhQEMA+NENQPn0iNJAQf+MddpThycyCNtBp01cZOpmw3aOoqx+pHM/xHcd6flkOxz\n64Jiz3Zeg6r+qUmZdvWaJeCdr/3Zp9Y+WqMDCjRZ+A4NN++Zdno/oBGJDpKJBd8L\nd1NuEEf/iS/9tr6cEdTF3tE9Pon+Go7Z1lNBQO9VQLAhpSQEIL4Nx8Vp5/fRjg2J\nXH7Bt1RAoHy8JJLc22K0GIKcP1BNl2EaspniMCkDV0WcXfXbSIfhJP0sUuRyHdGU\nIA5LhbmmRQnj743jkarjvojGzwEK65edRae0kWuZTc2LxQYtkCpR3++JzEubueFk\nzik1i54lUXmAI5DJPTQJw+Y+d/L+CJ+TVdWRc88RQdJFAV/QXCuWxu49KpIPYCT3\nvJ9ju/HAdgbtOzh9nqv4IBgFd2B4hPdG+3BMeDScas05Za796TdAFhKL+fxoxsA9\nwbFGkvln\n=fB5x\n-----END PGP MESSAGE-----\n

e sembra non venga disattivata la carta. 
E' possibile fare un controllo? 
Dove posso reperire informazioni circa la deprecazione? 

Grazie
Alberto

**Comment by mrossano** [comment]
Ciao,
con una disinscrizione dell'utente il problema non si verifica più, l'utenza è come se venisse riallineata.

Il test corretto da fare è fare iscrizione utente, enroll carta con i servizi V1 e poi fare una delete con la V2.


Per la deprecazione c'è una data tentative?

**Comment by DenisaBraho** [comment]
CIao,
grazie, verifichiamo.

La deprecazione delle V1, verrà posticipata di qualche mese. Seguirà comunicazione ufficiale.

Saluti

**Comment by daniloMessinaSia** [comment]
Buongiorno,
abbiamo notato che sugli id risultati dalla pgpzzazione sono presenti dei caratteri "\n" a fine stringa non necessari.
Potreste rimuoverli ed effettuare nuovamente i test?

In attesa di riscontro,
Buona serata

**Comment by mrossano** [comment]
Ciao Danilo,
bisogna rimuovere solo l'ultimo "\n"?

**Comment by daniloMessinaSia** [comment]
Corretto,
è stato effettuato il test di GET e DELETE con gli id da voi indicati ed il risultato è stato quello atteso
