### ISSUE TITLE
403 PUT per enroll citizen ambiente SIT

### ISSUE THREAD

**Issue by riccardoscelsigft** [pagopa/issuer_integration#213]
Buongiorno,
non riusciamo a chiamare con nessuna PK nexi questi endpoint in ambiente SIT:
/bpd/hb/citizens/v2

Dettaglio log

2021-05-28 13:01:17.884  INFO [mte-issuing-cashback-pagopa,4adac6185703ecf9,4adac6185703ecf9,false] 20228 --- [io-8222-exec-10] i.n.m.h.c.i.HttpLoggingInterceptor       : REST request: {
    method: PUT
    url: https://intapi.nexi.local:8443/outbound/Middletier/pagopa/bpd/hb/citizens/v2/
    headers: {
        Accept: application/json
        OCP-APIM-SUBSCRIPTION-KEY: ***
        Content-Type: application/json
        MT_INTERNAL_REQUEST_ORIGIN: NEXI/mte-issuing-cashback-pagopa
        User-Agent: NEXI/mte-issuing-cashback-pagopa
        Authorization: ******
    }
    body: {"id":"PLZBRN80E09H501Y"}
}

2021-05-28 13:01:17.928  INFO [mte-issuing-cashback-pagopa,4adac6185703ecf9,4adac6185703ecf9,false] 20228 --- [io-8222-exec-10] i.n.m.h.c.i.HttpLoggingInterceptor       : REST response: {
    request: {
        method: PUT
        url: https://intapi.nexi.local:8443/outbound/Middletier/pagopa/bpd/hb/citizens/v2/
    }
    code: 403
    headers: {
        Server: Apache-Coyote/1.1
        Content-Type: application/json;charset=UTF-8
        Content-Length: 38
        Date: Fri, 28 May 2021 11:00:22 GMT
        OkHttp-Sent-Millis: 1622199677891
        OkHttp-Received-Millis: 1622199677928
    }
    body: {    "errcode":403,    "errmsg":"forbidden"}
}

ci riuscireste a dare supporto?
l'errore sembra simile a quello presente in questa segnalazione 
https://github.com/pagopa/issuer_integration/issues/146

**Comment by DenisaBraho** [comment]
Ciao,
verifichiamo e vi forniamo riscontro appena possibile
Saluti

**Comment by riccardoscelsigft** [comment]
Oggi abbiamo provato utilizzando altri parametri di sicurezza, il problema sembra rientrato
