### ISSUE TITLE
Swagger ops_resources/swagger/bpd-hb-winning-api.yaml non aggiornato

### ISSUE THREAD

**Issue by daviogg** [pagopa/issuer_integration#214]
Ho notato che lo swagger seguente:
ops_resources/swagger/bpd-hb-winning-api.yaml

non è aggiornato con la versione V2 delle API, è corretto?

Nella documentazione aggiornata viene utilizzata questa API.

URL: /bpd/hb/winning-transactions/v2/total-cashback
METHOD: GET

**Comment by DenisaBraho** [comment]
Ciao,
confermiamo che la v2 dello swagger "bpd-hb-winning-api.yaml" è stato caricato

Grazie
Saluti
