### ISSUE TITLE
UAT - Error 500 in bpd/hb/payment-instruments/v2

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#217]
Buongiorno, durante gli UAT dell'integrazione API v2 riscontriamo "500 - Internal Server Error" durante l'invocazione dell'operation di GET all'end point in oggetto: potete verificare? Grazie
Di seguito gli header di una chiamata di esempio per il pan 5330048196851561

**x-request-id:** migration
**id:** -----BEGIN PGP MESSAGE-----nVersion: BCPG v1.65nnhQEMA5iQxLoVRSHvAQf+MIOXOBGRFXddQzGszyg2bC06H2A1IlwvMuurKpQQSlFrnjo5s3FEstv8VNUQcBVOgY+UvQfgVMiXPYpveN/+t3EPVn3oPYB6myzHNkLLgjR+nn1PnO85I0q9tiVpdbuWWO9e5TC05l4gmbqAIkXepwsCyRpsbaLJpOhl2Obkl8ENmcnypE1kEqPpVpGDvQLvkQeow9CmUp+UtzdQYRmjRHKzkBh3hQa2JLCRGhtArhh23zOnV8NGs6mjYIOWe0xoJqB+2X2gyi6qTumhUFmwNm/GC2iZn2wJCTHBZ1biarv80s3cnMJY/4/viqPCeTg1NC57ThbgAdLiDlm0tvcV/EOzaWtJLASXrPJR3E5L0nAyWMsrunXwxLbdfKrbBGJfTxNiSW632P3WiOI7+3Z0ZDEOy32P+wFA2T1Rts4LGE+lWIKBqrn+pIz5KHci6nxGcf1n=Jsjnn-----END PGP MESSAGE-----n

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo verificato che l'id non è riportato correttamente (mancanza \n).Potreste riprovare? 

Di seguito, il dato corretto:

[12:41] Danilo Messina
-----BEGIN PGP MESSAGE-----\nVersion: BCPG v1.65\n\nhQEMA5iQxLoVRSHvAQf+MIOXOBGRFXddQzGszyg2bC06H2A1IlwvMuurKpQQSlFr\njo5s3FEstv8VNUQcBVOgY+UvQfgVMiXPYpveN/+t3EPVn3oPYB6myzHNkLLgjR+n\n1PnO85I0q9tiVpdbuWWO9e5TC05l4gmbqAIkXepwsCyRpsbaLJpOhl2Obkl8ENmc\nypE1kEqPpVpGDvQLvkQeow9CmUp+UtzdQYRmjRHKzkBh3hQa2JLCRGhtArhh23zO\nV8NGs6mjYIOWe0xoJqB+2X2gyi6qTumhUFmwNm/GC2iZn2wJCTHBZ1biarv80s3c\nMJY/4/viqPCeTg1NC57ThbgAdLiDlm0tvcV/EOzaWtJLASXrPJR3E5L0nAyWMsru\nXwxLbdfKrbBGJfTxNiSW632P3WiOI7+3Z0ZDEOy32P+wFA2T1Rts4LGE+lWIKBqr\n+pIz5KHci6nxGcf1\n=Jsjn\n-----END PGP MESSAGE-----

Saluti
Denisa
