### ISSUE TITLE
SWAGGER: errore definizione body di DELETE /bpd/hb/citizens/v2/ 

### ISSUE THREAD

**Issue by wallaroo** [pagopa/issuer_integration#218]
copia della issue #207 chiusa con promessa di correzione entro il 28/05 (2021 suppongo)
chiuderei solo a correzione effettivamente pushata grazie.

nel file swagger https://github.com/pagopa/issuer_integration/blob/master/ops_resources/swagger/bpd-hb-citizen-api-v2.yaml
nella definizione di DELETE /bpd/hb/citizens/v2/ manca la definizione del body
{
"channel":"12345"
}

**Comment by DenisaBraho** [comment]
Ciao,
file caricato.
Saluti
