### ISSUE TITLE
SWAGGER: errore CitizenRankingMilestoneResource 

### ISSUE THREAD

**Issue by wallaroo** [pagopa/issuer_integration#219]
clone della issue #192 chiusa con promessa di correzione entro 28/05 (2021 suppongo)
chiuderei solo a correzione effettivamente pushata grazie.

Salve la descriozione del DTO CitizenRankingMilestoneResource all'interno del file issuer_integration/ops_resources/swagger/bpd-hb-citizen-api-v2.yaml non sembra corrispondere a quanto documentato in ops_resources/Issuer%20Interface%20Agreement_v5_Eng_(Additions%20Post%20Release).pdf o a quanto effettivamente ritornato dall'API.

Potete controllare?
grazie mille

**Comment by DenisaBraho** [comment]
Ciao,
lo swagger è stato aggiornato e il CitizenRankingMilestoneResource non verrà restituito verso gli Issuer.
Saluti
Denisa
