### ISSUE TITLE
API di recupero totale cashback - 404 Not Found

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#22]
Da qualche giorno l'API di Recupero totale del cashback (paragrafo "1.1.10 Recupero totale cashback" della documentazione) restituisce l'errore "404 - Not Found" in **SIT** (in precedenza era funzionante).

L'url è il seguente: https://bpd-dev.azure-api.net/bpd/hb/winning-transactions/total-cashback?awardPeriodId=1&fiscalCode=XXXXXXXXXX (che risulta essere ancora quello corretto da documentazione).

Vi risulta che tale API sia non più disponibile in SIT?

**Comment by daniloMessinaSia** [comment]
Buongiorno,
potreste riprovare e darci un feedback?
In SIT stiamo facendo degli interventi pertanto potrebbero essere presenti indisponibilità temporanee

**Comment by albertosangalliflowe** [comment]
Confermo che ora l'errore non è più 404, ma a seguito di una chiamata riscontro una risposta completamente vuota.
