### ISSUE TITLE
UAT award periods v2 - pariodi attivi

### ISSUE THREAD

**Issue by riccardoscelsigft** [pagopa/issuer_integration#221]
Buongiorno,
durante dei test odierni svolti in ambiente di UAT abbiamo riscontrato che la award periods non ritorna periodi attivi:

<html><body>

`
  | REST response: {	request: {		method: GET 		url: https://stgsecgw.private.nexicloud.it:8443/outbound/Middletier/pagopa/bpd/hb/award-periods/v2/	}	code: 200	headers: { 		Server: Apache-Coyote/1.1		Cache-Control: no-cache, no-store, max-age=0, must-revalidate		Pragma: no-cache		Expires: 0		X-Content-Type-Options: nosniff		X-XSS-Protection: 1; mode=block		X-Frame-Options: DENY		Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4		Content-Type: application/json;charset=UTF-8		Date: Mon, 28 Jun 2021 16:02:34 GMT		OkHttp-Sent-Millis: 1624896154182		OkHttp-Received-Millis: 1624896154545	}	body: [{"awardPeriodId":3,"startDate":"2022-01-01","endDate":"2022-06-30","minTransactionNumber":5,"maxAmount":150,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"INACTIVE","maxTransactionEvaluated":150},{"awardPeriodId":4,"startDate":"2022-07-01","endDate":"2022-12-31","minTransactionNumber":5,"maxAmount":0,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"INACTIVE","maxTransactionEvaluated":150},{"awardPeriodId":5,"startDate":"2023-01-01","endDate":"2023-06-30","minTransactionNumber":5,"maxAmount":150,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"INACTIVE","maxTransactionEvaluated":150},{"awardPeriodId":0,"startDate":"2020-11-23","endDate":"2020-12-31","minTransactionNumber":5,"maxAmount":1500,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":180,"status":"WAITING","maxTransactionEvaluated":150},{"awardPeriodId":97,"startDate":"2020-08-23","endDate":"2020-09-22","minTransactionNumber":5,"maxAmount":1500,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"CLOSED","maxTransactionEvaluated":150},{"awardPeriodId":100,"startDate":"2023-01-01","endDate":"2023-06-30","minTransactionNumber":5,"maxAmount":150,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"INACTIVE","maxTransactionEvaluated":150},{"awardPeriodId":6,"startDate":"2023-07-01","endDate":"2023-12-31","minTransactionNumber":50,"maxAmount":150,"minPosition":10,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"INACTIVE","maxTransactionEvaluated":150},{"awardPeriodId":14,"startDate":"2021-05-27","endDate":"2021-06-01","minTransactionNumber":5,"maxAmount":1500,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":20,"status":"CLOSED","maxTransactionEvaluated":150},{"awardPeriodId":2,"startDate":"2021-06-21","endDate":"2021-06-25","minTransactionNumber":5,"maxAmount":1500,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"WAITING","maxTransactionEvaluated":150},{"awardPeriodId":23,"startDate":"2021-06-01","endDate":"2021-06-27","minTransactionNumber":5,"maxAmount":1500,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"WAITING","maxTransactionEvaluated":150},{"awardPeriodId":1,"startDate":"2021-01-01","endDate":"2021-06-10","minTransactionNumber":5,"maxAmount":1500,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":13,"status":"CLOSED","maxTransactionEvaluated":150},{"awardPeriodId":99,"startDate":"2020-10-23","endDate":"2020-11-22","minTransactionNumber":5,"maxAmount":1500,"minPosition":5,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"CLOSED","maxTransactionEvaluated":150},{"awardPeriodId":98,"startDate":"2020-09-23","endDate":"2020-10-22","minTransactionNumber":5,"maxAmount":0,"minPosition":0,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"CLOSED","maxTransactionEvaluated":150},{"awardPeriodId":8,"startDate":"2027-01-01","endDate":"2027-06-30","minTransactionNumber":50,"maxAmount":1500,"minPosition":******,"maxTransactionCashback":15,"maxPeriodCashback":150,"cashbackPercentage":10,"gracePeriod":10,"status":"INACTIVE","maxTransactionEvaluated":150}]}
-- | --
`

qui una lista più pratica:
{
    [
        {
            "awardPeriodId": 3,
            "startDate": "2022-01-01",
            "endDate": "2022-06-30",
            "minTransactionNumber": 5,
            "maxAmount": 150,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "INACTIVE",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 4,
            "startDate": "2022-07-01",
            "endDate": "2022-12-31",
            "minTransactionNumber": 5,
            "maxAmount": 0,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "INACTIVE",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 5,
            "startDate": "2023-01-01",
            "endDate": "2023-06-30",
            "minTransactionNumber": 5,
            "maxAmount": 150,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "INACTIVE",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 0,
            "startDate": "2020-11-23",
            "endDate": "2020-12-31",
            "minTransactionNumber": 5,
            "maxAmount": 1500,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 180,
            "status": "WAITING",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 97,
            "startDate": "2020-08-23",
            "endDate": "2020-09-22",
            "minTransactionNumber": 5,
            "maxAmount": 1500,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "CLOSED",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 100,
            "startDate": "2023-01-01",
            "endDate": "2023-06-30",
            "minTransactionNumber": 5,
            "maxAmount": 150,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "INACTIVE",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 6,
            "startDate": "2023-07-01",
            "endDate": "2023-12-31",
            "minTransactionNumber": 50,
            "maxAmount": 150,
            "minPosition": 10,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "INACTIVE",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 14,
            "startDate": "2021-05-27",
            "endDate": "2021-06-01",
            "minTransactionNumber": 5,
            "maxAmount": 1500,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 20,
            "status": "CLOSED",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 2,
            "startDate": "2021-06-21",
            "endDate": "2021-06-25",
            "minTransactionNumber": 5,
            "maxAmount": 1500,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "WAITING",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 23,
            "startDate": "2021-06-01",
            "endDate": "2021-06-27",
            "minTransactionNumber": 5,
            "maxAmount": 1500,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "WAITING",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 1,
            "startDate": "2021-01-01",
            "endDate": "2021-06-10",
            "minTransactionNumber": 5,
            "maxAmount": 1500,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 13,
            "status": "CLOSED",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 99,
            "startDate": "2020-10-23",
            "endDate": "2020-11-22",
            "minTransactionNumber": 5,
            "maxAmount": 1500,
            "minPosition": 5,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "CLOSED",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 98,
            "startDate": "2020-09-23",
            "endDate": "2020-10-22",
            "minTransactionNumber": 5,
            "maxAmount": 0,
            "minPosition": 0,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "CLOSED",
            "maxTransactionEvaluated": 150
        },
        {
            "awardPeriodId": 8,
            "startDate": "2027-01-01",
            "endDate": "2027-06-30",
            "minTransactionNumber": 50,
            "maxAmount": 1500,
            "minPosition":******,
            "maxTransactionCashback": 15,
            "maxPeriodCashback": 150,
            "cashbackPercentage": 10,
            "gracePeriod": 10,
            "status": "INACTIVE",
            "maxTransactionEvaluated": 150
        }
    ]
}

Vorremmo sapere se è normale che non risultino periodi attivi o in caso segnalare l'anomalia.

Vi ringrazio

**Comment by riccardoscelsigft** [comment]
Buongiorno,
per permettere lo svolgimento di test integrativi in previsione del periodo di gennaio 22 è possibile inserire un periodo attivo in ambiente UAT?
Vi ringrazio

**Comment by DenisaBraho** [comment]
Buongiorno,
attualmente in UAT sono presenti periodi attivi.
Saluti
