### ISSUE TITLE
500 Hashing Service Error

### ISSUE THREAD

**Issue by smAPIgtw** [pagopa/issuer_integration#223]
Buongiorno,
invocando la seguente API

https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5354760597064757

riceviamo l'errore
500 Hashing Service Error
con body vuoto

Potreste verificare?

saluti

Service Manager API Gateway Poste

**Comment by umbros** [comment]
Buongiorno @smAPIgtw,
l'endpoint corretto è:  api.uat.cstar.pagopa.it come da comunicazione inviata.

Potete verificare?

Grazie

**Comment by smAPIgtw** [comment]
Buonasera,
all'indirizzo mail associato a questa utenza non abbiamo ricevuto la comunicazione del cambio di endpoint, potreste indicare dove troviamo la documentazione aggiornata con i nuovi endpoint? 
Al seguente percorso 
https://github.com/pagopa/issuer_integration/blob/master/ops_resources/Issuer%20Interface%20Agreement_v5_Eng_(Additions%20Post%20Release).pdf trovo ancora l'hostname https://test.cstar.pagopa.it

Di seguito i percorsi che usiamo:
/bpd/hb/award-periods/
/bpd/hb/citizens/
/bpd/hb/winning-transactions/
/bpd/hb/payment-instruments/

Ci potreste indicare se il cambio di endpoint è valido per i percorsi indicati?

saluti

Service Manager API Gateway Poste

**Comment by smAPIgtw** [comment]
Buongiorno,
ci potreste dare un ritorno sulla richiesta precedente?

saluti

Service Manager API Gateway Poste

**Comment by umbros** [comment]
Buongiorno @smAPIgtw confermo la validità, potrebbe trattarsi di problemi sulla mutua autenticazione. Mi scrivi a umberto.rosini@pagopa.it?

**Comment by smAPIgtw** [comment]
Buonasera,
ho verificato che con i dati indicati nel primo messaggio l’errore non è più presente, provvedo a chiudere la issue
