### ISSUE TITLE
Numeri Carta Nazionali ( Pagobancomat )

### ISSUE THREAD

**Issue by ChristianRoldo** [pagopa/issuer_integration#23]
Ciao,

con quale logica va inviato il numero di carta nazionale ? 
Di solito si utilizza   ABI4CARATTERI + "0" + PANNAZIONALE12CARATTERI

Tipo   12340123456123456

E' questa la logica da utilizzare ?
Grazie
Christian

**Comment by menottistefano** [comment]
a quale attributo e di quale API si fa riferimento?
in generale il PAN carta deve esser passato così come viene letto e utilizzato durante i pagamenti

**Comment by ChristianRoldo** [comment]
Ciao all'attributo PAN dell'api enrollPaymentInstrumentHB .
Nel caso di circuito nazionale PagoBancomat qual è la regola da seguire ?
Lato acquiring quei dati se non erro vengono forniti direttamente da pagobancomat stesso e credo necessitiate dello stesso formato.

**Comment by DenisaBraho** [comment]
Ciao Christian,

il processo prevede di ricevere in fase di enrollment carte Bancomat l'identificativo univoco dello strumento, che come giustamente avete indicato dovrà coincidere con il dato fornito da Bancomat tramite le transazioni.
Quindi è corretto che venga inviato in fase di enrollment lo stesso identificativo con lo stesso formato inviato da Bancomat.
