### ISSUE TITLE
DataScadenza

### ISSUE THREAD

**Issue by ChristianRoldo** [pagopa/issuer_integration#24]
Ciao
qual è l utilità dell invio della data scadenza della carta ? 
Di fatto una carta scaduta non può transare per cui non avreste il dato lato acquring. 
Serve esclusivamente per eliminarlo dalla lista degli hashed pan ?

grazie
Christian

**Comment by menottistefano** [comment]
la data scadenza serve per mostrare le caratteristiche della carta in App IO, specificatamente nel caso in cui la carta non ha altri dati noti al cittadino e per non esser ambigui nei casi in cui il cittadino abbia N carte

**Comment by ChristianRoldo** [comment]
Quindi tutte le carte enrollate da HB delle singole banche saranno comunque visibili su App IO ? 
Nel caso in cui la banca prevede ad inviare anche i token di GPay o ApplePay quindi queste verranno visualizzate sull'app IO ?
Il cliente credo potrebbe rimanere leggermente confuso a riguardo.

**Comment by menottistefano** [comment]
si tutte le carte saranno visibili in App IO. la gestione dei Token è ancora in fase di studio. ci sarà un'aggiornamento nei prossimi giorni riguardo la gestione degli stessi.
