### ISSUE TITLE
Enrollment strumento di pagamento - Cifratura PAN e scadenza 

### ISSUE THREAD

**Issue by ChristianRoldo** [pagopa/issuer_integration#25]
Ciao,
come riportato nelle ultime comunicazioni le specifiche di enrollment strumento di pagamento H/M Banking per le carte sono state aggiornate e  lato sicurezza, è convenuto di cifrare pgp i parametri PAN e data scadenza. 

Qualche domanda:

- quando saranno disponibili le chiavi ?
- oltre a cifrare con chiave va encodato in base64 ? ( immagino di si ) 
- essendo il valore criptato sotto pgp consistente a livello di lunghezza è previsto di rivedere la firma del servizio per inviare nel body l'id e non nell'url ?

grazie
Christian

**Comment by lucasomarugasia** [comment]
Buongiorno, specifiche aggiornate e chiavi PGP pubbliche disponibili qui: 
https://github.com/pagopa/issuer_integration/tree/master/ops_resources/PGP%20key
