### ISSUE TITLE
Requisiti funzionali

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#26]
Buonasera,

avrei bisogno di smarcare alcuni dubbi funzionali riguardo il Cashback di Stato:

1. è possibile avere più periodi di cashback attivi contemporaneamente?
2. In che modo è possibile identificare in modo univoco il bonifico tramite cui l'utente finale riceverà l'accredito sul proprio conto? Sarà sempre lo stesso ente ad emettere il bonifico? L'IBAN mittente sarà sempre lo stesso? Quale sarà la causale di questa operazione?
3. Alla fine di ogni periodo, in che modo è possibile sapere se l'utente ha vinto il cashback (sia il cashback che il cashback speciale)?
4. Perchè nell'API della richiesta graduatoria, il parametro Award Period ID è un parametro opzionale? In che modo cambierà l'output se l'Award Period ID sarà popolato o meno? 
5. Sono previste a piano delle API per ricevere il dettaglio di tutte le transazioni?

Grazie mille

**Comment by DenisaBraho** [comment]
Ciao,

di seguito le nostre risposte:

1. Alla fine di un Award Period inizierà in automatico un nuovo periodo di premiazione. Tuttavia, sarà stabilito un periodo: "Grace Period" (durata TBD)  entro il quale tutte le transazioni pervenute dopo la fine dell'Award Period (ossia dopo che è iniziato l'Award Period successivo) ma aventi una data transazione che rientra all'interno del periodo di premiazione precedente verranno presi in considerazione e contribuiranno alla generazione del cashback (associato all'award period precedente).
2. L'ente Consap sarà responsabile dell'accredito del cashback nell'IBAN inserito dall'utente. BPD fornirà a Consap una serie di campi che permetteranno di distinguere il modo univoco la transazione ( es. ID univoco relativo al pagamento, CF, Nome, Cognome beneficiario, Causale etc). 
Riportiamo per completezza un esempio  della valorizzazione della Causale nel file inviato da CentroStella verso Consap:
_Causale: (id_pagamento, tipo iniziativa Cashback, Periodo): 000000001 - Cashback di Stato - dal 01/01/2021 al 30/06/2021_
3. Sara visibile nel H/M Banking  il numero minimo delle trx richieste, il numero delle trx effettuate dall'utente e il cashback maturato. Riguardo al premio speciale sarà visibile all' utente il suo Ranking, che gli permetterà di capire se ha vinto il premio speciale o meno.
4. L'API permette di restituire la graduatoria per tutti i periodi (presente e passati) in cui ha partecipato l'utente, motivo per cui l' AwardID parameter è facoltativo. Quando tale parametro viene inserito, si restituisce esclusivamente la graduatoria per il periodo inserito. 
5. No, dal H/M Banking non sarà possibile visualizzare il dettaglio delle transazioni.

A disposizione,
Saluti

**Comment by MarcoDeNovellis** [comment]
Un ulteriore domanda sul primo punto. I periodi di cashback andranno in parallelo con i periodi di cashback speciali? Cioè avremo che per ogni mese ci sarà un cashback normale ed un cashback speciale? Oppure ci sarà un cashback normale al mese ed un cashback speciale dalla durata di 6 mesi che andrà quindi in parallelo con i 6 cashback normali sugli stessi mesi?

Grazie
