### ISSUE TITLE
Recesso

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#27]
Salve, 

l'IA del recesso quando verrà condivisa? Da piano era prevista la condivisione per il 05/11. 

E' stato rilasciato in UAT l'enrollment strumento di pagamento? 

Grazie mille 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,

l'IA contenente i dettagli relativi al recesso utente da H/M Banking verrà condivisa in data 18/11/2020.
L'enrollment dello strumento di pagamento è stato rilasciato in UAT.
Saluti
