### ISSUE TITLE
Delucidazioni su servizi e campi non valorizzati

### ISSUE THREAD

**Issue by Pierwide** [pagopa/issuer_integration#28]
Salve,
di seguito alcuni quesiti e anomalie riscontrate:
1. nella response dello status ( /bpd/hb/payment-instruments/{id}), il campo status è null, da doc i valori previsti erano ACTIVE e INACTIVE.

2. il servizio ranking (/bpd/hb/citizens/XXXXXXXXXXXXX/ranking?awardPeriodId=1) ma status 200 con body vuoto. 

3. il servizio total cashback (/bpd/hb/winning-transactions/total-cashback?awardPeriodId=1&fiscalCode=XXXXXXXXXXXX)                ritorna status 200 con body vuoto

4. il servizio delete payment instruments ritorna errore, settimana scorsa funzionava (/bpd/hb/payment-instruments/{pan}). E’ un’anomalia momentanea? 

5.il servizio di delete payment instrument si può invocare subito dopo aver registrato la carta, oppure ci sono dei tempi di attesa?

6. il servizio del recupero della graduatoria (/bpd/hb/citizen/ranking) restituisce una lista invece di un oggetto come da doc, è corretto? (se si riportatelo in doc)

Grazie
Pier

**Comment by DenisaBraho** [comment]
CIao, 
stiamo verificando i punti indicati.
per quanto riguarda il punto 1. potreste indicarci un esempio specifico sul quale vi viene restuito il campo vuoto?

Vi aggiorniamo sulle altre segnalazioni appena possibile. 
Grazie

**Comment by luca-delgiudice-dev** [comment]
Ciao,

utente TSTMIA00L14A074F, pan 5330********6588, ambiente SIT.

risposta del servizio:

PaymentInstrumentResource {
    activationDate: 2020-11-03T14:46:22.534+01:00
    cancellationDate: null
    fiscalCode: TSTMIA00L14A074F
    hpan: 96ac3316523eeaf3299dc6ba62db20cc1fc22590f37a4aa5bf8b408c764e9015
    **status: null**
}

grazie,
Luca

**Comment by mdesogus** [comment]
Buongiorno

di seguito le risposte ai punti segnalati:

1. non abbiamo evidenza del campo null per quell'hpan, si prega di riprovare e darci riscontro
2. è stata rilasciata una versione che risolve l'anomalia
3. è stata rilasciata una versione che risolve l'anomalia
4. è stata rilasciata una versione che risolve l'anomalia
5. il servizio è invocabile subito dopo l'enrollment
6. è corretta la lista, correggeremo la documentazione

restiamo in attesa di riscontro,
grazie e buona giornata

**Comment by luca-delgiudice-dev** [comment]
Buongiorno,

in merito al punto 1, abbiamo riprovato con la nuova versione e ora riceviamo i valori nei nuovi campi: Status e deactivationDate.
Segnaliamo che nell'interfaccia il campo è denominato "status" mentre il servizio ritorna "Status".

In merito agli altri punti, confermiamo che le anomalie sono state risolte.

grazie e buona giornata

**Comment by DenisaBraho** [comment]
Ciao  Luca,
grazie del feeback e della segnalazione sul campo "status", provvederemo con la modifica volta ad allineare il servizio con la documentazione.
Saluti
