### ISSUE TITLE
Ambiente di test

### ISSUE THREAD

**Issue by luca1oo** [pagopa/issuer_integration#29]
Ciao, sarà disponibile un’ambiente di test lato piattaforma PagoPA per provare il giro completo di attivazione carta e simulazione acquisto presso esercente fisico?
Grazie

**Comment by DenisaBraho** [comment]
Ciao,
vi sarà l'apertura delle attività di test di CentroStella PagoPA ad un bacino utenti allargato in ambiente di produzione (pilota) per la verifica e certificazione dei processi di invio transazioni verso RTD (Registro Transazioni Digitali e Bonus Pagamenti Digitali).

A partire da martedì 17/11 si permetterà quindi di aderire al programma di Beta che prevede la verifica delle funzionalità del cashback tramite utilizzo di App IO.

La comunicazione competa relativamente all'apertura pilota è stata inviata via mail.
A disposizione per ulteriori chiarimenti
Saluti
