### ISSUE TITLE
Update Requisiti funzionali

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#30]
In relazione al primo punto dell'issue 26 ormai chiusa, vorrei porre un ulteriore domanda:

I periodi di cashback **normale** andranno in parallelo con i periodi di cashback **speciali**? 
Cioè avremo che per ogni mese/trimestre/semestre ci sarà coesistenza di un cashback normale ed un cashback speciale? Oppure ci sarà un cashback normale al mese ed un cashback speciale dalla durata di 6 mesi che andrà quindi in parallelo con i 6 cashback normali sugli stessi mesi?

Grazie

**Comment by DenisaBraho** [comment]
Ciao,
sulla gestione cashback e premi speciali le regole non sono ancora definitive. Gli organi competenti le approveranno a breve.
