### ISSUE TITLE
disallineamento documentazione IA vs swagger

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#31]
Salve, 

abbiamo notato un disallineamento tra la documentazione IA e lo swagger condiviso. 
esempio: 

- "status" del periodo nell'IA manca. 
- maxTransactionCashback manca nell'IA.

Quando verrà allineato il documento IA? 

Inoltre, saranno previsti i seguenti parametri?
- Data ultimo aggiornamento transazioni effettuate dall'utente nel periodo corrente
- Data di accredito Cashback 
- Rapporto (iban) sul quale è stato accreditato il cashback nel periodo di riferimento

Grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,

l'ia aggiornato con i dati sui campi segnalati verrà condiviso a breve (entro 18/11) contenente oltre a tali aggiornamenti, anche il recesso da H/M Banking.
Per quando riguarda le domande sui parametri di seguito le nostre risposte:
1. No, tale parametro non è previsto
2. Non è previsto l'invio della data dell'accredito del Cashback
3. L'unico parametro previsto è quello relativo  all'IBAN inserito dal cittadino.
A disposizione
Saluti
