### ISSUE TITLE
Importo super Cashback

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#32]
Salve, 

l'importo super cashback è un valore fisso o verrà restituito da qualche servizio?

Grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola, attualmente il campo contenente il premio (maxAmount) viene restituito dalla chiamata /bpd/hb/award-periods ed è un campo impostato per ciascun award period (es: 1500 eu ) . Tuttavia, precisiamo che le regole sull'importo del cashback speciale non sono ancora definitive e gli organi competenti le approveranno a breve.
