### ISSUE TITLE
Super cashback

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#33]
Salve, 

l'iniziativa super cashback è sempre prevista? 
Qual è il parametro che indica se in un determinato periodo il super cashback non è previsto? 

Grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao,
stando alle regole attualmente definite, l'iniziativa super cashback sarà sempre prevista, tranne nel primo periodo sperimentale ( 01/12/2020 -31/12/20)

**Comment by DenisaBraho** [comment]
Tuttavia, per completezza, precisiamo che regole non sono ancora definitive. Gli organi competenti le approveranno a breve.
