### ISSUE TITLE
Classifica Super Cashback in fase di consolidamento

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#34]
Salve, 

esiste un parametro che indica se la classifica del super cashback è in fase di consolidamento? Oppure alla chiusura del periodo la classifica è già disponibile? 

Grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao,

No, attualmente non è previsto un tale parametro. La classifica sarà consolidata al termine del Grace Period. Il “Grace Period” è un arco temporale (di durata ancora TBD) che inizerà al termine di ogni periodo di erogazione AwardID, al fine di gestire le transazioni pervenute alla piattaforma dopo la data di chiusura dell'Award period ma che hanno una data transazione  <= alla data di termine del periodo di premiazione. Il parametro GP è presente nello Swagger "bpd-hb-awardperiod-api"
