### ISSUE TITLE
Enrollment strumento di pagamento di tipo Carta (API con errore: 404 - Resource Not Found)

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#35]
Effettuando dei test in SIT per il servizio di Enroll della carta di pagamento riceviamo un errore 404 "resource not found"

Qui di seguito un esempio:

PUT - https://bpd-dev.azure-api.net/fa/hb/payment-instruments/card/**1234567890123456**
REQUEST:
{
    "fiscalCode": "{CodiceFiscale}",
    "expireYear": 2025,
    "exprireMonth": 12,
    "issuerAbiCode": "{ABICode}",
    "brand": "Mastercard",
    "holder": "Mario Rossi",
    "type": "DEB",
    "channel": "{ABICode}"
}

RESPONSE:
**{
    "statusCode": 404,
    "message": "Resource not found"
}**

**Comment by DenisaBraho** [comment]
Ciao, abbiamo notato che l'endpoint del servizio indicato è relativo a FA (attualmente non esistente) e non a BPD. Potreste verificare?

**Comment by albertosangalliflowe** [comment]
Confermo che era errato l'url.
con l'url:PUT - https://bpd-dev.azure-api.net/fa/hb/payment-instruments/card/**1234567890123456**

L'associazione è stata effettuata con successo.
Grazie
