### ISSUE TITLE
Recupero Graduatoria (API Error : "404  - Resource Not Found")

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#36]
Cercando di chiamare l'API di "Recupero Graduatoria" riceviamo un errore di tipo "404 - Resource not Found"

GET https://bpd-dev.azure-api.net/bpd/hb/citizen/**{FiscalCode}**/ranking?awardPeriodId=**{awardPeriodId}**

RESPONSE:
**{
    "statusCode": 404,
    "message": "Resource not found"
}**

**NOTA**: Considerando che il parametro: "awardPeriodId" è OPZIONALE da documentazione, che Output restituirebbe il servizio se non fosse passato questo parametro?

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo provveduto a risolvere l'anomalia descritta. Potreste provare e fornirci un feedback? 

L'API permette di restituire la graduatoria per tutti i periodi (presente e passati) in cui ha partecipato l'utente, motivo per cui l' AwardID parameter è facoltativo. Quando tale parametro viene inserito, si restituisce esclusivamente la graduatoria per il periodo inserito.
Saluti

**Comment by albertosangalliflowe** [comment]
Confermo che ora l'API funziona correttamente se viene passato il parametro "awardPeriodId"

GET https://bpd-dev.azure-api.net/bpd/hb/citizen/**{FiscalCode}**/ranking?awardPeriodId=**{awardPeriodId}**

Tuttavia chiamando il servizio senza il parametro "awardPeriodId":
GET https://bpd-dev.azure-api.net/bpd/hb/citizen/**{FiscalCode}**/ranking

continuiamo a ricevere:
**{
    "statusCode": 404,
    "message": "Resource not found"
}**

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo risolto l'anomalia. Potreste verificare se il servizio è funzionante e restituisce il codice atteso?
Grazie

**Comment by albertosangalliflowe** [comment]
Confermo che ora funziona
Grazie
