### ISSUE TITLE
Rinnovi Carte e Data Scadenza

### ISSUE THREAD

**Issue by ChristianRoldo** [pagopa/issuer_integration#37]
Ciao a tutti, 
ai fini cashback se non ho capito male viene considerato solo hashed pan.
La data scadenza viene utilizzata solo per la visualizzazione in app IO.
Il filtro lato acquiring viene applicato solo per hashed PAN.
Cosa succede in casa di rinnovo di una carta in cui il PAN non cambia , ma solo la data scadenza ? 
Come ci dobbiamo comportare ? 
Grazie
Christian

**Comment by DenisaBraho** [comment]
Ciao Christian,

nel caso in cui la carta si rinnovi mantendendo lo stesso PAN, il processo funzionerà correttamente in quanto verranno considerate le transazioni effettuate con la "nuova" carta, senza necessità di effettuare nuovamente l'enrollment da parte del cittadino. 
In merito alla gestione delle carte, il processo prevede che sia il cittadino a gestire le proprie carte. In particolare, nel caso di carta rinnovata, il processo funzionerà correttamente , ma sarà visibile all'utente nel proprio portale/app come data scadenza quella precedente inserita in fase di enrollment. In questi casi, l'utente potrà comunque disattivare/cancellare la carta precedente e inserire la "nuova".
A disposizione per ulteriori chiarimenti
Saluti
