### ISSUE TITLE
Recupero Graduatoria (API Error : "404 - Resource Not Found")

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#39]
Salve 

https://test.cstar.pagopa.it/bpd/hb/citizens/RSSNEE99A01H501L/ranking?awardPeriodId=0  

restituiscie: 

message": "Resource not found",
   "statusCode": 404

il servizio ci risponde con errore anche se il cf è attivo.
Ci aspettiamo ci dia uno stato di ranking, sulla doc il 404 non è documentato.

restiamo in attesa di un vostro riscontro

Grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,

potreste provare a chiamare su https://test.cstar.pagopa.it/bpd/hb/**citizen**/RSSNEE99A01H501L/ranking?awardPeriodId=0

Abbiamo verificato che c'è un disallineamento tra lo swagger e quanto riportato nell'IA. (/citizen/ vs. /citizens/)
Provvediamo ad aggiornare lo swagger appena possibile caricando la versione aggiornata. 
In attesa di un riscontro, 
Saluti

**Comment by DenisaBraho** [comment]
Ciao Nicola avete avuto modo di verificare se la chiamata adesso funziona?

**Comment by NicolaLamberti** [comment]
Ho aperto la issue #44. 

Il recupero graduatoria continua a restituire un array mentre in documentazione è scritto che sarà un oggetto.
Qual è la situazione corretta? 
In caso di array, quanti elementi ci dobbiamo aspettare?
Come andranno gestiti i campi visto che noi richiediamo la graduatoria per un determinato periodo? ci aspetteremo informazioni singole.

Grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,
stiamo verificando la issue 44. Chiudiamo questa issue per evitare issue duplicati.
Vi aggiorniamo appena possibile
Grazie
