### ISSUE TITLE
Disassociazione dello strumento di Pagamento

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#40]
Provando a rimuovere una carta associata al profilo utente (precedentemente associata sempre tramite API) riceviamo errore "404 - Resource not found"

Qui i dettagli:
DELETE: https://bpd-dev.azure-api.net/bpd/hb/payment-instruments/{{PAN in chiaro}}

RESPONSE: 404 - Not Found

**Comment by DenisaBraho** [comment]
Ciao,
l'anomalia dovrebbe essere risolta. Potreste verificare?
Grazie

**Comment by albertosangalliflowe** [comment]
Confermo, ora funziona
