### ISSUE TITLE
Servizio di Recupero Status degli strumenti di pagamento

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#41]
Con l servizio "Status Strumento Pagamento H/M Banking" riceviamo i dati delle carte da noi inserite.
Per tale scopo utilizziamo l'API: 
GET: https://bpd-dev.azure-api.net/bpd/hb/payment-instruments/{PAN in chiaro}

A regime sarà possibile vedere le informazioni di carte enrolled anche da altri issuer (con i dati sensibili "anonimizzati")?

**Comment by DenisaBraho** [comment]
Ciao,
no, dal H/M Banking non sarà possibile visualizzare i dati delle carte emesse ed enrollate da altri Issuer.
Saluti
