### ISSUE TITLE
Endpoint definitivi - Stato utente

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#42]
Salve, 

stamattina non risponde il servizio che restituisce lo stato utente che fino a ieri funzionava correttamente.
Sembra cambiato l’endpoint

Da:
https://test.cstar.pagopa.it/bpd/hb/citizens

A:
https://test.cstar.pagopa.it/bpd/hb/citizen

Potreste indicarci gli endpoint definitivi ?

Grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola, si ti confermiamo che l'endpoint corretto e definitivo è https://test.cstar.pagopa.it/bpd/hb/citizen 
Saluti

**Comment by ChristianRoldo** [comment]
Scusate ma ora funziona citizens  e non citizen!!!!
