### ISSUE TITLE
Errore 500 in impostazione/modifica IBAN da H/M Banking

### ISSUE THREAD

**Issue by antessio** [pagopa/issuer_integration#43]
Environment: UAT
x-request-id: 79c97b04-e09f-47c6-a102-609220868f00
Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4
API: PATCH /bpd/hb/citizen/<id>

--- 
**Risultato atteso:**

Http status : 200
Response Body: 
```json
{
    "validationStatus": "OK"
}
```

**Risultato ottenuto:**

Http status: 500
```json
{
  "returnMessages": {
    "ERROR": [
      {
        "message": "Errore generale contattare l'assistenza",
        "messageTitle": "Errore Generale",
        "messageKey": "generic.error",
        "severity": "ERROR"
      }
    ]
  }
}
```

**Comment by antessio** [comment]
Ho riprovato poco fa ottenendo non più un errore ma comunque una risposta non attesa. 

Environment: UAT
x-request-id: a6f0f6d4-7f90-488a-b5cf-ce56497f0e81
Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4

--- 

```json
{
  "validationStatus": "UNKNOWN_PSP"
}
```

L'iban che sto usando è: `IT74S0300203280794426587372`

Preciso che è un iban di test generato randomicamente.

**Comment by DenisaBraho** [comment]
Ciao, 

il comportamento ci sembra in linea con quelle che sono le logiche impostate attualmente. La risposta ricevuta significa che il servizio non è stato in grado di verificare l'IBAN, in particolare non è stato possibile verificare l'effettiva l'associazione dell'IBAN all'utente indicato. Questa risposta comporta, a differenza del messaggio di KO ( codice fiscale non associato all'IBAN fornito ). il salvataggio dell'IBAN nel database.

Saluti

**Comment by antessio** [comment]
Considerando che gli ambienti nei quali sto facendo queste chiamate sono usati per i test, in che modo è possibile associare l'IBAN all'utente?
