### ISSUE TITLE
Recupero graduatoria - array diverso dalle specifiche

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#44]
Salve, 

il servizio di recupero della graduatoria sta restituendo un array diversamente da come riportato in documentazione.

Di seguito quello che riceviamo: 

[[{"ranking":11,"totalParticipants":10,"maxTransactionNumber":11,"transactionNumber":0,"awardPeriodId":0}]]]

resto in attesa di un vostro riscontro

Grazie 

Nicola

**Comment by mdesogus** [comment]
Buongiorno,

Il servizio prevede la possibilità di ricevere una lista di periodi strutturati come da documentazione nel caso in cui non venga specificato un awardPeriod.
Qualora specificato invece verrà ritornato un unico oggetto contente i dati per l' awardPeriod indicato che verrà visualizzato come elemento uno della lista

grazie,
Michael

**Comment by NicolaLamberti** [comment]
La documentazione riporta semplicemente un oggetto di ritorno e non un array. Eseguiti altri due test senza successo:
Se non si passa il periodo otteniamo errore 500

https://test.cstar.pagopa.it/bpd/hb/citizen/RSSNEE99A01H501L/ranking?awardPeriodId=0 
RESPONSE - HTTP STATUS[500] 

https://test.cstar.pagopa.it/bpd/hb/citizen/RSSNEE99A01H501L/ranking 
RESPONSE - HTTP STATUS[500]
