### ISSUE TITLE
Stato strumento di pagamento -  errore 404

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#45]
Salve, 

la get per lo stato di uno strumento di pagamento che è stato abilitato al cashback restituisce 404. Fino a stamattina funzionava correttamente

https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030]

RESPONSE - HTTP STATUS[404]]

restiamo in attesa di riscontro

Grazie 

Nicola

**Comment by NicolaLamberti** [comment]
[INFO] [Fri Nov 20 10:41:35 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030]
[INFO] [Fri Nov 20 10:41:35 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 73461781-f3e0-4401-a755-19a230b7f9ed]
[INFO] [Fri Nov 20 10:41:35 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030
2020/11/20 10:41:35:164 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/20 10:41:35:168 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/20 10:41:35:170 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/20 10:41:35:190 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/20 10:41:35:200 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/20 10:41:35:493 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:50825<->20.54.178.216:443
2020/11/20 10:41:35:494 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/20 10:41:35:495 CET [DEBUG] wire - http-outgoing-0 >> "GET /bpd/hb/payment-instruments/5333171000547030 HTTP/1.1[\r][\n]"
2020/11/20 10:41:35:496 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/20 10:41:35:496 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 73461781-f3e0-4401-a755-19a230b7f9ed[\r][\n]"
2020/11/20 10:41:35:496 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/20 10:41:35:496 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/20 10:41:35:496 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/20 10:41:35:497 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/20 10:41:35:497 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/20 10:41:35:806 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 404 Not Found[\r][\n]"
2020/11/20 10:41:35:806 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
2020/11/20 10:41:35:808 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/20 10:41:35:809 CET [DEBUG] wire - http-outgoing-0 << "Date: Fri, 20 Nov 2020 09:41:35 GMT[\r][\n]"
2020/11/20 10:41:35:810 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/20 10:41:35:835 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/20 10:41:35:836 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Fri Nov 20 10:41:35 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP STATUS[404]
[INFO] [Fri Nov 20 10:41:35 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP ENTITY[]

**Comment by NicolaLamberti** [comment]
[INFO] [Fri Nov 20 18:17:09 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030]
[INFO] [Fri Nov 20 18:17:09 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 75b7ecae-de76-471f-9e16-2321496bc53d]
[INFO] [Fri Nov 20 18:17:09 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030
2020/11/20 18:17:09:107 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/20 18:17:09:112 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/20 18:17:09:114 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/20 18:17:09:136 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/20 18:17:09:148 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/20 18:17:09:699 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:54571<->20.54.178.216:443
2020/11/20 18:17:09:701 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/20 18:17:09:706 CET [DEBUG] wire - http-outgoing-0 >> "GET /bpd/hb/payment-instruments/5333171000547030 HTTP/1.1[\r][\n]"
2020/11/20 18:17:09:707 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/20 18:17:09:708 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 75b7ecae-de76-471f-9e16-2321496bc53d[\r][\n]"
2020/11/20 18:17:09:709 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/20 18:17:09:712 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/20 18:17:09:713 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/20 18:17:09:715 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/20 18:17:09:717 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/20 18:17:10:274 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
2020/11/20 18:17:10:274 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 111[\r][\n]"
2020/11/20 18:17:10:274 CET [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
2020/11/20 18:17:10:275 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/20 18:17:10:275 CET [DEBUG] wire - http-outgoing-0 << "Date: Fri, 20 Nov 2020 17:17:10 GMT[\r][\n]"
2020/11/20 18:17:10:275 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/20 18:17:10:275 CET [DEBUG] wire - http-outgoing-0 << "{ "statusCode": 500, "message": "Internal server error", "activityId": "0dfc01fd-6ac6-4bb8-87cb-8648d164d87b" }"
2020/11/20 18:17:10:293 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/20 18:17:10:293 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Fri Nov 20 18:17:10 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP STATUS[500]
[INFO] [Fri Nov 20 18:17:10 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP ENTITY[{ "statusCode": 500, "message": "Internal server error", "activityId": "0dfc01fd-6ac6-4bb8-87cb-8648d164d87b" }]
[DEBUG] [Fri Nov 20 18:17:10 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento-GET [{
   "activityId": "0dfc01fd-6ac6-4bb8-87cb-8648d164d87b",
   "message": "Internal server error",
   "statusCode": 500

**Comment by DenisaBraho** [comment]
Ciao,
l'anomalia è stata risolta. Adesso il servizio dovrebbe funzionare correttamente.
@NicolaLamberti Rimaniamo in attesa di un feedback.
Saluti

**Comment by NicolaLamberti** [comment]
Se chiamiamo il servizio status per una carta mai attivata/disattivata ci rispondete con 404

**Comment by DenisaBraho** [comment]
Ciao Nicola,
la segnalazione sullo status a 404 per la carta non attivata/disattivata è presente anche nella segnalazione #65. Per evitare di creare issue duplicate, procedo con la chiusura di questa issue, e vi rispondiamo sulla segnalazione in questione nell'altra issue appena possibile. Grazie

**Comment by DenisaBraho** [comment]
per correggere nr issue #66  (attualmente aperta.)
