### ISSUE TITLE
Chiarimenti sui dati in ricezione

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#46]
Buongiorno,

1. Se l'utente raggiunge il massimo ammontare previsto di cashback, il dato che ci ritorna il totale di cashback accumulato continuerà ad aumentare oppure si ferma al maxcashback previsto per quel periodo?
2. Esiste un API che ci permette di conoscere il numero di transazioni mancanti affinchè l'utente rientri nella classifica del super cashback?
3. Quanto tempo dopo la chiusura del periodo sarà l'accredito all'utente il cashback maturato?
4. Con L'API inerente al paragrafo 1.1.9 del documento di specifiche ("Recupero graduatoria") vediamo che per ogni "AwardPeriod" sono disponibili informazioni relative al ranking del cliente specifiche per ogni Periodo.
E' corretto interpretare che in ogni periodo ci sarà una classifica dedicata e che per ogni periodo saranno erogati potenzialmente 2 premi:
     1) Cashback maturato dal cliente con i suoi strumenti di pagamento (purchè il "minTransactionNumber" sia soddisfatto e non andrà oltre al "maxAmount" possibile per il periodo)
     2) Supercashback (con quota di 1500 € FISSI per ogni periodo) che verrà assegnato sulla base del "ranking" in classifica e del valore "minPosition" correlato all'Award attivo in quella data.

**Comment by DenisaBraho** [comment]
Ciao,
di seguito le nostre risposte:

1. si, al raggiungimento del cashback massimo, quest'ultimo si fermerà al max cashback 
2. l'API non prevede un campo che contiene il numero di trx mancanti al raggiungimento premio speciale, ma tuttavia contiene tutti i dati necessari: il numero delle proprie transazioni, il numero minimo di transazioni effettuate dagli utenti che rientrano nel “rimborso speciale” e il numero transazioni effettuati dal primo utente in classifica
3. Dopo la chiusura dell'Award Period, inizierà un Grace Period (un periodo di tolleranza che permetterà alla piattaforma di considerare anche le trx effettuate durante l'award period appena concluso ma contabilizzate con giorni di ritardo - _durata ancora da definire_ ). Dopo la fine del Grace Period, i dati sui vincitori verranno inviati a Consap. L'ente procederà successivamente con l'erogazione dei premi (indicativamente il mese dopo la chiusura del periodo di premiazione). Precisiamo che queste regole non sono ancora definitive. 
4.  Confermiamo la vostra interpretazione. Anche in questo caso, precisiamo che l'ammontare del supercashback e le regole di assegnazione definitive non sono state ancora approvate dagli organi competenti.
Saluti
