### ISSUE TITLE
Recupero graduatoria 

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#47]
Salve, 
 in riferimento alla issue #44 la documentazione riporta un oggetto di ritorno e non un array. 
Eseguiti altri due test senza successo e se non si passa il periodo otteniamo errore 500

https://test.cstar.pagopa.it/bpd/hb/citizen/RSSNEE99A01H501L/ranking?awardPeriodId=0
RESPONSE - HTTP STATUS[500]

https://test.cstar.pagopa.it/bpd/hb/citizen/RSSNEE99A01H501L/ranking
RESPONSE - HTTP STATUS[500]

**Comment by mdesogus** [comment]
Buongiorno,

in riferimento alla issue #44 il ritorno di una lista è corretto, correggeremo la documentazione;

per i due test segnalati la preghiamo di riprovare e darci riscontro , gli url da invocare post modifica sono i seguenti:

- https://test.cstar.pagopa.it/bpd/hb/citizens/{codice_fiscale}/ranking?awardPeriodId={award_period_id}
- https://test.cstar.pagopa.it/bpd/hb/citizens/{codice_fiscale}/ranking

grazie

**Comment by DenisaBraho** [comment]
Ciao,
@NicolaLamberti  avete avuto modo di effettuare dei test invocando gli url indicati? 
Grazie

**Comment by NicolaLamberti** [comment]
### - https://test.cstar.pagopa.it/bpd/hb/citizens/{codice_fiscale}/ranking?awardPeriodId={award_period_id}
Se passo come awardPeriodId=1 ottengo una risposta vuota mentre con 0 il log seguente

### https://test.cstar.pagopa.it/bpd/hb/citizens/{codice_fiscale}/ranking 
ottengo l’unica graduatoria presente. E’ corretto che pur avendo 4 periodi uno solo abbia una graduatoria?

**Comment by daniloMessinaSia** [comment]
Bungiorno,
di seguito una breve delucidazione sul funzionamento dei servizi.
Il servizio di Ranking restituisce la situazione della classifica dal punto di vista dell'utente.
Se viene invocata con uno specifico award Period verrà mostrata la situazione utente all'interno di quello speficico periodo, 
se non viene specificato un awardPeriod viene restituita la situazione sulla base del periodo attualmente ACTIVE e tutti quelli CLOSED.
Se l'utente ha transazioni validate, viene estratta la sua effettiva posizione in classifica altrimenti viene considerato che l'utente sia in ultima posizione.

In ambiente di UAT non tutti i periodi che risultano conclusi contengono una classifica consolidata pertanto per i periodi con ID 1-2-3 (che vanno dal 2020-02-20 al 2020-05-04) non viene estratta alcuna classifica,
il periodo con ID 4 è futuro alla data corrente pertanto non verrebbe estratto, il periodo 0 è l'unico per il quale sono state raccolte transazioni che compongono un ranking (a prescindere che l'utente vi abbia partecipato o meno)
