### ISSUE TITLE
Domande su API Enrollment strumento di pagamento

### ISSUE THREAD

**Issue by mrossano** [pagopa/issuer_integration#48]
Ho notato che rispetto alla precedente versione del servizi, per l'enrollment dello strumento di pagamento utilizzando il PAN della carta, ora è stata inserita la cifratura PGP del dato.

Avrei quindi diverse domande/dubbi:
- il vecchio servizio è stato totalmente dismesso?
- nella documentazione è presente la nota: le chiavi PGP saranno disponibili a breve; è possibile avere una pianificazione? Fino ad allora non sarà quindi possibile utilizzare il servizio?
- come mai la cifratura è stata inserita solo nel servizio di enrollment e non in quello di retrieve dello stato? Secondo la documentazione, per la API /bpd/hb/payment-instruments/{id} il parametro {id} corrisponde al PAN della carta in chiaro.

**Comment by DenisaBraho** [comment]
Ciao,
di seguito le nostre risposte:
1. il servizio è stato _aggiornato_, in modo da recepire anche la cifratura dei dati
2. si, attualmente siamo ancora in attesa della chiave pubblica che verrà condivisa appena possibile. Seguira comunicazione. Il servizio di per se è utilizzabile anche in assenza della chiave.
3. la necessità di introdurre la cifratura è nata dal impossibilità che i dati del **PAN** e **Scadenza carta** "viaggiassero" insieme in chiaro nella chiamata, in quanto dati sensibili.  Per tale motivo, la cifratura è stata introdotta solo nella chiamata di enrollment nella quale sono presenti entrambi i dati. 
A disposizione
Saluti

**Comment by mrossano** [comment]
Per il punto 2 non è chiaro cosa avverrà quando sarà attiva la cifratura. Senza cifratura il servizio non sarà più utilizzabile?
