### ISSUE TITLE
Servizio di status di uno strumento abilitato restituisce un errore 404

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#49]
Salve, 

alla seguente chiamata: 
https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000556999]

riceviamo: 

RESPONSE - HTTP STATUS[404]]

**Comment by DenisaBraho** [comment]
Ciao Nicola,
se non erro, la problematica sembra essere la stessa riportata nella issue attualmente in fase di analisi #45.
Per evitare la creazione di issue duplicate, provvediamo a chiudere questa issue e teniamo aperta la issue #45 aperta ieri. 
Vi forniamo un riscontro appena possibile
Saluti
