### ISSUE TITLE
Chiarimenti

### ISSUE THREAD

**Issue by luca1oo** [pagopa/issuer_integration#5]
(1) Un cliente che si è già iscritto su App IO/altro issuer, quando accede all'app di un'altra Banca deve registrarsi nuovamente all'iniziativa e rifirmare T&C?
(2) Se la carta è stata aggiunta tramite App IO, io issuer, non ho modo di vedere la percentuale di cashback legate alla mia carta
(3) Il cashback viene erogato in modo automatico ogni 6 mesi (max 150 a semestre)? 
(4) Come viene gestito il rimborso semestrale se l'iniziativa parte il 1 Dicembre e si ipotizza data fine 31/12/2021, quindi 13 mensilità?
(5) Se l'iscrizione non avvenuta su App dell'issuer, l'issuer ha modo di recuperare IBAN con cui si è iscritto il cliente su altra App/App IO?

**Comment by menottistefano** [comment]
1. no, non è necessario riaccettare i T&C. la chiamata statusCitizen restituisce lo stato dell'utente
2. sarà possibile verificare il cashback cumulato dal cittadino su tutte le carte registrate, non lo specifico sulla carta
3. si
4. il primo mese è sperimentale e gestito in modo separato con accredito del cashback maturato sul mese
5. no, la chiamata statusCitizen restituisce però se l'utente ha già memorizzato un IBAN e l'issuer può permettere al cittadino di memorizzarne uno nuovo (sovrascrive il precedente)
