### ISSUE TITLE
Il servizio di delete payment-instruments non cancella la carta

### ISSUE THREAD

**Issue by luca-delgiudice-dev** [pagopa/issuer_integration#50]
Ciao,
in ambiente SIT, il servizio di delete payment-instruments non ritorna più 404 ma ora ritorna status 204.
Tuttavia, invocando il servizio di status la carta non risulta cancellata, la cancellationDate e lo status non sono valorizzati.
Potete verificare? Sono previsti dei tempi di attesa per la presa in carico della cancellazione?

Logs:

2020-11-13 15:29:02.464
DELETE https://bpd-dev.azure-api.net/bpd/hb/payment-instruments/5330********6588 HTTP/1.1
<-- HTTP/1.1 204 No Content

2020-11-13 15:30:35.185
GET https://bpd-dev.azure-api.net/bpd/hb/payment-instruments/5330********6588 HTTP/1.1
<-- HTTP/1.1 200 OK

PaymentInstrumentResource {
    activationDate: 2020-11-13T15:18:34.747+01:00
    cancellationDate: null
    fiscalCode: TSTMIA00L14A074F
    hpan: 96ac3316523eeaf3299dc6ba62db20cc1fc22590f37a4aa5bf8b408c764e9015
    status: null
}

grazie,
Luca

**Comment by DenisaBraho** [comment]
Ciao Luca,
abbiamo fatto delle modifiche e il servizio dovrebbe funzionare.
In attesa di un riscontro 
Grazie

**Comment by luca-delgiudice-dev** [comment]
Ciao,
confermo.

grazie,
Luca
