### ISSUE TITLE
Integrazione BA

### ISSUE THREAD

**Issue by BrignoliSIA** [pagopa/issuer_integration#51]
stiamo per il servizio Bancomat Pay integrando le prime chiamate per l’enrollment da APP di circuito; riceviamo l’errore in allegato.
 
Sembra un problemi di certificati anche se abbiamo caricato il certificato che ci avete fornito.
 
Potete verificare se tali chiamate arrivano sui vostri sistemi ed indicarci il perché del rifiuto?

**Comment by BrignoliSIA** [comment]
Request e response
INFO  2020-11-12 09:31:15,821  AbstractRestClient(?: ?)        Send PUT request:
 ID: a9c13512-bfc0-44ea-bfa6-cefe5da3d7e1
 Endpoint: https://bpd-dev.azure-api.net/bpd/hb/citizens/TSTPGP91E25F704H
 Content object: <org.apache.http.client.methods.HttpPut>
	<headergroup>
		<headers>
			<org.apache.http.message.BasicHeader>
				<name>content-type</name>
				<value>application/json</value>
			</org.apache.http.message.BasicHeader>
			<org.apache.http.message.BasicHeader>
				<name>accept</name>
				<value>application/json</value>
			</org.apache.http.message.BasicHeader>
			<org.apache.http.message.BasicHeader>
				<name>x-request-id</name>
				<value>a5cb5e65-e3d0-489b-9a1d-eb88f99fc08d</value>
			</org.apache.http.message.BasicHeader>
			<org.apache.http.message.BasicHeader>
				<name>Ocp-Apim-Subscription-Key</name>
				<value>****************3687</value>
			</org.apache.http.message.BasicHeader>
		</headers>
	</headergroup>
	<aborted>
		<value>0</value>
	</aborted>
	<cancellableRef/>
	<uri>https://bpd-dev.azure-api.net/bpd/hb/citizens/TSTPGP91E25F704H</uri>
	<entity class="org.apache.http.entity.StringEntity">
		<contentType class="org.apache.http.message.BasicHeader">
			<name>Content-Type</name>
			<value>text/plain; charset=ISO-8859-1</value>
		</contentType>
		<chunked>false</chunked>
		<content>bnVsbA==</content>
	</entity>
</org.apache.http.client.methods.HttpPut>

ERROR 2020-11-12 09:31:16,063  AbstractRestClient(?: ?)        
	P2PBEEXT00001E - Eccezione durante la chiamata REST verso servizio esterno
	javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	Caused by: java.io.EOFException: SSL peer shut down incorrectly

**Comment by mdesogus** [comment]
Buongiorno,

Dalle evidenze ci risulta che le chiamate effettuate sono indirizzate all'ambiente di Sit, per tale ambiente dovremmo ricevere da parte vostra il certificato self signed.
Potreste effettuare delle verifiche e nel caso di assenza provvedere a fornirci via mail al team CentroStella 
(TeamCentroStella@sia.eu) il certificato in formato .cer?
Per info sul processo sono presenti dei riferimenti sul documento ISSUER INTERFACE AGREMENT https://github.com/pagopa/issuer_integration/blob/master/ops_resources/Issuer%20Interface%20Agreement_v2.pdf


Grazie
