### ISSUE TITLE
"BPD TC API" API non disponibili in UAT e PRODUZIONE

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#52]
Negli ambienti di UAT e di Produzione non risultano disponibili tramite Developer Portal: https://developer-test.cstar.pagopa.it/) le API della famiglia: "BPD TC API" (per il recupero del "Term & Condition" del servizio.

E' corretto?
Tali servizi verranno resi disponibili in seguito anche per questi ambienti?

**Comment by mdesogus** [comment]
Buongiorno,

accedendo al link presente in descrizione il servizio ci risulta essere presente.
potreste verificare e fornirci riscontro?

grazie

**Comment by DenisaBraho** [comment]
Ciao @albertosangalliflowe ci sono novità in merito?
Grazie

**Comment by albertosangalliflowe** [comment]
Confermo che:

- https://test.cstar.pagopa.it/bpd/tc/html
- https://test.cstar.pagopa.it/bpd/tc/pdf

Funzionano correttamente ora.

Ci confermate che per queste 2 API non è necessaria key ("Ocp-Apim-Subscription-Key")?

**Comment by DenisaBraho** [comment]
Ciao,
si confermiamo, la key non è necessaria per queste API
Saluti
