### ISSUE TITLE
Cancellazione IBAN di accredito

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#53]
salve, 

è previsto un servizio che permette all'utente di cancellare l'iban di accredito precedentemente inserito?

Ad oggi è presente solo un servizio per aggiungere o modificare. 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,
no, attualmente non è previsto un servizio di cancellazione IBAN
Saluti
