### ISSUE TITLE
(SWAGGER) api /bpd/hb/citizens/ranking definizioni parametri mancanti

### ISSUE THREAD

**Issue by wallaroo** [pagopa/issuer_integration#54]
Ciao,
nello swagger file bpd-hb-citizen-api.yml per il path /ranking risulta mancante la definizione del parametro fiscalCode

Michele

**Comment by DenisaBraho** [comment]
Ciao Michele,
dai nostri controlli ci risulta che la definizione del codice fiscale sia presente nel Ranking. Potreste verificare?
Grazie

**Comment by wallaroo** [comment]
Si nella versione di oggi c'è.
Grazie
