### ISSUE TITLE
Chiave pubblica pgp di cifratura

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#55]
Salve, 

nella documentazione è presente la nota: la chiave pubblica pgp di cifratura sarà condivisa a breve.

Quando sarà resa disponibile? 
i servizi in UAT possono essere usati senza la chiave? 

Grazie

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,
non abbiamo ancora un indicazione sulla data nella quale verrà resa disponibile la chiave. Vi avvisiamo appena tale informazione sarà disponibile. Per quanto riguarda i servizi in UAT, confermiamo che possono essere usati anche senza la chiave di cifratura.
Saluti
