### ISSUE TITLE
API "Enrollment strumento di pagamento di tipo Carta" return "404" in UAT

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#56]
Buongiorno,
quest'oggi effettuando dei test in **UAT** l'API:

**https://test.cstar.pagopa.it/bpd/hb/payment-instruments/{PAN}**

Restituisce **404 Not Found** sebbene la carta sia stata correttamente assegnata al profilo del cittadino

**Comment by DenisaBraho** [comment]
Ciao,
il servizio di enrollment carta corretto e aggiornato ( per enrollment carta ) è il seguente: 

https://test.cstar.pagopa.it/bpd/hb/payment-instruments**/card/**{PAN}

Vi chiediamo di effettuare una chiamata su tale servizio e procedere con l'apertura di una issue nuova, qualora dovessero esserci degli errori. 
Grazie
