### ISSUE TITLE
Grace period

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#57]
salve, 

Lato Poste si segnala criticità sul calcolo della data, è preferibile ricevere un flag in caso di Grace Period “in corso/non in corso” e non doverlo calcolare lato issuer

non potreste indicarci direttamente in un parametro se la classifica è in fase di consolidamento oppure no? 

Sconsigliamo fortemente di demandare calcoli all’issuer per evitare viste NON coordinate tra i diversi FE che espongono il medesimo servizio.

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,

potrebbe essere utile lato vostro di considerare il campo status del Periodo. In particolare, nel campo STATUS del Periodo è previsto l'invio del valore "WAITING" che indica che si è entrati nella fase di grace period (tra la fine del periodo precedente e il termine del grace Period) ossia che di conseguenza la classifica è in fase di consolidamento. Appena il GP termina, lo status dell'award period passerà a CLOSED. 
Saluti
