### ISSUE TITLE
Ricezione bonifici, utenze di test, significato del minTransactionNumber

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#58]
Buonasera

1. Il bonifico a fine concorso è comprensivo di cashback + eventuale bonus del super cashback oppure saranno due bonifici disgiunti? Se sono due bonifici disgiunti, in che modo è possibile distinguerli (oltre il valore dell'ammontare ricevuto)?
2. Com'è possibile testare i diversi scenari in cui l'utente finale può ritrovarsi? Classifica super cashback vinta/non vinta, Cashback standard ottenuto/non ottenuto, utente con T&C accettati/non accettati, ecc? Sono previste delle utenze o dei codici fiscali da utilizzare per i suddetti test?
3. Potete confermarci che nel paragrafo 1.1.9. la voce "minTransactionNumber" si riferisce al valore delle transazioni effettuate dall'ULTIMO utente premiato in classifica di super cashback (e quindi rappresenta il numero di transazioni che il cliente deve sorpassare per ottenere il super cashback)?
4. Se la nostra assunzione del punto 3 è corretta, possiamo dedurre che quindi il valore "minTransactionNumber" varierà nel tempo a seconda del comportamento dei partecipanti al concorso?

Grazie

**Comment by DenisaBraho** [comment]
Ciao Marco,
di seguito le nostre risposte:
1. il bonifico sarà comprensivo sia del cashback ed eventuale premio speciale.
2. per quanto riguarda l'utente con t&c non accettati, tale test puo essere effettuato attualmente. In merito ai test sui scenari finali di cashback vinto/non vinto; premio speciale vinto/non vinto, possiamo procedere con il censimento delle utenze a db associandoli un numero di trx che permetterebbe di testare quanto richiesto. Ci potreste fornire dei CF e PAN ( indicativamente 2/3 coppie di cf e pan) in modo da procedere con il data preparation?
3. Si, confermiamo
4. Si, esatto

**Comment by MarcoDeNovellis** [comment]
Grazie Denisa,

recupero i CF e i PAN quanto prima e ve li scrivo stesso in questo thread il prima possibile.

Grazie

**Comment by luca1oo** [comment]
Ciao, per indicare CF e PAN, scriviamo in questo thread o c'è una mail a cui scrivere?
Grazie

**Comment by DenisaBraho** [comment]
Ciao, potete indicarli in questo thread
Grazie

**Comment by luca1oo** [comment]
Anche se è un pagina pubblica, condividiamo PAN e dati anagrafici?
Grazie
Luca

**Comment by DenisaBraho** [comment]
Ciao,
 i dati dovranno essere fittizi. 
Vi confermiamo che potete inviare i CF e PAN nel seguente indirizzo mail: TeamCentroStella@sia.eu.
Procediamo con la chiusura di questa issue e appena inviata la mail, per tracciatura, vi chiediamo di aprire una nuova issue.
Grazie
