### ISSUE TITLE
Super cashback - periodo 01/12/2020 - 31/12/2020

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#59]
Salve, 

nel periodo iniziale dove il super cashback non è presente, i campi riferiti al super cashback che valore torneranno? 

Inoltre esiste un parametro che possiamo utilizzare per capire se il super cashback è previsto oppure no?

Grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao,
i campi relativi al supercashback/premio speciale sono: maxAmount (importo massimo erogabile nel periodo per il rimborso speciale) e minPosition del servizio recupero lista periodi premi. Per il periodo nel quale non sarà previsto il premio, questi parametri saranno a 0.
Per identificare il periodo privo di premio speciale, puo essere utilizzato il parametro di cui sopra: maxAmount .
Saluti
