### ISSUE TITLE
Chiarimenti - 1.1.2 Impostazione/modifica IBAN da H/M Banking

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#6]
Salve, 

contatto per Poste Italiane. 

Nel par 1.1.2  Impostazione/modifica IBAN da H/M Banking del documento "Issuer Interface Agreement_ v2" è riportato che l'utente può inserire solo IBAN a lui intestati associati esclusivamente a conti aperti presso la Banca Issuer che mette a disposizione il portale.

Cosa si intende per "Banca Issuer che mette a disposizione il portale"?

Non è chiara questa frase. Se l'utente inserisce un IBAN non di Poste e non di una Banca che mette a disposizione il portale, il servizio da voi esposto riorna qualche errore specifico? 

Resto in attesa di un vostro riscontro

Grazie

**Comment by menottistefano** [comment]
ogni banca Issuer può impostare/modificare IBAN del cittadino se l'IBAN è intestato al cittadino (nome, cognome, CF) e se il conto è della banca issuer.
per portale si intendono i touch point digitali/fisici della banca issuer
il servizio di memorizzazione IBAN effettua controlli formali sull'IBAN e tramite un serviziod i checkIBAN restituirà un esito sul controllo che l'IBAN sia effettivamente intestato a nome, congome, CF del cittadino
