### ISSUE TITLE
Gestione campi null

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#60]
Salve, 

i servizi torneranno sempre campi valorizzati? 
In caso negativo in quali casi e per quali campi tornerà un valore null? 

Grazie 

Nicola

**Comment by mdesogus** [comment]
Buongiorno,

come regola generale se un campo non è presente sulla base dati non verrà restituito, 
per una risposta dettagliata avremmo bisogno di un caso più specifico.

Grazie

**Comment by NicolaLamberti** [comment]
esempio: nel primo periodo non sarà presente il super cashback. 
I dati del super cashback (es: ranking, ecc ecc) cosa restituiranno?
