### ISSUE TITLE
Status= INACTIVE

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#61]
Salve, 

lo status del periodo = INACTIVE cosa indica? 

grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,

lo stato inactive indica i periodi futuri, non ancora attivi.
Nella nuova versione dell'IA ISSUER (che verrà condivisa entro oggi) potete trovare il dominio aggiornato di questo campo che riporto quà per comodità:

ACTIVE (periodo attivo)
INACTIVE (periodi futuri)
WAITING (tra la fine del periodo precedente e il termine del grace Period)
CLOSED (periodi precedenti)

Saluti
