### ISSUE TITLE
Campo status nel servizio di getPaymentInstrument

### ISSUE THREAD

**Issue by mrossano** [pagopa/issuer_integration#63]
Ciao,
il campo "status" ricevuto dal servizio GET /bpd/hb/payment-instruments/{id} non risulta essere in camelCase come da documentazione.

Potreste sistemare?

Ecco i dettagli:
x-request-id: 6a6c42bc-e80a-4409-b3ce-380e9d6affaf

Request
GET https://bpd-dev.azure-api.net/bpd/hb/payment-instruments/491600*****1326

Response:
{"hpan":"6007ad385dcbf6b88fb959d7b0ad4fa55c2f632558716b395c25f1b0b358beb8","fiscalCode":"PLRMRC92A01G273P","activationDate":"2020-11-18T14:06:42.293+01:00",**"Status"**:"ACTIVE"}

**Comment by DenisaBraho** [comment]
Ciao,
la documentazione IA è stata modificata inserendo modificando il nome del parametro a: "Status" nel servizio GET /bpd/hb/payment-instruments/{id} 
Saluti
