### ISSUE TITLE
Recesso servizio

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#64]
Salve, 

uno dei possibili errori che può ritornare il servizio è:

400 | TOO_MANY_CHANNELS | risultano presenti strumenti di pagamento attivi su altri canali diversi da quello dell’Issuer chiamante

L'utente quindi per poter recedere dal servizio deve prima disattivare gli strumenti di pagamento attivi su altri canali diversi da quello dell'issuer chiamante? 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,
si esatto, il cittadino puo recedere dal servizio tramite H/M solo se gli unici strumenti attivi su BPD sono sullo stesso canale dell'issuer chiamante. Per poter concludere il recesso da H/M Banking, l'utente dovrà quindi prima disattivare eventuali altri strumenti di pagamento attivi su altri canali (diversi da quello dell'issuer chiamante)
Saluti
