### ISSUE TITLE
/bpd/hb/payment-instruments/card/ - errore 

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#65]
REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card/5333171000547030

restituisce errore. 

potreste per favore verificare? 

Nicola

**Comment by NicolaLamberti** [comment]
[INFO] [Fri Nov 20 10:39:10 CET 2020] BonusPagamentiDigitaliService - enrollmentStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card/5333171000547030]
[INFO] [Fri Nov 20 10:39:10 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 2d7033ff-a785-47a4-9f7d-e958ae14499f, Content-Type: application/json]
[INFO] [Fri Nov 20 10:39:10 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card/5333171000547030
2020/11/20 10:39:10:256 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/20 10:39:10:260 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/20 10:39:10:262 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/20 10:39:10:276 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/20 10:39:10:432 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/20 10:39:10:876 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:50788<->20.54.178.216:443
2020/11/20 10:39:10:877 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/20 10:39:10:879 CET [DEBUG] wire - http-outgoing-0 >> "PUT /bpd/hb/payment-instruments/card/5333171000547030 HTTP/1.1[\r][\n]"
2020/11/20 10:39:10:879 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/20 10:39:10:879 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 2d7033ff-a785-47a4-9f7d-e958ae14499f[\r][\n]"
2020/11/20 10:39:10:880 CET [DEBUG] wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
2020/11/20 10:39:10:881 CET [DEBUG] wire - http-outgoing-0 >> "Content-Length: 189[\r][\n]"
2020/11/20 10:39:10:881 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/20 10:39:10:882 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/20 10:39:10:882 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/20 10:39:10:882 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/20 10:39:10:883 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/20 10:39:10:885 CET [DEBUG] wire - http-outgoing-0 >> "{"fiscalCode":"RSSNEE99A01H501L","exprireMonth":"12","channel":"APP","issuerAbiCode":"00000","type":"PP","activationDate":"2020-11-20T10:39:10+01:00","expireYear":"22","brand":"MASTERCARD"}"
2020/11/20 10:39:13:873 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2020/11/20 10:39:13:874 CET [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
2020/11/20 10:39:13:874 CET [DEBUG] wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
2020/11/20 10:39:13:874 CET [DEBUG] wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2020/11/20 10:39:13:874 CET [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
2020/11/20 10:39:13:875 CET [DEBUG] wire - http-outgoing-0 << "Expires: 0[\r][\n]"
2020/11/20 10:39:13:875 CET [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2020/11/20 10:39:13:875 CET [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2020/11/20 10:39:13:875 CET [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
2020/11/20 10:39:13:876 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/20 10:39:13:876 CET [DEBUG] wire - http-outgoing-0 << "Date: Fri, 20 Nov 2020 09:39:13 GMT[\r][\n]"
2020/11/20 10:39:13:876 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/20 10:39:13:877 CET [DEBUG] wire - http-outgoing-0 << "2D[\r][\n]"
2020/11/20 10:39:13:877 CET [DEBUG] wire - http-outgoing-0 << "{"activationDate":"2020-11-20T09:39:11.745Z"}[\r][\n]"
[INFO] [Fri Nov 20 10:39:13 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPONSE - HTTP STATUS[200]
[INFO] [Fri Nov 20 10:39:13 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPONSE - HTTP ENTITY[{"activationDate":"2020-11-20T09:39:11.745Z"}]

**Comment by NicolaLamberti** [comment]
adesso restituisce un altro errore


[INFO] [Fri Nov 20 18:15:30 CET 2020] BonusPagamentiDigitaliService - enrollmentStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card/5333171000547030]
[INFO] [Fri Nov 20 18:15:30 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 3149dc68-3a42-4bea-b0a7-2ac11a2c8dc8, Content-Type: application/json]
[INFO] [Fri Nov 20 18:15:30 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQUEST PAYLOAD - {"fiscalCode":"RSSNEE99A01H501L","exprireMonth":"12","channel":"APP","issuerAbiCode":"00000","type":"PP","activationDate":"2020-11-20T18:15:30+01:00","expireYear":"22","brand":"MASTERCARD"}
2020/11/20 18:15:30:685 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/20 18:15:30:688 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/20 18:15:30:689 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/20 18:15:30:705 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/20 18:15:30:989 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/20 18:15:31:572 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:54534<->20.54.178.216:443
2020/11/20 18:15:31:573 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/20 18:15:31:576 CET [DEBUG] wire - http-outgoing-0 >> "PUT /bpd/hb/payment-instruments/card/5333171000547030 HTTP/1.1[\r][\n]"
2020/11/20 18:15:31:577 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/20 18:15:31:578 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 3149dc68-3a42-4bea-b0a7-2ac11a2c8dc8[\r][\n]"
2020/11/20 18:15:31:578 CET [DEBUG] wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
2020/11/20 18:15:31:579 CET [DEBUG] wire - http-outgoing-0 >> "Content-Length: 189[\r][\n]"
2020/11/20 18:15:31:579 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/20 18:15:31:579 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/20 18:15:31:580 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/20 18:15:31:580 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/20 18:15:31:581 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/20 18:15:31:581 CET [DEBUG] wire - http-outgoing-0 >> "{"fiscalCode":"RSSNEE99A01H501L","exprireMonth":"12","channel":"APP","issuerAbiCode":"00000","type":"PP","activationDate":"2020-11-20T18:15:30+01:00","expireYear":"22","brand":"MASTERCARD"}"
2020/11/20 18:15:32:075 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
2020/11/20 18:15:32:075 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 111[\r][\n]"
2020/11/20 18:15:32:076 CET [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
2020/11/20 18:15:32:076 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/20 18:15:32:076 CET [DEBUG] wire - http-outgoing-0 << "Date: Fri, 20 Nov 2020 17:15:31 GMT[\r][\n]"
2020/11/20 18:15:32:077 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/20 18:15:32:077 CET [DEBUG] wire - http-outgoing-0 << "{ "statusCode": 500, "message": "Internal server error", "activityId": "70f1be39-e1ff-48e4-bd23-3c3cb56fbef9" }"
2020/11/20 18:15:32:090 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/20 18:15:32:090 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Fri Nov 20 18:15:32 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPONSE - HTTP STATUS[500]
[INFO] [Fri Nov 20 18:15:32 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPONSE - HTTP ENTITY[{ "statusCode": 500, "message": "Internal server error", "activityId": "70f1be39-e1ff-48e4-bd23-3c3cb56fbef9" }]
[DEBUG] [Fri Nov 20 18:15:32 CET 2020] BonusPagamentiDigitaliService - enrollmentStrumentoPagamento-PUT [{
   "activityId": "70f1be39-e1ff-48e4-bd23-3c3cb56fbef9",
   "message": "Internal server error",
   "statusCode": 500

**Comment by DenisaBraho** [comment]
Ciao Nicola,
abbiamo risolto l'anomalia. Potresti verifcare se il servizio adesso funziona correttamente?
in attesa di un riscontro
Saluti

**Comment by NicolaLamberti** [comment]
adesso questo servizio funziona
