### ISSUE TITLE
Attivazione subscription key

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#67]
Buongiorno, abbiamo verificato che le nostre chiavi di sottoscrizione per gli ambienti UAT e Produzione sono ancora in stato "Submitted": il passaggio ad "Active" sarà automatico o sono necessari degli interventi lato nostro? In caso fosse automatico, per quando è prevista l'attivazione? Grazie

Andrea

**Comment by mdesogus** [comment]
Buongiorno,

a fine di verifica, ci indichereste il nominativo della sottoscrizione effettuata?

Grazie

**Comment by AndreaCaccin** [comment]
yapuat e yapprod.
Grazie

**Comment by mdesogus** [comment]
abbiamo provveduto ad attivare le utenze per entrambi gli ambienti.

Grazie e buona giornata
