### ISSUE TITLE
Domande su API Enrollment strumento di pagamento 

### ISSUE THREAD

**Issue by mrossano** [pagopa/issuer_integration#68]
Ciao,
una volta ricevute le chiavi PGP per la cifratura delle chiavi, cosa succede a tutti coloro che chiamano il servizio senza cifratura? Riceveranno errore quindi la soluzione non è seamless?

**Comment by DenisaBraho** [comment]
Ciao, 
si, confermiamo che verrà generato un errore.
Saluti
