### ISSUE TITLE
Disattivazione strumento di pagamento

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#69]
salve, 

riceviamo il seguente errore

[DEBUG] [Fri Nov 20 10:40:04 CET 2020] DisabilitazioneStrumentoPagamentoCashBackCommand - DisabilitazioneStrumentoPagamentoRequest{pan='5333171000547030'} org.jod.cashback.dto.bonuspagamentidigitali.disabilitazionestrumentopagamento.v1.DisabilitazioneStrumentoPagamentoRequest@20d525
[DEBUG] [Fri Nov 20 10:40:04 CET 2020]  START BonusPagamentiDigitaliService - disabilitazioneStrumentoPagamento
[INFO] [Fri Nov 20 10:40:04 CET 2020] BonusPagamentiDigitaliService - disabilitazioneStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030]
[INFO] [Fri Nov 20 10:40:04 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 36d5cf16-f126-445c-8940-0aa3842afa8c]
[INFO] [Fri Nov 20 10:40:04 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030
2020/11/20 10:40:04:698 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/20 10:40:04:702 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/20 10:40:04:705 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/20 10:40:04:725 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/20 10:40:04:736 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/20 10:40:05:020 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:50809<->20.54.178.216:443
2020/11/20 10:40:05:021 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/20 10:40:05:023 CET [DEBUG] wire - http-outgoing-0 >> "DELETE /bpd/hb/payment-instruments/5333171000547030 HTTP/1.1[\r][\n]"
2020/11/20 10:40:05:023 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/20 10:40:05:024 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 36d5cf16-f126-445c-8940-0aa3842afa8c[\r][\n]"
2020/11/20 10:40:05:025 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/20 10:40:05:025 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/20 10:40:05:026 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/20 10:40:05:026 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/20 10:40:05:026 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/20 10:40:05:308 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 404 Not Found[\r][\n]"
2020/11/20 10:40:05:308 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
2020/11/20 10:40:05:309 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/20 10:40:05:309 CET [DEBUG] wire - http-outgoing-0 << "Date: Fri, 20 Nov 2020 09:40:04 GMT[\r][\n]"
2020/11/20 10:40:05:310 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/20 10:40:05:317 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/20 10:40:05:318 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Fri Nov 20 10:40:05 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE RESPONSE - HTTP STATUS[404]
[INFO] [Fri Nov 20 10:40:05 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE RESPONSE - HTTP ENTITY[]

**Comment by NicolaLamberti** [comment]
[INFO] [Fri Nov 20 18:17:44 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 90185df0-1c79-4dfe-a241-4a40f7d88264]
[INFO] [Fri Nov 20 18:17:44 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030
2020/11/20 18:17:44:036 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/20 18:17:44:041 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/20 18:17:44:043 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/20 18:17:44:064 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/20 18:17:44:074 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/20 18:17:44:589 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:54583<->20.54.178.216:443
2020/11/20 18:17:44:590 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/20 18:17:44:596 CET [DEBUG] wire - http-outgoing-0 >> "DELETE /bpd/hb/payment-instruments/5333171000547030 HTTP/1.1[\r][\n]"
2020/11/20 18:17:44:597 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/20 18:17:44:598 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 90185df0-1c79-4dfe-a241-4a40f7d88264[\r][\n]"
2020/11/20 18:17:44:598 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/20 18:17:44:598 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/20 18:17:44:599 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/20 18:17:44:601 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/20 18:17:44:602 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/20 18:17:45:115 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
2020/11/20 18:17:45:116 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
2020/11/20 18:17:45:116 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/20 18:17:45:116 CET [DEBUG] wire - http-outgoing-0 << "Date: Fri, 20 Nov 2020 17:17:44 GMT[\r][\n]"
2020/11/20 18:17:45:116 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/20 18:17:45:126 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/20 18:17:45:127 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Fri Nov 20 18:17:45 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE RESPONSE - HTTP STATUS[500]
[INFO] [Fri Nov 20 18:17:45 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE RESPONSE - HTTP ENTITY[]

**Comment by DenisaBraho** [comment]
Ciao Nicola,
il servizio adesso dovrebbe funzionare correttamente.
Potreste verificare?
In attesa di un feedback
Grazie

**Comment by NicolaLamberti** [comment]
la disattivazione adesso funziona

Grazie
