### ISSUE TITLE
Chiarimenti funzionali

### ISSUE THREAD

**Issue by luca1oo** [pagopa/issuer_integration#7]
Buonasera, si riportano alcuni chiarimenti sulla meccanica:
(1) La sottoscrizione T&C sono relative al canale Banca o sono in comune con AppIO / Altre banche? Cioè se il cliente ha già sottoscritto da AppIO o altra banca devo rifarle?
(2) Le carte / IBAN inserite tramite AppIO le vedrò anche su HB Banca?
(3) Posso eliminare carta da HB anche se inserita da AppIO? Viceversa?
(4) Se un cliente non ha inserito IBAN cosa succede alla data dell’invio cashback? L'inserimento dell'IBAN è mandatorio?
(5) Se invece ha inserito IBAN non deve fare altre azioni e il cashback arriva in automatico?
(6) ApplePay e GooglePay ancora da definire, nel frattempo possiamo passare i Token?

Grazie

**Comment by menottistefano** [comment]
1. no, ha già accettato T&C e la chiamata statusCitizen restituisce l'info che l'utente è già iscritto
2. no
3. no, ogni issuer può eliminare solo i proprio strumenti di pagamento. dall'App IO è possibile eliminare/modificare carte e IBAN
4. l'inserimento dell'IBAN lato Issuer è mandatorio (se il cittadino non l'ha già inserito, l'informazione è restituita dalla chiamata statusCitizen
5. corretto
6. lato Acquirer le transazioni che saranno inviate al centrostella dovranno contenere anche le trx fatte con Apple e Google Pay, veicolando il PAN tokenizzato (unico conosciuto dall'acquirer)
7. nel caso in cui si parli della componente Issuer, se in possesso del PAN tokenizzato, può enrollare anche quello strumento

**Comment by luca1oo** [comment]
2. e 3. Questo significa che l'issuer può far vedere e gestire solo i PAN passati dalle sue proporties, ma cosa c’è su APP IO dei PAN dell'issuer non è possibile saperlo? Dalla documentazione ci si aspettva di ricevere l’informazione del PAN nel metodo payment-instruments anche se carta sottoscritta da AppIO
7. In riferimento alla componente issuer, se il cliente è in possesso del PAN tokenizzato e enrolla tale strumento, su App IO cosa visualizzerà? O non visulizzerà i PAN tokenizzati perchè saranno filtrati?

**Comment by menottistefano** [comment]
la piattaforma non memorizza i PAN delle carte ma solo Hash degli stessi. per motivi di privacy la piattaforma non restituirà ai soggetti issuer informazioni dei cittadini se non già in possesso dell'issuer stesso

la gestione/visualizzazione su App io delle carte tokenizzate è ancora in fase di studio
