### ISSUE TITLE
Status Strumento Pagamento H/M Banking inconsistenza documentazione e API

### ISSUE THREAD

**Issue by antessio** [pagopa/issuer_integration#71]
Facendo riferimento al PDF: 
https://github.com/pagopa/issuer_integration/blob/master/ops_resources/Issuer%20Interface%20Agreement_v2.pdf

>id : id dello strumento di pagamento, che corrisponde al PAN (Primary Account Number) del metodo di pagamento

mentre sul portale:
https://bpd-dev.developer.azure-api.net/api-details#api=bpd-hb-payment-instruments-api&operation=statuspaymentinstrumenthb

>id dello strumento di pagamento, che corrisponde all'hash del PAN (Primary Account Number) del metodo di pagamento

In SIT l'API restituisce il risultato utilizzando come id il PAN, in UAT la stessa API restituisce un 500 usando il PAN. 

Qual'è l'interfaccia finale di questa API?

**Comment by mdesogus** [comment]
Buongiorno,

sarebbe possibile rieseguire il test e darci riscontro?

grazie

**Comment by antessio** [comment]
La chiamata ora restituisce il risultato atteso. 

E' confermato che il path param `id` è il PAN e non l'hash del PAN?

Grazie

**Comment by DenisaBraho** [comment]
Ciao
si, l'id corrisponde al PAN. Abbiamo provveduto a modificare la descrizione campo "id" nel portale.
Saluti
