### ISSUE TITLE
method statusStrumentoPagamento - errore 404 

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#72]
errore 404

[INFO] [Fri Nov 20 21:21:41 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547031]
[INFO] [Fri Nov 20 21:21:41 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 5bd9e0a9-ec9f-422b-9b4b-3f4020002522]
[INFO] [Fri Nov 20 21:21:41 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547031
2020/11/20 21:21:42:008 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/20 21:21:42:017 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/20 21:21:42:019 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/20 21:21:42:041 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/20 21:21:42:053 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/20 21:21:42:475 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.43.106:51245<->20.54.178.216:443
2020/11/20 21:21:42:476 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/20 21:21:42:479 CET [DEBUG] wire - http-outgoing-0 >> "GET /bpd/hb/payment-instruments/5333171000547031 HTTP/1.1[\r][\n]"
2020/11/20 21:21:42:479 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/20 21:21:42:480 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 5bd9e0a9-ec9f-422b-9b4b-3f4020002522[\r][\n]"
2020/11/20 21:21:42:480 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/20 21:21:42:481 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/20 21:21:42:481 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/20 21:21:42:481 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/20 21:21:42:481 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/20 21:21:43:152 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 404 Not Found[\r][\n]"
2020/11/20 21:21:43:152 CET [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
2020/11/20 21:21:43:153 CET [DEBUG] wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
2020/11/20 21:21:43:153 CET [DEBUG] wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2020/11/20 21:21:43:153 CET [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
2020/11/20 21:21:43:154 CET [DEBUG] wire - http-outgoing-0 << "Expires: 0[\r][\n]"
2020/11/20 21:21:43:154 CET [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2020/11/20 21:21:43:154 CET [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2020/11/20 21:21:43:154 CET [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
2020/11/20 21:21:43:155 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/20 21:21:43:155 CET [DEBUG] wire - http-outgoing-0 << "Date: Fri, 20 Nov 2020 20:21:43 GMT[\r][\n]"
2020/11/20 21:21:43:155 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/20 21:21:43:156 CET [DEBUG] wire - http-outgoing-0 << "B6[\r][\n]"
2020/11/20 21:21:43:156 CET [DEBUG] wire - http-outgoing-0 << "{"returnMessages":{"ERROR":[{"message":"il campo %s supporta solamente il tipo %s","messageTitle":"Risorsa non trovata","messageKey":"resource.not-found.error","severity":"ERROR"}]}}[\r][\n]"
2020/11/20 21:21:43:176 CET [DEBUG] wire - http-outgoing-0 << "0[\r][\n]"
[INFO] [Fri Nov 20 21:21:43 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP STATUS[404]
[INFO] [Fri Nov 20 21:21:43 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP ENTITY[{"returnMessages":{"ERROR":[{"message":"il campo %s supporta solamente il tipo %s","messageTitle":"Risorsa non trovata","messageKey":"resource.not-found.error","severity":"ERROR"}]}}]
2020/11/20 21:21:43:177 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/20 21:21:43:177 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/20 21:21:43:178 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[DEBUG] [Fri Nov 20 21:21:43 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento-GET [{"returnMessages": {"ERROR": [{
   "severity": "ERROR",
   "messageKey": "resource.not-found.error",
   "messageTitle": "Risorsa non trovata",
   "message": "il campo %s supporta solamente il tipo %s"
}]}}]

**Comment by NicolaLamberti** [comment]
se una carta non censita sui vostri portali ci date 404. questo errore non è descritto nella documentazione. Potreste indicarci come gestire questa casistica?

**Comment by DenisaBraho** [comment]
Ciao Nicola,
l'errore inviato 404 è da ritenersi corretto per la casistica di cui sopra. Provvederemo ad aggiornare l'IA aggiungendo anche questo errore.
Saluti
