### ISSUE TITLE
Enroll di una seconda carta produce errore: "il campo %s supporta solamente il tipo %s"

### ISSUE THREAD

**Issue by albertosangalliflowe** [pagopa/issuer_integration#73]
Effettuando l'enroll di una seconda carta di debito (DEB) o credito (CRD) o Prepagata (PP) per un profilo che già possiede una Carta di Debito si riceve l'errore "il campo %s supporta solamente il tipo %s"

Qui i dettagli:
PUT - https://bpd-dev.azure-api.net/bpd/hb/payment-instruments/card/1234567890123457

{
    "fiscalCode": "AAABBB11X11X111X",
    "expireYear": 2025,
    "exprireMonth": 12,
    "issuerAbiCode": "36003",
    "brand": "Mastercard",
    "holder": "Alberto Rossi",
    "type": "CRD",
    "channel": "36003"
}

Response:
{
    "returnMessages": {
        "ERROR": [
            {
                "message": "il campo %s supporta solamente il tipo %s",
                "messageTitle": "Risorsa non trovata",
                "messageKey": "resource.not-found.error",
                "severity": "ERROR"
            }
        ]
    }
}

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo provveduto a sanare l'anomalia. Abbiamo verificato che in SIT il servizio attualmente funziona correttamente.
Saluti
