### ISSUE TITLE
Status strumento di pagamento non censito - errore 404

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#74]
Salve, 

prima dell'attivazione/Disattivazione delle carte noi invochiamo lo status dello strumento di pagamento. 
Il servizio ci restituisce 404. 

di seguito gli step del test: 
1.	Faccio la richiesta dello stato di una carta X mai censita su pagoPa e ottengo un 404.
2.	La stessa carta X del punto precedente la attivo e l’attivazione va a buon fine
3.	Faccio la richiesta dello stato della stessa carta X del punto 1 e 2 ed ottengo come risposta che la carta è attiva
4.	Disabilito la carta X del punto 1,2 e 3 ed ottengo come risposta un OK
5.	Faccio la richiesta dello stato della carta X del punto 1,2,3 e 4 ed ottengo come risposta che la carta è disattiva

di seguito le nostre domande:
1) l'errore non è presente nella vostra documentazione, potreste per favore aggiornarla
2) è corretto gestire questa casistica come strumento non attivo cioè non associato al cashback? 

Grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,
1. l'errore inviato 404 è da ritenersi corretto per la casistica di cui sopra. Provvederemo ad aggiornare l'IA aggiungendo anche questo errore. 2. Si, corretto.
Saluti
