### ISSUE TITLE
Termini e condizioni

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#75]
Salve, 

possiamo far vedere questo:
https://prod.cstar.pagopa.it/bpd/tc/html
 
direttamente in webview?

attualmente in collaudo non è presente nessun testo. Corretto? 

Grazie 

Nicola

**Comment by mdesogus** [comment]
buongiorno,

il link dell'ambiente di collaudo su cui è esposto il T&C è il seguente:
https://test.cstar.pagopa.it/bpd/tc/html

grazie
