### ISSUE TITLE
Disattivazione Postamat - errore

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#76]
Salve, proviamo a disabilitare una carta Postamat 5354760568760185 ma questa risulta sempre attiva nonostante la disattivazione vada a buon fine. 
CF: FLVNDR89B27F839K

di seguito i log. 

queste carte non vengono disabilitate nonostante la chiamata di disabilitazione vada a buon fine. E’stato cambiato qualcosa lato pagoPa?
Di seguito il log di disabilitazione e poi di status

**DISATTIVAZIONE:** 

[INFO] [Mon Nov 23 16:08:45 CET 2020] BonusPagamentiDigitaliService - disabilitazioneStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5354760568760185]
[INFO] [Mon Nov 23 16:08:45 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: d46caa37-d2d5-4309-9ac9-88fee3569afc]
[INFO] [Mon Nov 23 16:08:45 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5354760568760185
2020/11/23 16:08:45:497 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/23 16:08:45:504 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/23 16:08:45:506 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/23 16:08:45:551 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/23 16:08:45:691 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/23 16:08:45:986 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:51603<->20.54.178.216:443
2020/11/23 16:08:45:986 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/23 16:08:45:989 CET [DEBUG] wire - http-outgoing-0 >> "DELETE /bpd/hb/payment-instruments/5354760568760185 HTTP/1.1[\r][\n]"
2020/11/23 16:08:45:990 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/23 16:08:45:990 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: d46caa37-d2d5-4309-9ac9-88fee3569afc[\r][\n]"
2020/11/23 16:08:45:991 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/23 16:08:45:992 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/23 16:08:45:993 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/23 16:08:45:995 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/23 16:08:45:999 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/23 16:08:46:304 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 204 No Content[\r][\n]"
2020/11/23 16:08:46:304 CET [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
2020/11/23 16:08:46:304 CET [DEBUG] wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
2020/11/23 16:08:46:304 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
2020/11/23 16:08:46:305 CET [DEBUG] wire - http-outgoing-0 << "Expires: 0[\r][\n]"
2020/11/23 16:08:46:306 CET [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2020/11/23 16:08:46:306 CET [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2020/11/23 16:08:46:306 CET [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
2020/11/23 16:08:46:307 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/23 16:08:46:308 CET [DEBUG] wire - http-outgoing-0 << "Date: Mon, 23 Nov 2020 15:08:43 GMT[\r][\n]"
2020/11/23 16:08:46:308 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/23 16:08:46:324 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/23 16:08:46:324 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Mon Nov 23 16:08:46 CET 2020] BonusPagamentiDigitaliService.disabilitazioneStrumentoPagamento - exec-time [884 ms] - result [DisabilitazioneStrumentoPagamentoResponse{} AOutput{resultCode=0, httpResultCode='204', returnMessage='OK', description='null', errorCode='null', errorMap={}}]

**sTATUS:** 

[INFO] [Mon Nov 23 16:09:22 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5354760568760185]
[INFO] [Mon Nov 23 16:09:22 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 76665f48-88cb-4046-9a7e-5a79d44e643e]
[INFO] [Mon Nov 23 16:09:22 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5354760568760185
2020/11/23 16:09:22:698 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/23 16:09:22:702 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/23 16:09:22:704 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/23 16:09:22:747 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/23 16:09:22:757 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/23 16:09:23:016 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:51619<->20.54.178.216:443
2020/11/23 16:09:23:017 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/23 16:09:23:019 CET [DEBUG] wire - http-outgoing-0 >> "GET /bpd/hb/payment-instruments/5354760568760185 HTTP/1.1[\r][\n]"
2020/11/23 16:09:23:020 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/23 16:09:23:021 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 76665f48-88cb-4046-9a7e-5a79d44e643e[\r][\n]"
2020/11/23 16:09:23:021 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/23 16:09:23:021 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/23 16:09:23:022 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/23 16:09:23:022 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/23 16:09:23:022 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/23 16:09:23:326 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2020/11/23 16:09:23:326 CET [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
2020/11/23 16:09:23:327 CET [DEBUG] wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
2020/11/23 16:09:23:327 CET [DEBUG] wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2020/11/23 16:09:23:327 CET [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
2020/11/23 16:09:23:328 CET [DEBUG] wire - http-outgoing-0 << "Expires: 0[\r][\n]"
2020/11/23 16:09:23:328 CET [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2020/11/23 16:09:23:329 CET [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2020/11/23 16:09:23:329 CET [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
2020/11/23 16:09:23:329 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/23 16:09:23:330 CET [DEBUG] wire - http-outgoing-0 << "Date: Mon, 23 Nov 2020 15:09:20 GMT[\r][\n]"
2020/11/23 16:09:23:331 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/23 16:09:23:332 CET [DEBUG] wire - http-outgoing-0 << "A9[\r][\n]"
2020/11/23 16:09:23:332 CET [DEBUG] wire - http-outgoing-0 << "{"hpan":"cc69604c3ed0f5104b751c69aea6945c24cea93279d082e4d4a389773d1bcf1d","fiscalCode":"FLVNDR89B27F839K","activationDate":"2020-11-17T16:50:00.727Z","Status":"ACTIVE"}[\r][\n]"
[INFO] [Mon Nov 23 16:09:23 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP STATUS[200]
[INFO] [Mon Nov 23 16:09:23 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP ENTITY[{"hpan":"cc69604c3ed0f5104b751c69aea6945c24cea93279d082e4d4a389773d1bcf1d","fiscalCode":"FLVNDR89B27F839K","activationDate":"2020-11-17T16:50:00.727Z","Status":"ACTIVE"}]
2020/11/23 16:09:23:349 CET [DEBUG] wire - http-outgoing-0 << "0[\r][\n]"
2020/11/23 16:09:23:349 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/23 16:09:23:350 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/23 16:09:23:351 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[DEBUG] [Mon Nov 23 16:09:23 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento-GET [{
   "Status": "ACTIVE",
   "hpan": "cc69604c3ed0f5104b751c69aea6945c24cea93279d082e4d4a389773d1bcf1d",
   "fiscalCode": "FLVNDR89B27F839K",
   "activationDate": "2020-11-17T16:50:00.727Z"
}]

**Comment by mdesogus** [comment]
Buongiorno, 

sarebbe possibile rieseguire il test e fornirci riscontro?

grazie

**Comment by DenisaBraho** [comment]
Ciao Nicola,
il servizio attualmente ci risulta che funziona correttamente. 
Procediamo con la chiusura della issue, qualora si presentasse un errore vi pregiamo di aprire una nuova issue
Saluti
