### ISSUE TITLE
il servizio di enrollment dello strumento di pagamento ritorna status 404

### ISSUE THREAD

**Issue by luca-delgiudice-dev** [pagopa/issuer_integration#77]
Ciao,
in ambiente SIT, il servizio di enrollment dello strumento di pagamento per l'utente CRZGNN91R30A221V ritorna errore 404 con messaggio "il campo %s supporta solamente il tipo %s".

Potete verificare?
L'ultima chiamata è stata effettuata in data 2020-11-23 16:28

LOGS:

endpoint https://bpd-dev.azure-api.net/bpd/hb/payment-instruments/card/533004******7197

metodo PUT

body:
{ "fiscalCode": "CRZGNN91R30A221V", "expireYear": "23", "expireMonth": "12", "issuerAbiCode": "32875", "brand": "MASTERCARD", "holder": "Giovanni Carzolio", "type": "PP", "channel": "32875"}

risposta:
status 404 - response {"returnMessages":{"ERROR":[{"message":"il campo %s supporta solamente il tipo %s","messageTitle":"Risorsa non trovata","messageKey":"resource.not-found.error","severity":"ERROR"}]}}

grazie,
Luca

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo provveduto a sanare l'anomalia. Abbiamo verificato che in SIT il servizio attualmente funziona correttamente. Potreste verificare?
Saluti

**Comment by luca-delgiudice-dev** [comment]
Ciao,
abbiamo riprovato e confermo che ha funzionato correttamente.
{
    activationDate: 2020-11-24T10:09:27.057+01:00
}

grazie,
Luca

**Comment by mdesogus** [comment]
Buongiorno,

a seguito di esito positivo procediamo con la chiusura della segnalazione.

Grazie
