### ISSUE TITLE
recesso - errore TOO_MANY_CHANNELS

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#78]
Salve, 

oltre alle seguenti informazioni "400 | TOO_MANY_CHANNELS"  inviate anche un testo specifico per questo errore? Se si, qual è? 

Nicola

**Comment by DenisaBraho** [comment]
Ciao,
atttualmente viene restituito un generico "impossible to delete Payment method" con il codice di errore
Saluti
