### ISSUE TITLE
Enrollment strumento di pagamento - campo Channel

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#79]
Salve, 

per le App finanziare del gruppo Poste, confermate che vi aspettate la valorizzazione del campo "channel" come descritto di seguito? 

- app BancoPosta channel=07601
- app Postepay channel=36081

grazie 

Nicola

**Comment by lucasomarugasia** [comment]
Per uniformità con l'identificazione di Poste lato acquiring suggeriamo di utilizzare la sola valorizzazione "36081", anche se funzionalmente non ottimale.
