### ISSUE TITLE
Super bonus finale

### ISSUE THREAD

**Issue by luca1oo** [pagopa/issuer_integration#8]
Buonasera, chiediamo gentilmente conferma che al super bonus finale si acceda con almeno 50 transazione al semestre o 100 annue?  40 transazioni nel primo semestre e 60 nel secondo semestre, permettono al cittadino di partecipare al superbonus?
Grazie

**Comment by menottistefano** [comment]
ciao, le regole non sono ancora definitive. gli organi competenti le approveranno a breve.
in ogni caso questi valori saranno restituiti anche dalle API esposte dalla piattaforma
