### ISSUE TITLE
Iscrizione sistema di pagamento - produzione

### ISSUE THREAD

**Issue by AndreaCaccin** [pagopa/issuer_integration#80]
Buonasera, provando ad aggiungere una carta in ambiente di produzione, su un utente iscritto al beta test, riceviamo http status 404 - Not Found, senza response body

- Il servizio è già attivo in ambiente di produzione? 
- vista l'assenza delle chiavi pgp, inizialmente saranno abilitate le chiamate coi dati carta in chiaro?

I dati delle chiamate di prova, per le vostre verifiche, sono
- subscriptionKey: 9fb41939931e4834baa441d218d45597
- orario: Mon, 23 Nov 2020 19:53:49 GMT

Grazie

**Comment by lucasomarugasia** [comment]
I servizi non sono disponibili in ambiente di produzione. Potete al momento testare fino in UAT.
