### ISSUE TITLE
Informativa trattamento dati personali

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#83]
Oltre il documento di Termini e Condizioni ottenibile dall'API specificata al punto 1.1.1 del vostro documento di specifiche, avete pianificato di fornire anche un documento di **Informativa sul trattamento dei dati personali**?

Grazie

**Comment by lucasomarugasia** [comment]
Buongiorno, 
si è prevista informativa su trattamento dei dati personali per il portale sviluppatori. Il testo è già pubblicato in ambiente di UAT: 
https://developer-test.cstar.pagopa.it/

**Comment by MarcoDeNovellis** [comment]
Quindi dobbiamo assumere che il testo del link al trattamento dei dati della privacy non cambi mai?
Non sono previste API per fornirci il testo in questione?

**Comment by lucasomarugasia** [comment]
corretto, al momento è così, il testo è fisso e non dovrebbe cambiare. 
Confermo che al momento non sono previste API per fornire il testo per portale sviluppatori e il testo sarà il medesimo per l'ambiente di produzione
