### ISSUE TITLE
Info sul parametro minTransactionNumber, Grace period, maxAmount vs maxPeriodCashback e CF non accettabili

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#84]
1. Da alcuni test abbiamo notato che il parametro minTransactionNumber non viene valorizzato quando chiamato tramite l'API del paragrafo 1.1.9.
è un bug?

Inoltre il parametro minTransactionNumber è presente nel body di due API diverse (1.1.8 e 1.1.9), avendo lo stesso nome può portare confusione poichè il suo significato cambia a seconda dell'API da cui viene chiamata.
Confermate che sono due significati diversi collegati allo stesso nome minTransactionNumber?
- 1.1.8 = Numero minimo di transazioni per accedere al cashback
- 1.1.9 = Numero minimo di transazioni effettuate dagli utenti che rientrano nel "rimborso speciale"

2. Altra domanda: al termine di ogni periodo è previsto un lasso di tempo di grace period. Ci confermate che potremmo avere il nuovo award period attivo contemporaneamente al grace period dell'award period precedente?
Esempio: 
- **Award period 1** (01/01/2021 - 30/06/2021) con relativo Grace period (01/07/2021 - 05/07/2021)
- Il successivo **Award period 2** inizierà il 01/07/2021 oppure può iniziare solo alla fine del grace period precedente e quindi il 06/07/2021?

3. Ancora un altra domanda, dall'API 1.1.8 qual è la differenza tra maxAmount e maxPeriodCashback? Potreste fornirci un esempio per favore?

4. Sono previsti dei casi in cui l'utente NON si può registrare? Se sì, quali sono gli scenari? In che modo ci comunicate che il Codice Fiscale non può essere registrato all'iniziativa di Cashback?

5. In che modo si può evincere che in un awardPeriod NON è presente il super cashback? Lo si evince dal fatto che non sarà fornito il parametro ranking? O altro?

Grazie

**Comment by DenisaBraho** [comment]
Ciao,
rispondiamo per punti:
1.  abbiamo sanato l'anomalia circa la visualizzazione del campo indicato. Adesso il campo dovrebbe risultare valorizzato. Confermiamo inoltre che i significati dei campi indicati son diversi. In particolare, il primo (1.1.8) è un parametro fisso che indica il numero minimo delle trx che l'utente deve aver fatto per ricevere il cashback standard (es. 50), mentre Il campo minTransactionNumber (paragrafo 1.1.9) rappresenta il numero delle trx fatte dall'ultimo utente che è rientra nel rimborso speciale, ossia il numero di trx che l'utente deve superare per poter ricevere il premio speciale. Questo sarà di conseguenza  variabile.
2. L'award period 1 durante la durata del grace period, avrà uno status = "WAITING", che significa che saranno ancora prese in considerazione e contribuiscono alla generazione del cashback le trx fatte entro 30/06/2021 ma che arrivano su BPD oltre il 30/06/21. Tuttavia, il periodo attivo sarà quello del award period 2 che avrà uno stato "ACTIVE" a partire dal 01/07/2021.
3. il Campo maxAmount identifica l'ammontare del super cashback. Se quel campo è 0 vuol dire che per quel periodo non è previsto un super bonus, in caso contrario sarà valorizzato con l'ammontare del premio speciale del periodo (es. 1500). il parametro "Max period Cashback" è il massimo accumulabile per l’intero periodo a livello di cashback (es. 150) 
4. Il cittadino in possesso di uno SPID, di età maggiorene ed eventualmente intestatario di uno strumento di pagamento emesso da un Issuer, puo iscriversi a BPD. 
5.  Tramite il campo maxAmount (1.1.8) = 0. Inoltre nel Ranking (1.1.9) i campi relativi come es: posizione (ranking) maxTransactionNumber e minTransactionNumber saranno inviati a 0.

**Comment by MarcoDeNovellis** [comment]
@DenisaBraho grazie per le risposte.
Una delucidazione in più sul punto 4. 
Sulla documentazione non è scritto da nessuna parte che l'issuer deve valutare se l'utente è in possesso dello SPID. La mia domanda è riferita dal punto di vista dell'issuer. 
"Sono previsti dei casi in cui l'utente NON si può registrare tramite issuer? Se sì, quali sono gli scenari? Visto che l'issuer fornisce a PagoPA il codice fiscale, in che modo PagoPA ci comunica che il Codice Fiscale non può essere registrato all'iniziativa di Cashback? Prevedete di passarci un errore ad hoc?"

Grazie

**Comment by lucasomarugasia** [comment]
Buongiorno, rettifico il punto 4.
Dal punto di vista del sogetto issuer è corretto, non è necessario che l'utente sia in possesso dello SPID. Per l'autenticazione è sufficiente il metodo di autenticazione forte previsto dai suoi touch point.
I controlli circa la possibilità o meno del cittadino di poter aderire al programma cashback sono in capo al soggetto issuer, così come sono in capo ad appIO. Centro Stella non effetta alcun controllo, pertanto non è previsto un servizio che, dato in input un CF, restituisca l'esito dei controlli.
I vincoli sul cittadino per la partecipazione al servizio sono: maggiorenne, residente in Italia
