### ISSUE TITLE
Utenze di test

### ISSUE THREAD

**Issue by luca1oo** [pagopa/issuer_integration#86]
CIao, inviata mail per le utenze di test per simulare cashback e supercahbacl. Email del 24/11 ore 16:53.
Grazie
Luca

**Comment by mdesogus** [comment]
Buongiorno,

a seguito di risposta fornita via mail attendiamo riscontro,

Grazie

**Comment by lucasomarugasia** [comment]
Gestiamo la segnalazione tramite mail a teamcentroStella@sia.eu, cons.dellannariccardo@sia.eu come supporto alla data preparation
