### ISSUE TITLE
Errore in UAT /bpd/hb/payment-instruments/{id} per GET

### ISSUE THREAD

**Issue by ChristianRoldo** [pagopa/issuer_integration#87]
Ciao 
eseguendo la GET di   /bpd/hb/payment-instruments/{id} otteniamo un errore non documentato 

```
{
    "returnMessages": {
        "ERROR": [
            {
                "message": "il campo %s supporta solamente il tipo %s",
                "messageTitle": "Risorsa non trovata",
                "messageKey": "resource.not-found.error",
                "severity": "ERROR"
            }
        ]
    }
}
```

Lo stesso errore compare in fase di enrollment.  E' un errore interno del servizio ?
Grazie
Christian

**Comment by mdesogus** [comment]
Buongiorno,

sarebbe possibile rieseguire  il test e fornirci riscontro? 

grazie

**Comment by ChristianRoldo** [comment]
buongiorno
fatto in test con stesso risultato
Grazie

**Comment by mdesogus** [comment]
Potreste fornirci il dettaglio della chiamata effettuata ed il log?
nelle casistiche che abbiamo replicato non riscontriamo evidenze di errore

**Comment by ChristianRoldo** [comment]
Una piccola precisazione. Nella PUT ho visto che è stata cambiata la "firma" passami il termine. Id è passato nel body.
Id è come evidenziato nell'ultma versione committata poco fa il PGP message derivante dalla criptatura dello strumento di pagamento  

Nella get non è richiesto il crypting ( anche passando path parameters non sarebbe utilzzabile senza encoding )...
Provando ora funziona in SIT 
/bpd/hb/payment-instruments/477571123456

Mi ritorna i valori correttamente

La cosa strana è che in test ho provato a sottomettere piu volte la stessa carta criptata e ritorna ogni volta un activation date diverso , anche se la carta è gia enrollata.
Funziona invece correttament la verifica di conflict se la carta è già attivata su altro utente 

Se eseguo la stessa chiamata in UAT ottengo l errore riportato sopra.

`{
    "returnMessages": {
        "ERROR": [
            {
                "message": "il campo %s supporta solamente il tipo %s",
                "messageTitle": "Risorsa non trovata",
                "messageKey": "resource.not-found.error",
                "severity": "ERROR"
            }
        ]
    }
}`

La PUT invece ritorna in UAT  ritorna una bad request. 

grazie
Christian

**Comment by mdesogus** [comment]
Buongiorno,

da verifiche effettuate l'anomalia risulta sanata,
sarebbe possibile rieseguire il test e fornirci nuovamente il risultato?

Sul punto legato al valore assunto dall'activationDate ad ogni enrollment  sono in corso ulteriori verifiche.

Grazie

**Comment by ChristianRoldo** [comment]
Risulta sanata in UAT ? 
In SIT tutto mi funziona. In UAT ottengo ancora 400 sulla PUT 
endpoint /bpd/hb/payment-instruments/card
Qui il body della richiesta 

`{   "id":"-----BEGIN PGP MESSAGE-----\nVersion: BCPG v1.58\n\nhQEMA+NENQPn0iNJAQf+MHqzKTeQ51jx1W8qj8PJ2NWc1vHuK/nyFWuYLalO1Aef\nQx1inN+C3kaZ0sfbf9nPWeLAxC8IH/wgACxMQOxeoCnN6PblSmndubG+b/aqCxh0\nhx7gaRGfijnasC9q9LPpqELqq7yHKRCPLmwbxINWbiUb6N2a//VTSv7sU/opvm73\n8EGIOpQPCMKcOeUpa7For79sEpYMmnSarmqn0H9QUwdPkcujJUawI+VdyBagMDBw\nMjCsYtHmroSb6nO3RPXUv+abWFrXupRc1y5PQFYfmyHSTlGVcYkN9TyZTxCpTTzI\nJcqhAoWqm5dXpd4MOfnWgKplp4odeEFG7Jg0uS2OUdJdAYWEybGtRJ0dspab8gXi\nFkGIodR943hfkA+Gcbgq3KZ1iMHlltChFpUMuVAi/h5hXRezaRHSLtogsWGmS0Hu\nCu12nMM7jeO8Yb7jqD9pN1fb7dzhYonI+zFOCB6E\n\u003dHDez\n-----END PGP MESSAGE-----\n",
    "fiscalCode": "RLDCRS78B08A859N",
    "expireYear": "2022",
    "expireMonth": "05",
    "issuerAbiCode": "03268",
    "brand": "VISA",
    "holder": "ROLDO CHRISTIAN",
    "type": "CRD",
    "channel": "03268"
}`

La get Citizen Status ritorna

`{
    "fiscalCode": "RLDCRS78B08A859N",
    "payoffInstr": "IT43U0326822300001765985800",
    "timestampTC": "2020-10-30T13:16:36.942+01:00",
    "enabled": true
}`

La stessa PUT  in SIT funziona correttamente

christian

**Comment by mdesogus** [comment]
c'è un errore nella richiesta, 

in documentazione il campo "expireMonth" è censito  come **exprireMonth**,
potreste riprovare così?

grazie

**Comment by ChristianRoldo** [comment]
Ciao
cosi la PUT funziona.  Ed anche la Get del payment instrument.
Procederete con la correzione? 
grazie
Christian

**Comment by mdesogus** [comment]
in questo momento il campo resterà così, procederemo in un secondo momento con la correzione, notificandovi poi l'avvenuto aggiornamento.

Grazie

**Comment by ChristianRoldo** [comment]
Scusate quindi solo in UAT avremo questa "differenza" ?

**Comment by mdesogus** [comment]
anche in Produzione sino al momento della correzione

**Comment by ChristianRoldo** [comment]
Pero in SIT ad oggi non è allineato.. Corretto?
Come procederete aggiungendo un nuovo campo e definendo come "deprecato" quello errato ?

Grazie
Christian
