### ISSUE TITLE
non è possibile procedere con l'abilitazione/disabilitazione delle carte

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#89]
salve, 

non è possibile procedere con l'abilitazione/disabilitazione delle carte né in fase di attivazione servizio né successivamente nella dashboard

di seguito i log che evidenziano errore 400

[INFO]    [25/11/2020 17.56.18 677] [pool-4-thread-196] [SCA - SESSIONID [7D4B9D3FC2FFEAB1BCDC856F920DF55B.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaCartaCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - enrollmentStrumentoPagamento - HTTP URL[https
://test.cstar.pagopa.it/bpd/hb/payment-instruments/card/5333171000567590]]
[INFO]    [25/11/2020 17.56.18 678] [pool-4-thread-196] [SCA - SESSIONID [7D4B9D3FC2FFEAB1BCDC856F920DF55B.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaCartaCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQ
UEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: b4f5b877-a9c0-420b-a59c-8f0a7e00c4b7, Content-Type: application/json]]
[INFO]    [25/11/2020 17.56.18 678] [pool-4-thread-196] [SCA - SESSIONID [7D4B9D3FC2FFEAB1BCDC856F920DF55B.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaCartaCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQ
UEST PAYLOAD - {"fiscalCode":"PLARST80A01H501Z","exprireMonth":"10","channel":"APP","issuerAbiCode":"00000","holder":"ROSATI PAOLO","type":"","activationDate":"2020-11-
25T17:56:18+01:00","expireYear":"","brand":""}]
[INFO]    [25/11/2020 17.56.19 053] [pool-4-thread-196] [SCA - SESSIONID [7D4B9D3FC2FFEAB1BCDC856F920DF55B.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaCartaCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPO
NSE - HTTP STATUS[400]]
[INFO]    [25/11/2020 17.56.19 053] [pool-4-thread-196] [SCA - SESSIONID [7D4B9D3FC2FFEAB1BCDC856F920DF55B.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaCartaCash
back] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [rosati.paolo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPO
NSE - HTTP ENTITY[]]

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo provveduto a sanare l'anomalia segnalata.
Adesso il servizio funziona correttamente.
Saluti
