### ISSUE TITLE
definizione di #/components/schemas/MedaError mancante

### ISSUE THREAD

**Issue by wallaroo** [pagopa/issuer_integration#9]
Ciao, segnalo che la definizione del tipo "MedaError" risulta mancante in [bpd-hb-payment-instruments-api.yaml](https://github.com/pagopa/issuer_integration/blob/master/ops_resources/swagger/bpd-hb-payment-instruments-api.yaml)

**Comment by DenisaBraho** [comment]
Ciao,
abbiamo provveduto a sistemare l'API indicato. Nel path: https://github.com/pagopa/issuer_integration/tree/master/ops_resources/swagger potete trovare la versione aggiornata e corretta.
A disposizione
Saluti
