### ISSUE TITLE
modificaImpostazioniIBAN - errore KO

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#90]
Salve, 

riscontriamo questa anomalia 

INFO]    [26/11/2020 09.36.12 107] [pool-4-thread-143] [SCA - SESSIONID [EB4C0D7D6ECA5A02462ADA6E43AE207E.mobile] -  COMMAND SCA [Async - v1/postepay/attivaIbanCashbac
k] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - modificaImpostazioniIBAN - HTTP URL[https:
//test.cstar.pagopa.it/bpd/hb/citizens/DDCDBP66A01L736X]]
[INFO]    [26/11/2020 09.36.12 108] [pool-4-thread-143] [SCA - SESSIONID [EB4C0D7D6ECA5A02462ADA6E43AE207E.mobile] -  COMMAND SCA [Async - v1/postepay/attivaIbanCashbac
k] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBAN-PATCH - RE
QUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 5d6336ba-d450-4437-8dd0-82ace959b3ee, Content-Type: application/json]]
[INFO]    [26/11/2020 09.36.12 108] [pool-4-thread-143] [SCA - SESSIONID [EB4C0D7D6ECA5A02462ADA6E43AE207E.mobile] -  COMMAND SCA [Async - v1/postepay/attivaIbanCashbac
k] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBAN-PATCH - RE
QUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/citizens/DDCDBP66A01L736X]
[INFO]    [26/11/2020 09.36.13 395] [pool-4-thread-143] [SCA - SESSIONID [EB4C0D7D6ECA5A02462ADA6E43AE207E.mobile] -  COMMAND SCA [Async - v1/postepay/attivaIbanCashbac
k] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBAN-PATCH RESP
ONSE - HTTP STATUS[200]]
[INFO]    [26/11/2020 09.36.13 395] [pool-4-thread-143] [SCA - SESSIONID [EB4C0D7D6ECA5A02462ADA6E43AE207E.mobile] -  COMMAND SCA [Async - v1/postepay/attivaIbanCashbac
k] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBAN-PATCH RESP
ONSE - HTTP ENTITY[{"validationStatus":"KO"}]]
[DEBUG]   [26/11/2020 09.36.13 396] [pool-4-thread-143] [SCA - SESSIONID [EB4C0D7D6ECA5A02462ADA6E43AE207E.mobile] -  COMMAND SCA [Async - v1/postepay/attivaIbanCashbac
k] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - modificaImpostazioniIBAN-PATCH [{"validati
onStatus": "KO"}]]
[ERROR]   [26/11/2020 09.36.13 397] [pool-4-thread-143] [SCA - SESSIONID [EB4C0D7D6ECA5A02462ADA6E43AE207E.mobile] -  COMMAND SCA [Async - v1/postepay/attivaIbanCashbac
k] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService.modificaImpostazioniIBAN - exec-time [1289 m
s] - result [ModificaImpostazioniIBANResponse [stato=KO]]]
[ERROR]   [26/11/2020 09.36.13 402] [pool-4-thread-143] [SCA - SESSIONID [EB4C0D7D6ECA5A02462ADA6E43AE207E.mobile] -  COMMAND SCA [Async - v1/postepay/attivaIbanCashback] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - AttivaIbanCashbackCommand - EnrollmentStrumentoPagamentoCashBackCommand - ERROR: ModificaImpostazioniIBANResponse [stato=KO]]

**Comment by daniloMessinaSia** [comment]
Ciao,
per poter effettuare le verifiche avremmo quanto meno la necessità di ottenere maggiori informazioni riguardo la segnalazione tra cui il body di chiamata.

Aggiungo che il servizio risponde un KO se il servizio esterno tramite il quale verifichiamo l'associazione tra IBAN inviato e CF dell'utente loggato non va a buon fine.
Come definito su IA, i valori possibili sono:
 - OK: l’IBAN è associato all’utente (IBAN salvato)
 - KO: l’IBAN non è associato all’utente (IBAN NON salvato)
 - UNKNOWN_PSP: non è stato possibile verificare (IBAN salvato)

**Comment by DenisaBraho** [comment]
Ciao,
procediamo con la chiusura della issue. Se si dovesse presentare un KO non atteso lato vostro, vi pregiamo di procedere con la riapertura di questa issue, oppure con l'apertura di una nuova 
Grazie
Saluti

**Comment by DenisaBraho** [comment]
Ciao @NicolaLamberti  ci sono novità in merito? 
Se il KO dovesse risultare atteso lato vostro a seguito delle informazioni fornite sopra, vi chiediamo un conferma per poter procedere con la chiusura della issue.
Saluti

**Comment by lucasomarugasia** [comment]
Da controllo di Lamberti riporto "anomalia rientrata". Chiudo segnalazione
