### ISSUE TITLE
Inconsistenza tra API e documentazione

### ISSUE THREAD

**Issue by antessio** [pagopa/issuer_integration#91]
Con riferimento all'ultima versione della documentazione [Issuer Interface Agreement_v3.pdf](https://github.com/pagopa/issuer_integration/blob/master/ops_resources/Issuer%20Interface%20Agreement_v3.pdf) l'enrollment dello strumento Satispay dovrebbe avere in response body `activationDate`

Facendo questa chiamata in UAT però l'API restituisce 201 senza alcun response body. 

Qual'è il comportamento atteso?

Segnalo inoltre che come segnalato in questa issue https://github.com/pagopa/issuer_integration/issues/87 anche noi stiamo riscontrando lo stesso errore. 

nello specifico chiamando prima `PUT /bpd/hb/payment-instruments/satispay/{id}` e poi `GET /bpd/hb/payment-instruments/{id}`con lo stesso id.

**Comment by mdesogus** [comment]
Buongiorno,

è possibile rieseguire il test e fornirci riscontro?

grazie

**Comment by antessio** [comment]
Ora otteniamo la risposta corretta. 
Potrebbe per favore invece chiarire qual'è la risposta attesa per l'API `PUT /bpd/hb/payment-instruments/satispay/{id}`?

**Comment by mdesogus** [comment]
è corretta quella indicata nella prima segnalazione inviataci(response body activationDate):
es.
{
    "activationDate": "2020-11-26T10:50:05.878+01:00"
}
