### ISSUE TITLE
Disattivazione carta ok ma lo status ritorna carta attiva

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#92]
salve, 
la seguente carta ci risulta attiva. la disattivazione va a buon fine ma lo stato poi ci torna sempre come se fosse attiva

**stato:** 

[INFO] [Thu Nov 26 12:52:43 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030]
[INFO] [Thu Nov 26 12:52:43 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 83fec27b-5cf1-4f31-82e9-85c2b7154ee9]
[INFO] [Thu Nov 26 12:52:43 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030
2020/11/26 12:52:43:784 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/26 12:52:43:788 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/26 12:52:43:789 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/26 12:52:43:804 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/26 12:52:43:815 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/26 12:52:44:089 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:61126<->20.54.178.216:443
2020/11/26 12:52:44:090 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/26 12:52:44:097 CET [DEBUG] wire - http-outgoing-0 >> "GET /bpd/hb/payment-instruments/5333171000547030 HTTP/1.1[\r][\n]"
2020/11/26 12:52:44:098 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/26 12:52:44:099 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 83fec27b-5cf1-4f31-82e9-85c2b7154ee9[\r][\n]"
2020/11/26 12:52:44:101 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/26 12:52:44:102 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/26 12:52:44:103 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/26 12:52:44:104 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/26 12:52:44:105 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/26 12:52:44:412 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2020/11/26 12:52:44:412 CET [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
2020/11/26 12:52:44:413 CET [DEBUG] wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
2020/11/26 12:52:44:413 CET [DEBUG] wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2020/11/26 12:52:44:413 CET [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
2020/11/26 12:52:44:414 CET [DEBUG] wire - http-outgoing-0 << "Expires: 0[\r][\n]"
2020/11/26 12:52:44:414 CET [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2020/11/26 12:52:44:414 CET [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2020/11/26 12:52:44:415 CET [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
2020/11/26 12:52:44:415 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/26 12:52:44:415 CET [DEBUG] wire - http-outgoing-0 << "Date: Thu, 26 Nov 2020 11:52:42 GMT[\r][\n]"
2020/11/26 12:52:44:416 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/26 12:52:44:416 CET [DEBUG] wire - http-outgoing-0 << "AE[\r][\n]"
2020/11/26 12:52:44:416 CET [DEBUG] wire - http-outgoing-0 << "{"hpan":"484ed6c6a82a7915a2cdcc7827075efdc644eac4d35e2c66ba493f98aaa7e96d","fiscalCode":"RSSNEE99A01H501L","activationDate":"2020-11-23T13:25:46.327+01:00","Status":"ACTIVE"}[\r][\n]"
2020/11/26 12:52:44:429 CET [DEBUG] wire - http-outgoing-0 << "0[\r][\n]"
2020/11/26 12:52:44:429 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/26 12:52:44:429 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/26 12:52:44:430 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Thu Nov 26 12:52:44 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP STATUS[200]
[INFO] [Thu Nov 26 12:52:44 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP ENTITY[{"hpan":"484ed6c6a82a7915a2cdcc7827075efdc644eac4d35e2c66ba493f98aaa7e96d","fiscalCode":"RSSNEE99A01H501L","activationDate":"2020-11-23T13:25:46.327+01:00","Status":"ACTIVE"}]
[DEBUG] [Thu Nov 26 12:52:44 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento-GET [{
   "Status": "ACTIVE",
   "hpan": "484ed6c6a82a7915a2cdcc7827075efdc644eac4d35e2c66ba493f98aaa7e96d",
   "fiscalCode": "RSSNEE99A01H501L",
   "activationDate": "2020-11-23T13:25:46.327+01:00"
}]

**Disattivazione:** 

[INFO] [Thu Nov 26 12:53:11 CET 2020] BonusPagamentiDigitaliService - disabilitazioneStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030]
[INFO] [Thu Nov 26 12:53:11 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 24cd3009-2ddd-42bc-822d-fb2770237d99]
[INFO] [Thu Nov 26 12:53:11 CET 2020] BonusPagamentiDigitaliService - method disabilitazioneStrumentoPagamento-DELETE - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030
2020/11/26 12:53:11:421 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/26 12:53:11:427 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/26 12:53:11:430 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/26 12:53:11:452 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/26 12:53:11:462 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/26 12:53:11:746 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:61138<->20.54.178.216:443
2020/11/26 12:53:11:746 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/26 12:53:11:749 CET [DEBUG] wire - http-outgoing-0 >> "DELETE /bpd/hb/payment-instruments/5333171000547030 HTTP/1.1[\r][\n]"
2020/11/26 12:53:11:749 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/26 12:53:11:750 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 24cd3009-2ddd-42bc-822d-fb2770237d99[\r][\n]"
2020/11/26 12:53:11:750 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/26 12:53:11:751 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/26 12:53:11:751 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/26 12:53:11:752 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/26 12:53:11:752 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/26 12:53:12:033 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 204 No Content[\r][\n]"
2020/11/26 12:53:12:033 CET [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
2020/11/26 12:53:12:034 CET [DEBUG] wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
2020/11/26 12:53:12:034 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
2020/11/26 12:53:12:034 CET [DEBUG] wire - http-outgoing-0 << "Expires: 0[\r][\n]"
2020/11/26 12:53:12:035 CET [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2020/11/26 12:53:12:035 CET [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2020/11/26 12:53:12:035 CET [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
2020/11/26 12:53:12:035 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/26 12:53:12:036 CET [DEBUG] wire - http-outgoing-0 << "Date: Thu, 26 Nov 2020 11:53:10 GMT[\r][\n]"
2020/11/26 12:53:12:036 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/26 12:53:12:044 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/26 12:53:12:045 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Thu Nov 26 12:53:12 CET 2020] BonusPagamentiDigitaliService.disabilitazioneStrumentoPagamento - exec-time [670 ms] - result [DisabilitazioneStrumentoPagamentoResponse{} AOutput{resultCode=0, httpResultCode='204', returnMessage='OK', description='null', errorCode='null', errorMap={}}]
DisabilitazioneStrumentoPagamentoResponse{} AOutput{resultCode=0, httpResultCode='204', returnMessage='OK', description='null', errorCode='null', errorMap={}}

**Stato** 

    
    [INFO] [Thu Nov 26 12:53:39 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030]
[INFO] [Thu Nov 26 12:53:39 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 55a4b4e7-7cda-411f-8e7c-28f64333507f]
[INFO] [Thu Nov 26 12:53:39 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET - REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/payment-instruments/5333171000547030
2020/11/26 12:53:39:109 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/26 12:53:39:117 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/26 12:53:39:119 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {​​​​​​​s}​​​​​​​->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/26 12:53:39:138 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {​​​​​​​s}​​​​​​​->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/26 12:53:39:148 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/26 12:53:39:405 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:61147<->20.54.178.216:443
2020/11/26 12:53:39:406 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/26 12:53:39:409 CET [DEBUG] wire - http-outgoing-0 >> "GET /bpd/hb/payment-instruments/5333171000547030 HTTP/1.1[\r][\n]"
2020/11/26 12:53:39:410 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/26 12:53:39:410 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 55a4b4e7-7cda-411f-8e7c-28f64333507f[\r][\n]"
2020/11/26 12:53:39:411 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/26 12:53:39:411 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/26 12:53:39:411 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/26 12:53:39:412 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/26 12:53:39:412 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/26 12:53:39:698 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2020/11/26 12:53:39:698 CET [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
2020/11/26 12:53:39:699 CET [DEBUG] wire - http-outgoing-0 << "Pragma: no-cache[\r][\n]"
2020/11/26 12:53:39:699 CET [DEBUG] wire - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2020/11/26 12:53:39:699 CET [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
2020/11/26 12:53:39:700 CET [DEBUG] wire - http-outgoing-0 << "Expires: 0[\r][\n]"
2020/11/26 12:53:39:701 CET [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2020/11/26 12:53:39:701 CET [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2020/11/26 12:53:39:701 CET [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: DENY[\r][\n]"
2020/11/26 12:53:39:702 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/26 12:53:39:702 CET [DEBUG] wire - http-outgoing-0 << "Date: Thu, 26 Nov 2020 11:53:38 GMT[\r][\n]"
2020/11/26 12:53:39:703 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/26 12:53:39:703 CET [DEBUG] wire - http-outgoing-0 << "AE[\r][\n]"
2020/11/26 12:53:39:704 CET [DEBUG] wire - http-outgoing-0 << "{​​​​​​​"hpan":"484ed6c6a82a7915a2cdcc7827075efdc644eac4d35e2c66ba493f98aaa7e96d","fiscalCode":"RSSNEE99A01H501L","activationDate":"2020-11-23T13:25:46.327+01:00","Status":"ACTIVE"}​​​​​​​[\r][\n]"
2020/11/26 12:53:39:719 CET [DEBUG] wire - http-outgoing-0 << "0[\r][\n]"
[INFO] [Thu Nov 26 12:53:39 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP STATUS[200]
[INFO] [Thu Nov 26 12:53:39 CET 2020] BonusPagamentiDigitaliService - method statusStrumentoPagamento-GET RESPONSE - HTTP ENTITY[{​​​​​​​"hpan":"484ed6c6a82a7915a2cdcc7827075efdc644eac4d35e2c66ba493f98aaa7e96d","fiscalCode":"RSSNEE99A01H501L","activationDate":"2020-11-23T13:25:46.327+01:00","Status":"ACTIVE"}​​​​​​​]
2020/11/26 12:53:39:719 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/26 12:53:39:719 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {​​​​​​​s}​​​​​​​->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/26 12:53:39:722 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {​​​​​​​s}​​​​​​​->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/26 12:53:39:735 CET [DEBUG] PoolingHttpClientConnectionManager - Closing expired connections[DEBUG] [Thu Nov 26 12:53:39 CET 2020] BonusPagamentiDigitaliService - statusStrumentoPagamento-GET [{​​​​​​​
   "Status": "ACTIVE",
   "hpan": "484ed6c6a82a7915a2cdcc7827075efdc644eac4d35e2c66ba493f98aaa7e96d",
   "fiscalCode": "RSSNEE99A01H501L",
   "activationDate": "2020-11-23T13:25:46.327+01:00"
}​​​​​​​]

**Comment by mdesogus** [comment]
Abbiamo rilevato un'incongruenza sulla base dati,
è possibile riprovare.

Grazie
