### ISSUE TITLE
Enrollment Strumento di pagamento - valorizzazione campi

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#93]
Salve. 

per le carte del gruppo Poste,  in che modo vi aspettate che siano valorizzati i seguenti campi obbligatori: 

1.	 campo Channel 

2.	 campo issuerAbiCode  

3.	Campo Brand 

4.	Campo Type

Grazie 

Nicola

**Comment by mdesogus** [comment]
Buongiorno,

come definito in documentazione i campi dovranno essere popolati nel seguente modo:

- issuerAbiCode:  codice ABI della banca emittente carta
- brand: tipo di circuito (es. Visa, Mastercard etc)
- type:  tipologia carta (es. PP, DEB, CRD)
- channel: Canale che identifica univocamente l’issuer che invoca l’API sulla piattaforma. Valorizzato con il codice ABI dell’Issuer chiamante

**Comment by NicolaLamberti** [comment]
@mdesogus si ho letto la documentazione. ma voi sull'app IO come li valorizzate per le carte del gruppo Poste Italiane? chi vi passa queste informazioni?
