### ISSUE TITLE
enrollment strumento di pagamento - errore 500

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#94]
salve, 

di seguito i log. ci ritorna un 500. 

[DEBUG] [Thu Nov 26 15:41:41 CET 2020]  START BonusPagamentiDigitaliService - enrollmentStrumentoPagamento-PUT
[INFO] [Thu Nov 26 15:41:41 CET 2020] BonusPagamentiDigitaliService - enrollmentStrumentoPagamento-PUT - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card]
[INFO] [Thu Nov 26 15:41:41 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 7b3c2d88-f194-4fff-a25c-9a3c0092d029, Content-Type: application/json]
[INFO] [Thu Nov 26 15:41:41 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQUEST PAYLOAD - {"fiscalCode":"RSSNEE99A01H501L","exprireMonth":"11","channel":"36081","issuerAbiCode":"36081","id":"-----BEGIN PGP MESSAGE-----Version: BCPG v1.60hQEMA+NENQPn0iNJAQf9Es+LcP+uR0m0mDTTNSxXNVXFWZmEGVInIio42BT3sEIEumGB3w7NSnA8FaHahf61DfNiCyvZQGzPTPSOaS4Qgr5heI/XH7ZbcrrDSGU0hhfN6yhpyp90F5gUBQFksMnw/aNxyYrgrPFQGx7AJXMLXh7RCUdgg6TaSIkKRWcT5llVII0elzbtk9HKzew6RbKn4MJ3ajGU5mzYG7qmykea0YwBcIABM7rkDLa7FTJzxbilwxkAP39V+JRdZtCKSu2n9dIILBV2+YZmPErU2d4ZjyCNy/+Y2ye//Td1FNGewcJipLop3EFCOS7NjzpShBOuqXStFaxv+hmMSwnnhbxFosk0cjR2cjN4XKOoq+8oyfS82vTC9q5Yg57lGZvqv2VRYnjUNKI8LiCaMs4nRk1x6R9OH+yv7A===kpI1-----END PGP MESSAGE-----","type":"PP","activationDate":"2020-11-26T15:41:41+01:00","expireYear":"2024","brand":"Mastercard"}
2020/11/26 15:41:41:764 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/26 15:41:41:774 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/26 15:41:41:777 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/26 15:41:41:799 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/26 15:41:41:811 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/26 15:41:42:087 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:58270<->20.54.178.216:443
2020/11/26 15:41:42:087 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/26 15:41:42:090 CET [DEBUG] wire - http-outgoing-0 >> "PUT /bpd/hb/payment-instruments/card HTTP/1.1[\r][\n]"
2020/11/26 15:41:42:090 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/26 15:41:42:091 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 7b3c2d88-f194-4fff-a25c-9a3c0092d029[\r][\n]"
2020/11/26 15:41:42:091 CET [DEBUG] wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
2020/11/26 15:41:42:091 CET [DEBUG] wire - http-outgoing-0 >> "Content-Length: 713[\r][\n]"
2020/11/26 15:41:42:092 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/26 15:41:42:092 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/26 15:41:42:092 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/26 15:41:42:093 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/26 15:41:42:093 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/26 15:41:42:093 CET [DEBUG] wire - http-outgoing-0 >> "{"fiscalCode":"RSSNEE99A01H501L","exprireMonth":"11","channel":"36081","issuerAbiCode":"36081","id":"-----BEGIN PGP MESSAGE-----Version: BCPG v1.60hQEMA+NENQPn0iNJAQf9Es+LcP+uR0m0mDTTNSxXNVXFWZmEGVInIio42BT3sEIEumGB3w7NSnA8FaHahf61DfNiCyvZQGzPTPSOaS4Qgr5heI/XH7ZbcrrDSGU0hhfN6yhpyp90F5gUBQFksMnw/aNxyYrgrPFQGx7AJXMLXh7RCUdgg6TaSIkKRWcT5llVII0elzbtk9HKzew6RbKn4MJ3ajGU5mzYG7qmykea0YwBcIABM7rkDLa7FTJzxbilwxkAP39V+JRdZtCKSu2n9dIILBV2+YZmPErU2d4ZjyCNy/+Y2ye//Td1FNGewcJipLop3EFCOS7NjzpShBOuqXStFaxv+hmMSwnnhbxFosk0cjR2cjN4XKOoq+8oyfS82vTC9q5Yg57lGZvqv2VRYnjUNKI8LiCaMs4nRk1x6R9OH+yv7A===kpI1-----END PGP MESSAGE-----","type":"PP","activationDate":"2020-11-26T15:41:41+01:00","expireYear":"2024","brand":"Mastercard"}"
2020/11/26 15:41:42:363 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 500 ErrorPM[\r][\n]"
2020/11/26 15:41:42:364 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
2020/11/26 15:41:42:364 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/26 15:41:42:365 CET [DEBUG] wire - http-outgoing-0 << "Date: Thu, 26 Nov 2020 14:41:40 GMT[\r][\n]"
2020/11/26 15:41:42:365 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/26 15:41:42:375 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/26 15:41:42:376 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Thu Nov 26 15:41:42 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPONSE - HTTP STATUS[500]
[INFO] [Thu Nov 26 15:41:42 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPONSE - HTTP ENTITY[]
[ERROR] [Thu Nov 26 15:41:42 CET 2020] BonusPagamentiDigitaliService.enrollmentStrumentoPagamento - exec-time [692 ms] - result [EnrollmentStrumentoPagamentoResponse{dataAttivazione='null'} AOutput{resultCode=1, httpResultCode='500', returnMessage='Error method service.', description='Generic error', errorCode='null', errorMap={}}]
EnrollmentStrumentoPagamentoResponse{dataAttivazione='null'} AOutput{resultCode=1, httpResultCode='500', returnMessage='Error method service.', description='Generic error', errorCode='null', errorMap={}}

**Comment by mdesogus** [comment]
Buongiorno

dal log di esempio notiamo che il campo della chiave pgp non contiene i separatori di riga(/n),
potreste riprovare in questo modo?

**Comment by NicolaLamberti** [comment]
Sempre 500 

[DEBUG] [Thu Nov 26 17:23:49 CET 2020]  START BonusPagamentiDigitaliService - enrollmentStrumentoPagamento-PUT
[INFO] [Thu Nov 26 17:23:49 CET 2020] BonusPagamentiDigitaliService - enrollmentStrumentoPagamento-PUT - HTTP URL[https://test.cstar.pagopa.it/bpd/hb/payment-instruments/card]
[INFO] [Thu Nov 26 17:23:49 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: 7bd6752d-6fab-4cef-9018-462f9a5f16b3, Content-Type: application/json]
[INFO] [Thu Nov 26 17:23:49 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT - REQUEST PAYLOAD - {"fiscalCode":"RSSNEE99A01H501L","exprireMonth":"11","channel":"36081","issuerAbiCode":"36081","id":"-----BEGIN PGP MESSAGE-----\nVersion: BCPG C# v1.6.1.0\n\nhQEMA+NENQPn0iNJAQf/ee9tRkksD+IhY84e2SG4Or51kopVtwWbysbzEpWX0oAo\n0aVLq10BHbTs2zEG1L1Xwqf24YrrRvc6IUX73j4Xh6n//Mz7op8dCD47uMSVeSDa\n9EMd239jDKD31d6O3I1CEPfnaTVOPy4veHxgNn6deWxdUai9a1RCZMJXO9AXWKtu\n6oVjUMWiJhpT8zK9OO2KT+YpMUWp8CTJfoQQVMdZx8lqpYvXvmblAAtT7HZfGn41\nFYnPv07mOseniLI5jOeHcUwDb2uVZExysxfotgW8VECUXT/39kLYkqzh4USyvVWo\nMC9XN1Jo3iXV6Z1BYDS9f/BydHPk3EGJeOk41QVY68kuVMrPTKAMluHg49E0vj+X\nSVEP14vqqNn0hsRJDDOYnFUVbOlEhYHW4q31mttOIw==\n=7n38\n-----END PGP MESSAGE-----\n","type":"PP","expireYear":"2024","brand":"Mastercard"}
2020/11/26 17:23:49:606 CET [DEBUG] RequestAddCookies - CookieSpec selected: ignoreCookies
2020/11/26 17:23:49:610 CET [DEBUG] RequestAuthCache - Auth cache not set in the context
2020/11/26 17:23:49:615 CET [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2020/11/26 17:23:49:645 CET [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2020/11/26 17:23:49:663 CET [DEBUG] DefaultHttpClientConnectionOperator - Connecting to test.cstar.pagopa.it/20.54.178.216:443
2020/11/26 17:23:49:966 CET [DEBUG] DefaultHttpClientConnectionOperator - Connection established 192.168.200.163:50989<->20.54.178.216:443
2020/11/26 17:23:49:967 CET [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
2020/11/26 17:23:49:969 CET [DEBUG] wire - http-outgoing-0 >> "PUT /bpd/hb/payment-instruments/card HTTP/1.1[\r][\n]"
2020/11/26 17:23:49:970 CET [DEBUG] wire - http-outgoing-0 >> "Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992[\r][\n]"
2020/11/26 17:23:49:970 CET [DEBUG] wire - http-outgoing-0 >> "x-request-id: 7bd6752d-6fab-4cef-9018-462f9a5f16b3[\r][\n]"
2020/11/26 17:23:49:971 CET [DEBUG] wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
2020/11/26 17:23:49:971 CET [DEBUG] wire - http-outgoing-0 >> "Content-Length: 690[\r][\n]"
2020/11/26 17:23:49:972 CET [DEBUG] wire - http-outgoing-0 >> "Host: test.cstar.pagopa.it[\r][\n]"
2020/11/26 17:23:49:972 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020/11/26 17:23:49:973 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_241)[\r][\n]"
2020/11/26 17:23:49:973 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020/11/26 17:23:49:973 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2020/11/26 17:23:49:974 CET [DEBUG] wire - http-outgoing-0 >> "{"fiscalCode":"RSSNEE99A01H501L","exprireMonth":"11","channel":"36081","issuerAbiCode":"36081","id":"-----BEGIN PGP MESSAGE-----\nVersion: BCPG C# v1.6.1.0\n\nhQEMA+NENQPn0iNJAQf/ee9tRkksD+IhY84e2SG4Or51kopVtwWbysbzEpWX0oAo\n0aVLq10BHbTs2zEG1L1Xwqf24YrrRvc6IUX73j4Xh6n//Mz7op8dCD47uMSVeSDa\n9EMd239jDKD31d6O3I1CEPfnaTVOPy4veHxgNn6deWxdUai9a1RCZMJXO9AXWKtu\n6oVjUMWiJhpT8zK9OO2KT+YpMUWp8CTJfoQQVMdZx8lqpYvXvmblAAtT7HZfGn41\nFYnPv07mOseniLI5jOeHcUwDb2uVZExysxfotgW8VECUXT/39kLYkqzh4USyvVWo\nMC9XN1Jo3iXV6Z1BYDS9f/BydHPk3EGJeOk41QVY68kuVMrPTKAMluHg49E0vj+X\nSVEP14vqqNn0hsRJDDOYnFUVbOlEhYHW4q31mttOIw==\n=7n38\n-----END PGP MESSAGE-----\n","type":"PP","expireYear":"2024","brand":"Mastercard"}"
2020/11/26 17:23:50:524 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 500 ErrorPM[\r][\n]"
2020/11/26 17:23:50:525 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
2020/11/26 17:23:50:525 CET [DEBUG] wire - http-outgoing-0 << "Request-Context: appId=cid-v1:e19defe2-7bfe-4a07-a249-f2bec96c14b4[\r][\n]"
2020/11/26 17:23:50:525 CET [DEBUG] wire - http-outgoing-0 << "Date: Thu, 26 Nov 2020 16:23:48 GMT[\r][\n]"
2020/11/26 17:23:50:526 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2020/11/26 17:23:50:534 CET [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT] can be kept alive indefinitely
2020/11/26 17:23:50:535 CET [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://test.cstar.pagopa.it:443][state: CN=Certificato client soggetti terzi, O=PagoPA S.p.A., L=Roma, ST=Roma, C=IT][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
[INFO] [Thu Nov 26 17:23:50 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPONSE - HTTP STATUS[500]
[INFO] [Thu Nov 26 17:23:50 CET 2020] BonusPagamentiDigitaliService - method enrollmentStrumentoPagamento-PUT RESPONSE - HTTP ENTITY[]
[ERROR] [Thu Nov 26 17:23:50 CET 2020] BonusPagamentiDigitaliService.enrollmentStrumentoPagamento - exec-time [1014 ms] - result [EnrollmentStrumentoPagamentoResponse{dataAttivazione='null'} AOutput{resultCode=1, httpResultCode='500', returnMessage='Error method service.', description='Generic error', errorCode='null', errorMap={}}]
EnrollmentStrumentoPagamentoResponse{dataAttivazione='null'} AOutput{resultCode=1, httpResultCode='500', returnMessage='Error method service.', description='Generic error', errorCode='null', errorMap={}}

**Comment by daniloMessinaSia** [comment]
Non è presente il campo holder, potreste inserirlo e riprovare?

**Comment by NicolaLamberti** [comment]
ma il campo Holder non è obbligatorio. Perchè lo dobbiamo passare? sono cambiate le specifiche?

**Comment by daniloMessinaSia** [comment]
no effettivamente continua a non essere obbligatorio.
testando il vostro body comunque riusciamo correttamente ad inserire lo strumento di pagamento

**Comment by lucasomarugasia** [comment]
Da controllo di Lamberti riporto "anomalia rientrata". Chiudo segnalazione
