### ISSUE TITLE
valorizzazione campi - enrollment strumento

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#95]
@mdesogus si ho letto la documentazione. Ma voi sull'app IO come li valorizzate per le carte del gruppo Poste Italiane? chi vi passa queste informazioni?

_Originally posted by @NicolaLamberti in https://github.com/pagopa/issuer_integration/issues/93#issuecomment-734372004_

**Comment by daniloMessinaSia** [comment]
Ciao,
quelle informazioni non vengono storicizzate sul Centro Stella.
durante l'enrollment da H/B le inviamo direttamente al PM, che renderà l'informazione anche disponibile tramite AppIO, per il salvataggio; nel caso di enrollment da appIO vengono richiesti all'utente o sono presenti meccanismi interni (che non conosciamo) per recuperare il dato. 
Ci tengo a precisare che il campo channel varia da attore ad attore quindi, nel caso di enrollment di una carta Poste, ad esempio, sarà valorizzato diversamente se questo avviene tramite H/B (popolato con ABI) o da appIO (popolato con un valore dedicato)
