### ISSUE TITLE
Update issue 83 e 84

### ISSUE THREAD

**Issue by MarcoDeNovellis** [pagopa/issuer_integration#96]
Creo questa issue solo per non perdere traccia del fatto che le issue 83 ed 84, seppur sono segnate come closed, restano effettivamente ancora da smarcare.

Grazie

**Comment by DenisaBraho** [comment]
Ciao Marco,
procediamo con la chiusura di questa issue e la riapertura delle issue 83 e 84. In questi casi, vi chiediamo gentilmente di procedere con la riapertura della issue già esistente.
Grazie
Saluti

**Comment by MarcoDeNovellis** [comment]
Come posso riaprire una issue già chiusa?
