### ISSUE TITLE
Chiarimento su comunicazione del 26/11

### ISSUE THREAD

**Issue by luca1oo** [pagopa/issuer_integration#97]
Ciao, si richiede un chiarimento sull'indicazione ricevuta via mail. In particolare:

"A valle dei vostri adeguamenti all’ultima versione di specifica vi chiediamo inoltre di condividere le evidenze dell’esito positivo dei test in ambiente di UAT per ogni servizio integrato. Concorderemo il passaggio in produzione solo al termine di avvenuta certificazione.
Se possibile, e al fine di poter erogare un supporto più pronto, sarebbe utile avere la vostra pianificazione delle sessioni di test."

1. Ogni Issuer deve condividere la sua test list con gli esiti?
2. Il passaggio in PRO è vincolato post condivisione dei test per singolo Issuer? O, una volta valutati alcuni test case, il passaggio è valido per tutti gli issuer?

Grazie
Luca

**Comment by lucasomarugasia** [comment]
Buonasera, 
1. Corretto
2. Confermiamo. Il passaggio in produzione e vincolato alla certificazione dei test di ogni issuer

**Comment by luca1oo** [comment]
Buonasera,
avete un test list da compilare o ogni issuer condivide la propria?
A quale mail è possibile condividere la test list?
Grazie
