### ISSUE TITLE
Mofdifica IBAN KO - 

### ISSUE THREAD

**Issue by NicolaLamberti** [pagopa/issuer_integration#99]
salve per questa utenza in particolare riceviamo sempre KO. Potreste verificare come mai? 
CF: DDCDBP66A01L736X

[DEBUG]   [27/11/2020 11.56.12 924] [pool-4-thread-313] [SCA - SESSIONID [7434949387A0C3FE7C7B4B132B3CC514.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall -  START BonusPagamentiDigitaliService - modificaImpostazioniIBAN ]
[INFO]    [27/11/2020 11.56.12 924] [pool-4-thread-313] [SCA - SESSIONID [7434949387A0C3FE7C7B4B132B3CC514.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - modificaImpostazioniIBAN - HTTP URL[http
s://test.cstar.pagopa.it/bpd/hb/citizens/DDCDBP66A01L736X]]
[INFO]    [27/11/2020 11.56.12 924] [pool-4-thread-313] [SCA - SESSIONID [7434949387A0C3FE7C7B4B132B3CC514.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBAN-PATCH -
REQUEST HEADER - [Ocp-Apim-Subscription-Key: 16c19a4cbc0a41a888fa6f3cb64c6992, x-request-id: bdd68696-3965-43d1-b3c5-c427b16aae26, Content-Type: application/json]]
[INFO]    [27/11/2020 11.56.12 924] [pool-4-thread-313] [SCA - SESSIONID [7434949387A0C3FE7C7B4B132B3CC514.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBAN-PATCH -
REQUEST PAYLOAD - https://test.cstar.pagopa.it/bpd/hb/citizens/DDCDBP66A01L736X]
[INFO]    [27/11/2020 11.56.13 982] [pool-4-thread-313] [SCA - SESSIONID [7434949387A0C3FE7C7B4B132B3CC514.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBAN-PATCH RE
SPONSE - HTTP STATUS[200]]
[INFO]    [27/11/2020 11.56.13 983] [pool-4-thread-313] [SCA - SESSIONID [7434949387A0C3FE7C7B4B132B3CC514.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - method modificaImpostazioniIBAN-PATCH RE
SPONSE - HTTP ENTITY[{"validationStatus":"KO"}]]
[DEBUG]   [27/11/2020 11.56.13 984] [pool-4-thread-313] [SCA - SESSIONID [7434949387A0C3FE7C7B4B132B3CC514.mobile] -  COMMAND SCA [Async - v1/bancoposta/attivaIbanCashb
ack] - AUTH LEVEL [https://idp.poste.it/L2] - USERID [ddbpapp.ddcollaudo] - CASHBACK - WSCall - BonusPagamentiDigitaliService - modificaImpostazioniIBAN-PATCH [{"valida
tionStatus": "KO"}]]

**Comment by daniloMessinaSia** [comment]
potreste fornirci anche il body della richiesta?
Grazie

**Comment by lucasomarugasia** [comment]
2020/11/27 14:24:46:754 CET [DEBUG] wire - http-outgoing-0 >> "{"accountHolderSurname":"ddcollaudo","accountHolderCF":"DDCDBP66A01L736X","payoffInstr":"IT44L3608105138245630945642","accountHolderName":"ddbpapp","payoffInstrType":"IBAN"}"

**Comment by NicolaLamberti** [comment]
ci potreste indicare come mai sui vostri sistemi l'iban non è associato al CF indicato da noi? 

grazie 

Nicola

**Comment by DenisaBraho** [comment]
Ciao Nicola,
la mancata associazione potrebbe essere dovuta a dei casi di disallienamento attualmente presenti tra gli ambienti di test e prod.
In Produzione per gli Iban reali la risposta dovrebbe essere quella corretta.
Saluti

**Comment by NicolaLamberti** [comment]
@DenisaBraho è possibile "pulire" in ambiente di UAT/collaudo le info di questa utenza in particolare? Per noi l'iban è dell'utente che usiamo quindi dobbiamo ricevere un ok

Nicola
